[workspace]
members = [
    "crates/chematic-core",
    "crates/chematic-smiles",
    "crates/chematic-perception",
    "crates/chematic-mol",
    "crates/chematic-depict",
    "crates/chematic-chem",
    "crates/chematic-fp",
    "crates/chematic-smarts",
    "crates/chematic-3d",
    "crates/chematic-rxn",
    "crates/chematic-ff",
    "crates/chematic-ewald",
    "crates/chematic-inchi",
    "crates/chematic-wasm",
    "crates/chematic",
    "crates/chematic-iupac",
    "tools/gen_sa_table",
]
resolver = "2"

[workspace.package]
version = "0.1.112"
edition = "2024"
rust-version = "1.85"
authors = ["kent-tokyo <kent-tokyo@users.noreply.github.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/kent-tokyo/chematic"
homepage = "https://kent-tokyo.github.io/chematic/"
