[workspace]
members = [
    "crates/chematic-core",
    "crates/chematic-smiles",
    "crates/chematic-perception",
    "crates/chematic-mol",
    "crates/chematic-depict",
    "crates/chematic-chem",
    "crates/chematic-fp",
    "crates/chematic-smarts",
    "crates/chematic-3d",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["chematic contributors"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/kent-tokyo/chematic"
