//! XYZ / multi-frame XYZ (trajectory) file format.
//!
//! The XYZ format carries no bond information: each frame is an atom-count
//! line, a free-form comment line, then `element x y z` rows (Å). A
//! multi-frame ("trajectory") XYZ file is just several such frames
//! concatenated back-to-back with no separator between them -- each frame
//! is self-delimiting via its own atom-count line.
//!
//! ```text
//! 3
//! water, generated by chematic
//! O    0.00000000    0.00000000    0.00000000
//! H    0.75860000    0.00000000    0.50428400
//! H    0.75860000    0.00000000   -0.50428400
//! ```
//!
//! # Design decisions
//!
//! **Explicit hydrogens are kept as ordinary atoms, not folded into
//! `implicit_hcount()`.** `chematic_core::Molecule` normally represents only
//! heavy atoms (see the crate-level docs), but XYZ has no such concept --
//! every line in the file is a literal atom with a literal coordinate,
//! hydrogen included. Folding an XYZ `H` row into implicit-H bookkeeping
//! would silently discard that atom's real 3D position, defeating the
//! point of this format (conformer/QM coordinate exchange -- specifically
//! the experimental-conformer-RMSD benchmark fixtures this module exists to
//! support). [`XyzFrame::to_molecule`] therefore adds every atom in the
//! file, including H, as an explicit graph node in file order -- the same
//! treatment this crate's SDF/MOL reader already gives explicit H atoms
//! present in a V2000 atom block.
//!
//! **No connectivity or bond-order inference, not even opt-in.** XYZ has no
//! bonds. [`XyzFrame::to_molecule`] always returns a `Molecule` with zero
//! bonds; this module never guesses bonds from interatomic distance and
//! never guesses bond order. Distance-based connectivity inference belongs
//! at a higher crate layer -- `chematic-3d` already has `determine_bonds`
//! for exactly that, but `chematic-mol` does not (and should not) depend on
//! `chematic-3d`, so wiring it in here is out of scope for this module.
//!
//! **Extended XYZ is out of scope.** The ASE-style extended-XYZ comment
//! line (`Lattice="..." Properties=species:S:1:pos:R:3 ...`) is not parsed
//! -- the comment line is always kept verbatim as one opaque `String` on
//! [`XyzFrame::comment`].

use chematic_core::{Atom, Element, Molecule, MoleculeBuilder};

/// One atom row in an XYZ frame: element + Cartesian coordinates (Å).
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct XyzAtom {
    pub element: Element,
    pub x: f64,
    pub y: f64,
    pub z: f64,
}

/// A single parsed XYZ frame: atom rows plus the frame's comment line.
#[derive(Debug, Clone, PartialEq)]
pub struct XyzFrame {
    /// Atoms in file order.
    pub atoms: Vec<XyzAtom>,
    /// The frame's comment line (line 2 of the frame), verbatim. May be
    /// empty. Extended-XYZ key=value content, if present, is not parsed.
    pub comment: String,
}

impl XyzFrame {
    /// Build a `Molecule` from this frame: every atom (including hydrogen)
    /// becomes an explicit graph node, in file order, with zero bonds. See
    /// the module-level docs for why H is kept explicit here.
    pub fn to_molecule(&self) -> Molecule {
        let mut builder = MoleculeBuilder::new();
        for atom in &self.atoms {
            builder.add_atom(Atom::new(atom.element));
        }
        builder.build()
    }

    /// Cartesian coordinates (Å), in the same atom order as `to_molecule()`.
    pub fn coords(&self) -> Vec<(f64, f64, f64)> {
        self.atoms.iter().map(|a| (a.x, a.y, a.z)).collect()
    }
}

/// Errors that can occur while parsing an XYZ frame.
#[derive(Debug, Clone, PartialEq)]
pub enum XyzError {
    /// The atom-count line (line 1) is missing or not a valid non-negative integer.
    InvalidCountLine { line: usize, raw: String },
    /// The comment line (line 2) is missing (input ended after the count line).
    MissingCommentLine,
    /// An atom row does not have the form `element x y z`.
    InvalidAtomLine { line: usize, detail: String },
    /// An atom row's element symbol is not recognised.
    UnknownElement { symbol: String, line: usize },
    /// A coordinate value parsed but is NaN or infinite.
    NonFiniteCoordinate {
        line: usize,
        axis: &'static str,
        raw: String,
    },
    /// Fewer atom rows were present than the count line declared (input
    /// ended early). The opposite case -- *more* rows than declared -- is
    /// not representable as this variant: since frames have no separator,
    /// the extra rows are simply read as the start of the next frame, and
    /// surface (if at all) as `InvalidCountLine` when that next "count
    /// line" fails to parse as an integer.
    AtomCountMismatch { declared: usize, found: usize },
}

impl std::fmt::Display for XyzError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::InvalidCountLine { line, raw } => {
                write!(f, "invalid atom-count line {line}: '{raw}'")
            }
            Self::MissingCommentLine => write!(f, "missing comment line"),
            Self::InvalidAtomLine { line, detail } => {
                write!(f, "invalid atom line {line}: {detail}")
            }
            Self::UnknownElement { symbol, line } => {
                write!(f, "unknown element '{symbol}' at line {line}")
            }
            Self::NonFiniteCoordinate { line, axis, raw } => {
                write!(f, "non-finite {axis} coordinate '{raw}' at line {line}")
            }
            Self::AtomCountMismatch { declared, found } => {
                write!(
                    f,
                    "atom-count line declared {declared} atoms, found {found}"
                )
            }
        }
    }
}

impl std::error::Error for XyzError {}

/// Parse a single XYZ frame from the start of `text`. Trailing content
/// after the frame (e.g. further frames in a multi-frame trajectory file)
/// is ignored -- use [`XyzReader`] to iterate every frame in a multi-frame
/// file.
pub fn parse_xyz(text: &str) -> Result<XyzFrame, XyzError> {
    parse_one_frame(text).map(|(frame, _rest)| frame)
}

/// Split the next line off the front of `text`. Handles `\n` and `\r\n`
/// line endings and an unterminated final line. Returns `None` only when
/// `text` is entirely empty (no more input, not even a partial line).
///
/// This is the *only* place frame/line boundaries are computed -- earlier
/// revisions of this parser walked lines twice (once via `str::lines()` to
/// consume content, once via a byte-offset recomputation to find the next
/// frame's start) and those two mechanisms could disagree on inputs mixing
/// `\r\n` line endings with a non-`\n`-terminated final line. Tracking the
/// byte offset directly here, in one pass, makes that class of bug
/// unrepresentable.
fn next_line(text: &str) -> Option<(&str, &str)> {
    if text.is_empty() {
        return None;
    }
    match text.find('\n') {
        Some(nl) => Some((text[..nl].trim_end_matches('\r'), &text[nl + 1..])),
        None => Some((text.trim_end_matches('\r'), "")),
    }
}

/// Parse one frame starting at `text`, returning the frame and the
/// remaining unparsed input. Shared by [`parse_xyz`] and [`XyzReader`].
fn parse_one_frame(text: &str) -> Result<(XyzFrame, &str), XyzError> {
    let (count_line, rest) = next_line(text).ok_or(XyzError::InvalidCountLine {
        line: 1,
        raw: String::new(),
    })?;
    let declared: usize = count_line
        .trim()
        .parse()
        .map_err(|_| XyzError::InvalidCountLine {
            line: 1,
            raw: count_line.to_string(),
        })?;

    let (comment_line, mut rest) = next_line(rest).ok_or(XyzError::MissingCommentLine)?;
    let comment = comment_line.to_string();

    let mut atoms = Vec::with_capacity(declared);
    for lineno in (3usize..).take(declared) {
        let Some((raw_line, next_rest)) = next_line(rest) else {
            break;
        };
        rest = next_rest;

        let parts: Vec<&str> = raw_line.split_whitespace().collect();
        if parts.len() < 4 {
            return Err(XyzError::InvalidAtomLine {
                line: lineno,
                detail: format!("expected 'element x y z', got '{raw_line}'"),
            });
        }
        let element = Element::from_symbol(parts[0]).ok_or_else(|| XyzError::UnknownElement {
            symbol: parts[0].to_string(),
            line: lineno,
        })?;

        let parse_coord = |raw: &str, axis: &'static str| -> Result<f64, XyzError> {
            let v: f64 = raw.parse().map_err(|_| XyzError::InvalidAtomLine {
                line: lineno,
                detail: format!("cannot parse {axis} coordinate '{raw}'"),
            })?;
            if !v.is_finite() {
                return Err(XyzError::NonFiniteCoordinate {
                    line: lineno,
                    axis,
                    raw: raw.to_string(),
                });
            }
            Ok(v)
        };
        let x = parse_coord(parts[1], "x")?;
        let y = parse_coord(parts[2], "y")?;
        let z = parse_coord(parts[3], "z")?;
        atoms.push(XyzAtom { element, x, y, z });
    }

    if atoms.len() != declared {
        return Err(XyzError::AtomCountMismatch {
            declared,
            found: atoms.len(),
        });
    }

    Ok((XyzFrame { atoms, comment }, rest))
}

/// Iterator over frames in a multi-frame XYZ (trajectory) string.
///
/// Each call to `next()` returns the next [`XyzFrame`], or the first
/// [`XyzError`] encountered. Iteration stops for good after an error --
/// once a frame fails to parse, the byte offset of the *next* frame can no
/// longer be trusted, so `next()` returns `None` on every subsequent call
/// rather than risk mis-parsing garbage as a frame.
pub struct XyzReader<'a> {
    remaining: &'a str,
}

impl<'a> XyzReader<'a> {
    /// Create a new `XyzReader` over the given multi-frame XYZ string.
    pub fn new(input: &'a str) -> Self {
        Self { remaining: input }
    }
}

impl<'a> Iterator for XyzReader<'a> {
    type Item = Result<XyzFrame, XyzError>;

    fn next(&mut self) -> Option<Self::Item> {
        // A run of blank lines between frames is not part of the spec (each
        // frame is self-delimited by its own count line, no separator) but
        // is tolerated here -- some multi-frame XYZ writers leave a
        // trailing blank line at EOF.
        if self.remaining.trim().is_empty() {
            return None;
        }
        let leading_blank =
            self.remaining.len() - self.remaining.trim_start_matches(['\n', '\r']).len();
        self.remaining = &self.remaining[leading_blank..];

        match parse_one_frame(self.remaining) {
            Ok((frame, rest)) => {
                self.remaining = rest;
                Some(Ok(frame))
            }
            Err(e) => {
                self.remaining = "";
                Some(Err(e))
            }
        }
    }
}

/// Parse every frame in a multi-frame XYZ string. Stops and returns an
/// error on the first parse failure.
pub fn parse_xyz_all(input: &str) -> Result<Vec<XyzFrame>, XyzError> {
    XyzReader::new(input).collect()
}

/// Streaming writer for a (possibly multi-frame) XYZ file.
pub struct XyzWriter<W: std::io::Write> {
    writer: W,
}

impl<W: std::io::Write> XyzWriter<W> {
    pub fn new(writer: W) -> Self {
        Self { writer }
    }

    /// Write one frame. Call repeatedly for a multi-frame trajectory --
    /// frames are simply concatenated, matching the format's own layout.
    pub fn write_frame(&mut self, frame: &XyzFrame) -> std::io::Result<()> {
        writeln!(self.writer, "{}", frame.atoms.len())?;
        writeln!(self.writer, "{}", frame.comment)?;
        for atom in &frame.atoms {
            writeln!(
                self.writer,
                "{:<2} {:>15.8} {:>15.8} {:>15.8}",
                atom.element.symbol(),
                atom.x,
                atom.y,
                atom.z
            )?;
        }
        Ok(())
    }
}

/// Write a single XYZ frame to a string.
pub fn write_xyz(frame: &XyzFrame) -> String {
    let mut buf = Vec::new();
    XyzWriter::new(&mut buf)
        .write_frame(frame)
        .expect("writing to a Vec<u8> is infallible");
    String::from_utf8(buf).expect("XyzWriter only emits ASCII/UTF-8 text")
}

#[cfg(test)]
mod tests {
    use super::*;

    const WATER_XYZ: &str = "3\nwater\nO 0.00000000 0.00000000 0.00000000\nH 0.75860000 0.00000000 0.50428400\nH 0.75860000 0.00000000 -0.50428400\n";

    const METHANE_XYZ: &str = "5\nmethane, generated by chematic\nC 0.00000000 0.00000000 0.00000000\nH 0.62910000 0.62910000 0.62910000\nH -0.62910000 -0.62910000 0.62910000\nH -0.62910000 0.62910000 -0.62910000\nH 0.62910000 -0.62910000 -0.62910000\n";

    #[test]
    fn parse_water_fixture() {
        let frame = parse_xyz(WATER_XYZ).unwrap();
        assert_eq!(frame.comment, "water");
        assert_eq!(frame.atoms.len(), 3);
        assert_eq!(frame.atoms[0].element, Element::O);
        assert_eq!(frame.atoms[1].element, Element::H);
        assert_eq!(frame.atoms[2].element, Element::H);
        assert_eq!(frame.atoms[0].x, 0.0);
        assert_eq!(frame.atoms[1].x, 0.7586);
        assert_eq!(frame.atoms[2].z, -0.504284);

        let mol = frame.to_molecule();
        assert_eq!(mol.atom_count(), 3);
        assert_eq!(mol.atom(chematic_core::AtomIdx(0)).element, Element::O);
        assert_eq!(mol.atom(chematic_core::AtomIdx(1)).element, Element::H);
        assert_eq!(mol.atom(chematic_core::AtomIdx(2)).element, Element::H);
        assert_eq!(mol.bond_count(), 0);

        let coords = frame.coords();
        assert_eq!(coords.len(), 3);
        assert_eq!(coords[0], (0.0, 0.0, 0.0));
    }

    #[test]
    fn parse_methane_fixture() {
        let frame = parse_xyz(METHANE_XYZ).unwrap();
        assert_eq!(frame.atoms.len(), 5);
        assert_eq!(frame.atoms[0].element, Element::C);
        for atom in &frame.atoms[1..] {
            assert_eq!(atom.element, Element::H);
        }
        let mol = frame.to_molecule();
        assert_eq!(mol.atom_count(), 5);
        assert_eq!(mol.bond_count(), 0);
    }

    #[test]
    fn roundtrip_parse_write_parse() {
        let frame = parse_xyz(WATER_XYZ).unwrap();
        let written = write_xyz(&frame);
        let reparsed = parse_xyz(&written).unwrap();
        assert_eq!(frame, reparsed);
    }

    #[test]
    fn roundtrip_methane() {
        let frame = parse_xyz(METHANE_XYZ).unwrap();
        let written = write_xyz(&frame);
        let reparsed = parse_xyz(&written).unwrap();
        assert_eq!(frame, reparsed);
    }

    #[test]
    fn multi_frame_parsing() {
        let traj = format!("{WATER_XYZ}{METHANE_XYZ}{WATER_XYZ}");
        let frames = parse_xyz_all(&traj).unwrap();
        assert_eq!(frames.len(), 3);
        assert_eq!(frames[0].atoms.len(), 3);
        assert_eq!(frames[1].atoms.len(), 5);
        assert_eq!(frames[2].atoms.len(), 3);
        assert_eq!(frames[0], frames[2]);
    }

    #[test]
    fn multi_frame_reader_matches_parse_xyz_all() {
        let traj = format!("{WATER_XYZ}{METHANE_XYZ}");
        let via_reader: Vec<XyzFrame> = XyzReader::new(&traj).collect::<Result<_, _>>().unwrap();
        let via_all = parse_xyz_all(&traj).unwrap();
        assert_eq!(via_reader, via_all);
    }

    #[test]
    fn xyz_writer_multi_frame_roundtrips() {
        let f1 = parse_xyz(WATER_XYZ).unwrap();
        let f2 = parse_xyz(METHANE_XYZ).unwrap();
        let mut buf: Vec<u8> = Vec::new();
        {
            let mut w = XyzWriter::new(&mut buf);
            w.write_frame(&f1).unwrap();
            w.write_frame(&f2).unwrap();
        }
        let text = String::from_utf8(buf).unwrap();
        let frames = parse_xyz_all(&text).unwrap();
        assert_eq!(frames, vec![f1, f2]);
    }

    #[test]
    fn fails_closed_on_atom_count_mismatch() {
        let bad = "4\nwater with wrong count\nO 0.0 0.0 0.0\nH 0.0 0.0 1.0\nH 0.0 0.0 -1.0\n";
        let err = parse_xyz(bad).unwrap_err();
        assert_eq!(
            err,
            XyzError::AtomCountMismatch {
                declared: 4,
                found: 3
            }
        );
    }

    #[test]
    fn fails_closed_on_atom_count_mismatch_zero_rows() {
        let bad = "5\nno atom rows at all\n";
        let err = parse_xyz(bad).unwrap_err();
        assert_eq!(
            err,
            XyzError::AtomCountMismatch {
                declared: 5,
                found: 0
            }
        );
    }

    #[test]
    fn zero_atom_frame_is_legal() {
        let s = "0\nempty frame\n";
        let frame = parse_xyz(s).unwrap();
        assert!(frame.atoms.is_empty());
        assert_eq!(frame.comment, "empty frame");
        assert_eq!(frame.to_molecule().atom_count(), 0);
    }

    #[test]
    fn multi_frame_survives_crlf_and_missing_final_newline() {
        // Middle frame uses CRLF line endings; the whole trajectory has no
        // trailing newline after the last atom row. Both boundary cases
        // that could desync a naive two-pass line scanner.
        let traj = "1\nlf frame\nH 0.0 0.0 0.0\n\
                     2\r\ncrlf frame\r\nO 0.0 0.0 0.0\r\nH 1.0 0.0 0.0\r\n\
                     0\nempty frame\n\
                     1\nno trailing newline\nC 1.0 2.0 3.0";
        let frames = parse_xyz_all(traj).unwrap();
        assert_eq!(frames.len(), 4);
        assert_eq!(frames[0].atoms.len(), 1);
        assert_eq!(frames[1].atoms.len(), 2);
        assert_eq!(frames[1].comment, "crlf frame");
        assert!(frames[2].atoms.is_empty());
        assert_eq!(frames[3].atoms.len(), 1);
        assert_eq!(frames[3].atoms[0].element, Element::C);
        assert_eq!(frames[3].atoms[0].z, 3.0);
    }

    #[test]
    fn fails_closed_on_non_finite_coordinate() {
        let bad = "1\nbad\nH 0.0 0.0 nan\n";
        let err = parse_xyz(bad).unwrap_err();
        assert!(matches!(
            err,
            XyzError::InvalidAtomLine { .. } | XyzError::NonFiniteCoordinate { .. }
        ));

        let bad_inf = "1\nbad\nH 0.0 0.0 inf\n";
        let err = parse_xyz(bad_inf).unwrap_err();
        assert!(matches!(err, XyzError::NonFiniteCoordinate { .. }));
    }

    #[test]
    fn fails_closed_on_unknown_element() {
        let bad = "1\nbad element\nXx 0.0 0.0 0.0\n";
        let err = parse_xyz(bad).unwrap_err();
        assert_eq!(
            err,
            XyzError::UnknownElement {
                symbol: "Xx".to_string(),
                line: 3,
            }
        );
    }

    #[test]
    fn parse_xyz_ignores_trailing_frames() {
        let traj = format!("{WATER_XYZ}{METHANE_XYZ}");
        let frame = parse_xyz(&traj).unwrap();
        assert_eq!(frame.atoms.len(), 3);
    }

    #[test]
    fn empty_comment_line_is_preserved() {
        let s = "1\n\nC 0.0 0.0 0.0\n";
        let frame = parse_xyz(s).unwrap();
        assert_eq!(frame.comment, "");
    }
}
