//! XYZ / multi-frame XYZ (trajectory) file format.
//!
//! The XYZ format carries no bond information: each frame is an atom-count
//! line, a free-form comment line, then `element x y z` rows (Å). A
//! multi-frame ("trajectory") XYZ file is just several such frames
//! concatenated back-to-back with no separator between them -- each frame
//! is self-delimiting via its own atom-count line.
//!
//! ```text
//! 3
//! water, generated by chematic
//! O    0.00000000    0.00000000    0.00000000
//! H    0.75860000    0.00000000    0.50428400
//! H    0.75860000    0.00000000   -0.50428400
//! ```
//!
//! # Design decisions
//!
//! **Explicit hydrogens are kept as ordinary atoms, not folded into
//! `implicit_hcount()`.** `chematic_core::Molecule` normally represents only
//! heavy atoms (see the crate-level docs), but XYZ has no such concept --
//! every line in the file is a literal atom with a literal coordinate,
//! hydrogen included. Folding an XYZ `H` row into implicit-H bookkeeping
//! would silently discard that atom's real 3D position, defeating the
//! point of this format (conformer/QM coordinate exchange -- specifically
//! the experimental-conformer-RMSD benchmark fixtures this module exists to
//! support). [`XyzFrame::to_molecule`] therefore adds every atom in the
//! file, including H, as an explicit graph node in file order -- the same
//! treatment this crate's SDF/MOL reader already gives explicit H atoms
//! present in a V2000 atom block.
//!
//! **No connectivity or bond-order inference, not even opt-in.** XYZ has no
//! bonds. [`XyzFrame::to_molecule`] always returns a `Molecule` with zero
//! bonds; this module never guesses bonds from interatomic distance and
//! never guesses bond order. Distance-based connectivity inference belongs
//! at a higher crate layer -- `chematic-3d` already has `determine_bonds`
//! for exactly that, but `chematic-mol` does not (and should not) depend on
//! `chematic-3d`, so wiring it in here is out of scope for this module.
//!
//! # Extended XYZ (extxyz)
//!
//! The functions above ([`parse_xyz`], [`XyzReader`], [`write_xyz`], ...)
//! never interpret the comment line -- it is always kept verbatim as one
//! opaque `String` on [`XyzFrame::comment`].
//!
//! [`parse_extxyz`] / [`ExtxyzReader`] / [`write_extxyz`] are a *separate*
//! entry point over the same [`XyzFrame`] type that additionally
//! understands the ASE-style extended-XYZ comment line: a sequence of
//! `key=value` pairs (quoted values may contain spaces), where two keys are
//! special-cased into typed fields:
//!
//! - `Lattice="ax ay az bx by bz cx cy cz"` -- a 3x3 cell matrix, row-major
//!   -> [`XyzFrame::lattice`].
//! - `Properties=species:S:1:pos:R:3[:name:type:count]*` -- the per-atom
//!   column layout. `species`/`pos` always map onto
//!   [`XyzAtom::element`]/`x,y,z` (this crate requires them first, in that
//!   order, matching every ASE-written extxyz file); any further columns
//!   (e.g. `forces:R:3`, `charge:R:1`) become [`XyzFrame::properties`].
//!   When `Properties` is absent, the default `species:S:1:pos:R:3` applies
//!   -- this is what makes an ordinary XYZ file parse as a valid,
//!   zero-extra-property extxyz frame too.
//!
//! Every other `key=value` pair (`energy=...`, `pbc=...`, arbitrary
//! metadata) is kept, in first-seen order, on [`XyzFrame::info`].
//!
//! A comment line containing no `=` at all is treated as an ordinary,
//! unstructured comment (`lattice: None`, `properties: []`, `info: []`) --
//! this is the case that keeps a plain XYZ file's comment line
//! byte-identical through the extxyz reader/writer (see [`write_extxyz`]).
//! Once any `=` is present, the whole line must parse as `key=value`
//! tokens or [`parse_extxyz`] fails closed.

use std::collections::HashSet;

use chematic_core::{Atom, Element, Molecule, MoleculeBuilder};

/// The declared type of an extended-XYZ `Properties=` column
/// (`R`=real, `I`=integer, `S`=string, `L`=logical).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum XyzPropertyKind {
    Real,
    Integer,
    String,
    Logical,
}

/// A single per-atom scalar value in an extended-XYZ property column.
#[derive(Debug, Clone, PartialEq)]
pub enum XyzValue {
    Real(f64),
    Integer(i64),
    /// Written as a single unquoted whitespace-delimited token (matching
    /// how [`parse_extxyz`] reads an `S`-typed atom-row column): a value
    /// containing whitespace round-trips through [`write_extxyz`] as *more
    /// than one* atom-row token, desyncing every column after it on
    /// reparse. `write_extxyz` does not check for this (only
    /// [`XyzFrame::info`]/[`XyzProperty::name`] are validated, see
    /// `validate_extxyz_writable`) -- avoid whitespace in `Str` property
    /// values when hand-building a frame. Not reachable from the
    /// Python/WASM `to_extxyz` bindings, which only accept real-valued
    /// (`R`) properties.
    Str(String),
    Logical(bool),
}

/// One extended-XYZ per-atom property column beyond `species`/`pos`
/// (e.g. `forces:R:3`, `charge:R:1`), as declared in the frame's
/// `Properties=` key.
#[derive(Debug, Clone, PartialEq)]
pub struct XyzProperty {
    pub name: String,
    pub kind: XyzPropertyKind,
    /// Number of scalar components per atom (e.g. 3 for `forces:R:3`).
    pub count: usize,
    /// `values[atom_index]` has length `count`, same atom order as
    /// [`XyzFrame::atoms`].
    pub values: Vec<Vec<XyzValue>>,
}

/// One atom row in an XYZ frame: element + Cartesian coordinates (Å).
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct XyzAtom {
    pub element: Element,
    pub x: f64,
    pub y: f64,
    pub z: f64,
}

/// A single parsed XYZ frame: atom rows plus the frame's comment line.
#[derive(Debug, Clone, PartialEq)]
pub struct XyzFrame {
    /// Atoms in file order.
    pub atoms: Vec<XyzAtom>,
    /// The frame's comment line (line 2 of the frame), verbatim. May be
    /// empty. Always populated by [`parse_xyz`]/[`parse_extxyz`] alike.
    /// [`write_extxyz`] uses this verbatim only when `lattice`, `properties`
    /// and `info` are all empty -- see the module-level "Extended XYZ" docs.
    pub comment: String,
    /// Extended-XYZ `Lattice=` cell matrix (row-major 3x3), if present.
    /// Always `None` for frames from [`parse_xyz`]/[`XyzReader`].
    pub lattice: Option<[f64; 9]>,
    /// Extended-XYZ per-atom property columns beyond `species`/`pos` (which
    /// map onto [`XyzAtom`] itself), e.g. `forces:R:3` or `charge:R:1`.
    /// Always empty for frames from [`parse_xyz`]/[`XyzReader`].
    pub properties: Vec<XyzProperty>,
    /// Extended-XYZ frame-level `key=value` metadata other than
    /// `Lattice`/`Properties` (e.g. `energy`, `pbc`, `config_type`), in
    /// first-seen order. Always empty for frames from
    /// [`parse_xyz`]/[`XyzReader`].
    pub info: Vec<(String, String)>,
}

impl XyzFrame {
    /// Build a `Molecule` from this frame: every atom (including hydrogen)
    /// becomes an explicit graph node, in file order, with zero bonds. See
    /// the module-level docs for why H is kept explicit here.
    pub fn to_molecule(&self) -> Molecule {
        let mut builder = MoleculeBuilder::new();
        for atom in &self.atoms {
            builder.add_atom(Atom::new(atom.element));
        }
        builder.build()
    }

    /// Cartesian coordinates (Å), in the same atom order as `to_molecule()`.
    pub fn coords(&self) -> Vec<(f64, f64, f64)> {
        self.atoms.iter().map(|a| (a.x, a.y, a.z)).collect()
    }
}

/// Errors that can occur while parsing an XYZ frame.
#[derive(Debug, Clone, PartialEq)]
pub enum XyzError {
    /// A configured input, frame, or line limit was exceeded.
    ResourceLimit {
        resource: &'static str,
        actual: usize,
        limit: usize,
    },
    /// The atom-count line (line 1) is missing or not a valid non-negative integer.
    InvalidCountLine { line: usize, raw: String },
    /// The comment line (line 2) is missing (input ended after the count line).
    MissingCommentLine,
    /// An atom row does not have the form `element x y z`.
    InvalidAtomLine { line: usize, detail: String },
    /// An atom row's element symbol is not recognised.
    UnknownElement { symbol: String, line: usize },
    /// A coordinate value parsed but is NaN or infinite.
    NonFiniteCoordinate {
        line: usize,
        axis: &'static str,
        raw: String,
    },
    /// Fewer atom rows were present than the count line declared (input
    /// ended early). The opposite case -- *more* rows than declared -- is
    /// not representable as this variant: since frames have no separator,
    /// the extra rows are simply read as the start of the next frame, and
    /// surface (if at all) as `InvalidCountLine` when that next "count
    /// line" fails to parse as an integer.
    AtomCountMismatch { declared: usize, found: usize },
    /// [`parse_extxyz`] only: a comment-line token has an empty key (a
    /// stray `=` with nothing before it). A bare key with no `=value` at
    /// all is *not* this error -- it is a valid implicit boolean flag,
    /// defaulting to `"T"` (matches ASE's own convention).
    InvalidInfoField { line: usize, detail: String },
    /// [`parse_extxyz`] only: a quoted value (`key="..."`) in the comment
    /// line has no closing quote.
    UnterminatedQuote { line: usize, key: String },
    /// [`parse_extxyz`] only: the same key appears twice in the comment
    /// line.
    DuplicateInfoKey { line: usize, key: String },
    /// [`parse_extxyz`] only: `Lattice=` does not contain exactly 9
    /// whitespace-separated finite numbers.
    InvalidLattice { line: usize, detail: String },
    /// [`parse_extxyz`] only: `Properties=` is malformed, or does not start
    /// with `species:S:1:pos:R:3`.
    InvalidProperties { line: usize, detail: String },
    /// [`parse_extxyz`] only: an atom row's whitespace-token count doesn't
    /// match what the frame's `Properties` columns declare.
    PropertyColumnMismatch {
        line: usize,
        expected: usize,
        found: usize,
    },
    /// [`parse_extxyz`] only: a per-atom property value (beyond
    /// `species`/`pos`) failed to parse as its declared type, or was
    /// non-finite for an `R` column.
    InvalidPropertyValue {
        line: usize,
        property: String,
        raw: String,
    },
    /// [`write_extxyz`]/[`ExtxyzWriter::write_frame`] only: an
    /// `XyzFrame::info` key/value or [`XyzProperty::name`] contains a
    /// character extxyz `key=value` syntax cannot represent (see
    /// [`validate_extxyz_writable`]) -- never produced by this module's own
    /// parsers, only by writing a hand-built `XyzFrame`.
    UnwritableMetadata { detail: String },
}

impl std::fmt::Display for XyzError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ResourceLimit {
                resource,
                actual,
                limit,
            } => write!(f, "XYZ {resource} exceeds limit {limit} (got {actual})"),
            Self::InvalidCountLine { line, raw } => {
                write!(f, "invalid atom-count line {line}: '{raw}'")
            }
            Self::MissingCommentLine => write!(f, "missing comment line"),
            Self::InvalidAtomLine { line, detail } => {
                write!(f, "invalid atom line {line}: {detail}")
            }
            Self::UnknownElement { symbol, line } => {
                write!(f, "unknown element '{symbol}' at line {line}")
            }
            Self::NonFiniteCoordinate { line, axis, raw } => {
                write!(f, "non-finite {axis} coordinate '{raw}' at line {line}")
            }
            Self::AtomCountMismatch { declared, found } => {
                write!(
                    f,
                    "atom-count line declared {declared} atoms, found {found}"
                )
            }
            Self::InvalidInfoField { line, detail } => {
                write!(f, "invalid extxyz info field at line {line}: {detail}")
            }
            Self::UnterminatedQuote { line, key } => {
                write!(
                    f,
                    "unterminated quoted value for key '{key}' at line {line}"
                )
            }
            Self::DuplicateInfoKey { line, key } => {
                write!(f, "duplicate extxyz info key '{key}' at line {line}")
            }
            Self::InvalidLattice { line, detail } => {
                write!(f, "invalid Lattice at line {line}: {detail}")
            }
            Self::InvalidProperties { line, detail } => {
                write!(f, "invalid Properties at line {line}: {detail}")
            }
            Self::PropertyColumnMismatch {
                line,
                expected,
                found,
            } => {
                write!(
                    f,
                    "atom line {line}: Properties columns declare {expected} value(s), found {found}"
                )
            }
            Self::InvalidPropertyValue {
                line,
                property,
                raw,
            } => {
                write!(
                    f,
                    "invalid value '{raw}' for property '{property}' at line {line}"
                )
            }
            Self::UnwritableMetadata { detail } => {
                write!(f, "cannot write extxyz frame: {detail}")
            }
        }
    }
}

impl std::error::Error for XyzError {}

/// Resource limits for XYZ and Extended XYZ parsing.
#[derive(Debug, Clone, Copy)]
pub struct XyzParseLimits {
    /// Maximum input size in bytes.
    pub max_input_bytes: usize,
    /// Maximum atoms declared in one frame.
    pub max_atoms_per_frame: usize,
    /// Maximum number of frames in an all-frames parse.
    pub max_frames: usize,
    /// Maximum physical line size in bytes.
    pub max_line_bytes: usize,
}

impl Default for XyzParseLimits {
    fn default() -> Self {
        Self {
            max_input_bytes: 1 << 30,
            max_atoms_per_frame: 1_000_000,
            max_frames: 100_000,
            max_line_bytes: 16 << 20,
        }
    }
}

fn validate_xyz_limits(text: &str, limits: &XyzParseLimits) -> Result<(), XyzError> {
    if text.len() > limits.max_input_bytes {
        return Err(XyzError::ResourceLimit {
            resource: "input bytes",
            actual: text.len(),
            limit: limits.max_input_bytes,
        });
    }
    for line in text.lines() {
        if line.len() > limits.max_line_bytes {
            return Err(XyzError::ResourceLimit {
                resource: "line bytes",
                actual: line.len(),
                limit: limits.max_line_bytes,
            });
        }
    }
    let mut lines = text.lines();
    let mut frames = 0usize;
    while let Some(count_line) = lines.next() {
        let Ok(count) = count_line.trim().parse::<usize>() else {
            break;
        };
        frames = frames.saturating_add(1);
        if frames > limits.max_frames {
            return Err(XyzError::ResourceLimit {
                resource: "frames",
                actual: frames,
                limit: limits.max_frames,
            });
        }
        if count > limits.max_atoms_per_frame {
            return Err(XyzError::ResourceLimit {
                resource: "atoms per frame",
                actual: count,
                limit: limits.max_atoms_per_frame,
            });
        }
        let _ = lines.next();
        for _ in 0..count {
            let _ = lines.next();
        }
    }
    Ok(())
}

/// Parse a single XYZ frame from the start of `text`. Trailing content
/// after the frame (e.g. further frames in a multi-frame trajectory file)
/// is ignored -- use [`XyzReader`] to iterate every frame in a multi-frame
/// file.
pub fn parse_xyz(text: &str) -> Result<XyzFrame, XyzError> {
    parse_xyz_with_limits(text, &XyzParseLimits::default())
}

/// Parse a single XYZ frame while enforcing resource limits.
pub fn parse_xyz_with_limits(text: &str, limits: &XyzParseLimits) -> Result<XyzFrame, XyzError> {
    validate_xyz_limits(text, limits)?;
    parse_one_frame(text).map(|(frame, _rest)| frame)
}

/// Split the next line off the front of `text`. Handles `\n` and `\r\n`
/// line endings and an unterminated final line. Returns `None` only when
/// `text` is entirely empty (no more input, not even a partial line).
///
/// This is the *only* place frame/line boundaries are computed -- earlier
/// revisions of this parser walked lines twice (once via `str::lines()` to
/// consume content, once via a byte-offset recomputation to find the next
/// frame's start) and those two mechanisms could disagree on inputs mixing
/// `\r\n` line endings with a non-`\n`-terminated final line. Tracking the
/// byte offset directly here, in one pass, makes that class of bug
/// unrepresentable.
fn next_line(text: &str) -> Option<(&str, &str)> {
    if text.is_empty() {
        return None;
    }
    match text.find('\n') {
        Some(nl) => Some((text[..nl].trim_end_matches('\r'), &text[nl + 1..])),
        None => Some((text.trim_end_matches('\r'), "")),
    }
}

/// Parse one frame starting at `text`, returning the frame and the
/// remaining unparsed input. Shared by [`parse_xyz`] and [`XyzReader`].
fn parse_one_frame(text: &str) -> Result<(XyzFrame, &str), XyzError> {
    let (count_line, rest) = next_line(text).ok_or(XyzError::InvalidCountLine {
        line: 1,
        raw: String::new(),
    })?;
    let declared: usize = count_line
        .trim()
        .parse()
        .map_err(|_| XyzError::InvalidCountLine {
            line: 1,
            raw: count_line.to_string(),
        })?;

    let (comment_line, mut rest) = next_line(rest).ok_or(XyzError::MissingCommentLine)?;
    let comment = comment_line.to_string();

    let mut atoms = Vec::with_capacity(declared);
    for lineno in (3usize..).take(declared) {
        let Some((raw_line, next_rest)) = next_line(rest) else {
            break;
        };
        rest = next_rest;

        let parts: Vec<&str> = raw_line.split_whitespace().collect();
        if parts.len() < 4 {
            return Err(XyzError::InvalidAtomLine {
                line: lineno,
                detail: format!("expected 'element x y z', got '{raw_line}'"),
            });
        }
        let element = Element::from_symbol(parts[0]).ok_or_else(|| XyzError::UnknownElement {
            symbol: parts[0].to_string(),
            line: lineno,
        })?;

        let parse_coord = |raw: &str, axis: &'static str| -> Result<f64, XyzError> {
            let v: f64 = raw.parse().map_err(|_| XyzError::InvalidAtomLine {
                line: lineno,
                detail: format!("cannot parse {axis} coordinate '{raw}'"),
            })?;
            if !v.is_finite() {
                return Err(XyzError::NonFiniteCoordinate {
                    line: lineno,
                    axis,
                    raw: raw.to_string(),
                });
            }
            Ok(v)
        };
        let x = parse_coord(parts[1], "x")?;
        let y = parse_coord(parts[2], "y")?;
        let z = parse_coord(parts[3], "z")?;
        atoms.push(XyzAtom { element, x, y, z });
    }

    if atoms.len() != declared {
        return Err(XyzError::AtomCountMismatch {
            declared,
            found: atoms.len(),
        });
    }

    Ok((
        XyzFrame {
            atoms,
            comment,
            lattice: None,
            properties: Vec::new(),
            info: Vec::new(),
        },
        rest,
    ))
}

/// Iterator over frames in a multi-frame XYZ (trajectory) string.
///
/// Each call to `next()` returns the next [`XyzFrame`], or the first
/// [`XyzError`] encountered. Iteration stops for good after an error --
/// once a frame fails to parse, the byte offset of the *next* frame can no
/// longer be trusted, so `next()` returns `None` on every subsequent call
/// rather than risk mis-parsing garbage as a frame.
pub struct XyzReader<'a> {
    remaining: &'a str,
}

impl<'a> XyzReader<'a> {
    /// Create a new `XyzReader` over the given multi-frame XYZ string.
    pub fn new(input: &'a str) -> Self {
        Self { remaining: input }
    }
}

impl<'a> Iterator for XyzReader<'a> {
    type Item = Result<XyzFrame, XyzError>;

    fn next(&mut self) -> Option<Self::Item> {
        // A run of blank lines between frames is not part of the spec (each
        // frame is self-delimited by its own count line, no separator) but
        // is tolerated here -- some multi-frame XYZ writers leave a
        // trailing blank line at EOF.
        if self.remaining.trim().is_empty() {
            return None;
        }
        let leading_blank =
            self.remaining.len() - self.remaining.trim_start_matches(['\n', '\r']).len();
        self.remaining = &self.remaining[leading_blank..];

        match parse_one_frame(self.remaining) {
            Ok((frame, rest)) => {
                self.remaining = rest;
                Some(Ok(frame))
            }
            Err(e) => {
                self.remaining = "";
                Some(Err(e))
            }
        }
    }
}

/// Parse every frame in a multi-frame XYZ string. Stops and returns an
/// error on the first parse failure.
pub fn parse_xyz_all(input: &str) -> Result<Vec<XyzFrame>, XyzError> {
    parse_xyz_all_with_limits(input, &XyzParseLimits::default())
}

/// Parse every XYZ frame while enforcing resource limits.
pub fn parse_xyz_all_with_limits(
    input: &str,
    limits: &XyzParseLimits,
) -> Result<Vec<XyzFrame>, XyzError> {
    validate_xyz_limits(input, limits)?;
    XyzReader::new(input).collect()
}

/// Streaming writer for a (possibly multi-frame) XYZ file.
pub struct XyzWriter<W: std::io::Write> {
    writer: W,
}

impl<W: std::io::Write> XyzWriter<W> {
    pub fn new(writer: W) -> Self {
        Self { writer }
    }

    /// Write one frame. Call repeatedly for a multi-frame trajectory --
    /// frames are simply concatenated, matching the format's own layout.
    pub fn write_frame(&mut self, frame: &XyzFrame) -> std::io::Result<()> {
        writeln!(self.writer, "{}", frame.atoms.len())?;
        writeln!(self.writer, "{}", frame.comment)?;
        for atom in &frame.atoms {
            writeln!(
                self.writer,
                "{:<2} {:>15.8} {:>15.8} {:>15.8}",
                atom.element.symbol(),
                atom.x,
                atom.y,
                atom.z
            )?;
        }
        Ok(())
    }
}

/// Write a single XYZ frame to a string.
pub fn write_xyz(frame: &XyzFrame) -> String {
    let mut buf = Vec::new();
    XyzWriter::new(&mut buf)
        .write_frame(frame)
        .expect("writing to a Vec<u8> is infallible");
    String::from_utf8(buf).expect("XyzWriter only emits ASCII/UTF-8 text")
}

// ---------------------------------------------------------------------------
// Extended XYZ (extxyz)
// ---------------------------------------------------------------------------

/// Tokenize an extxyz comment line into ordered `(key, value)` pairs.
/// Quoted values (`key="a b c"`) may contain spaces; a backslash inside a
/// quoted value escapes the following character verbatim (so `\"` is a
/// literal quote, `\\` a literal backslash), matching ASE's own
/// `key_val_str_to_dict` char-by-char escape handling. Unquoted values run
/// to the next whitespace. A bare key with no `=value` at all defaults to
/// value `"T"` (ASE's own convention for an implicit boolean flag -- e.g.
/// `constrained` alone means `constrained=T`), rather than being an error.
/// `lineno` only annotates errors.
fn tokenize_info_line(line: &str, lineno: usize) -> Result<Vec<(String, String)>, XyzError> {
    let chars: Vec<char> = line.chars().collect();
    let n = chars.len();
    let mut i = 0;
    let mut pairs = Vec::new();

    while i < n {
        while i < n && chars[i].is_whitespace() {
            i += 1;
        }
        if i >= n {
            break;
        }
        let key_start = i;
        while i < n && chars[i] != '=' && !chars[i].is_whitespace() {
            i += 1;
        }
        let key: String = chars[key_start..i].iter().collect();
        if key.is_empty() {
            // Only reachable via a stray '=' with nothing before it (e.g.
            // "=foo" or "==bar") -- whitespace already advanced past above,
            // so a real key never starts empty.
            return Err(XyzError::InvalidInfoField {
                line: lineno,
                detail: "empty key before '='".to_string(),
            });
        }
        if i >= n || chars[i] != '=' {
            pairs.push((key, "T".to_string()));
            continue;
        }
        i += 1; // consume '='

        let value: String = if i < n && chars[i] == '"' {
            i += 1;
            let mut v = String::new();
            loop {
                if i >= n {
                    return Err(XyzError::UnterminatedQuote { line: lineno, key });
                }
                match chars[i] {
                    '"' => {
                        i += 1;
                        break;
                    }
                    '\\' if i + 1 < n => {
                        v.push(chars[i + 1]);
                        i += 2;
                    }
                    c => {
                        v.push(c);
                        i += 1;
                    }
                }
            }
            v
        } else {
            let val_start = i;
            while i < n && !chars[i].is_whitespace() {
                i += 1;
            }
            chars[val_start..i].iter().collect()
        };
        pairs.push((key, value));
    }
    Ok(pairs)
}

/// Parse a `Lattice=` value: exactly 9 whitespace-separated finite numbers.
fn parse_lattice(raw: &str, lineno: usize) -> Result<[f64; 9], XyzError> {
    let parts: Vec<&str> = raw.split_whitespace().collect();
    if parts.len() != 9 {
        return Err(XyzError::InvalidLattice {
            line: lineno,
            detail: format!("expected 9 numbers, found {}", parts.len()),
        });
    }
    let mut out = [0.0; 9];
    for (i, p) in parts.iter().enumerate() {
        let v: f64 = p.parse().map_err(|_| XyzError::InvalidLattice {
            line: lineno,
            detail: format!("cannot parse '{p}' as a number"),
        })?;
        if !v.is_finite() {
            return Err(XyzError::InvalidLattice {
                line: lineno,
                detail: format!("non-finite value '{p}'"),
            });
        }
        out[i] = v;
    }
    Ok(out)
}

/// One column parsed from a `Properties=` value: `(name, kind, count)`.
type PropertyColumn = (String, XyzPropertyKind, usize);

/// Parse a `Properties=` value into its column list. Requires the first two
/// columns to be exactly `species:S:1` and `pos:R:3` (universal in
/// ASE-written extxyz) -- any further columns become [`XyzFrame::properties`].
fn parse_properties(raw: &str, lineno: usize) -> Result<Vec<PropertyColumn>, XyzError> {
    let parts: Vec<&str> = raw.split(':').collect();
    if parts.is_empty() || !parts.len().is_multiple_of(3) {
        return Err(XyzError::InvalidProperties {
            line: lineno,
            detail: format!("'{raw}' is not a multiple-of-3 colon-separated list"),
        });
    }
    let mut columns = Vec::with_capacity(parts.len() / 3);
    for chunk in parts.chunks(3) {
        let name = chunk[0].to_string();
        let kind = match chunk[1] {
            "R" => XyzPropertyKind::Real,
            "I" => XyzPropertyKind::Integer,
            "S" => XyzPropertyKind::String,
            "L" => XyzPropertyKind::Logical,
            other => {
                return Err(XyzError::InvalidProperties {
                    line: lineno,
                    detail: format!("unknown column type '{other}' for '{name}'"),
                });
            }
        };
        let count: usize = chunk[2].parse().map_err(|_| XyzError::InvalidProperties {
            line: lineno,
            detail: format!("invalid column count '{}' for '{name}'", chunk[2]),
        })?;
        if count == 0 {
            return Err(XyzError::InvalidProperties {
                line: lineno,
                detail: format!("column '{name}' declares 0 components"),
            });
        }
        columns.push((name, kind, count));
    }
    let valid_prefix = columns.len() >= 2
        && columns[0].0 == "species"
        && columns[0].1 == XyzPropertyKind::String
        && columns[0].2 == 1
        && columns[1].0 == "pos"
        && columns[1].1 == XyzPropertyKind::Real
        && columns[1].2 == 3;
    if !valid_prefix {
        return Err(XyzError::InvalidProperties {
            line: lineno,
            detail: format!("'{raw}' must start with 'species:S:1:pos:R:3'"),
        });
    }
    Ok(columns)
}

/// Parse one extxyz frame starting at `text`, returning the frame and the
/// remaining unparsed input. Shared by [`parse_extxyz`] and [`ExtxyzReader`].
fn parse_one_frame_ext(text: &str) -> Result<(XyzFrame, &str), XyzError> {
    let (count_line, rest) = next_line(text).ok_or(XyzError::InvalidCountLine {
        line: 1,
        raw: String::new(),
    })?;
    let declared: usize = count_line
        .trim()
        .parse()
        .map_err(|_| XyzError::InvalidCountLine {
            line: 1,
            raw: count_line.to_string(),
        })?;

    let (comment_line, mut rest) = next_line(rest).ok_or(XyzError::MissingCommentLine)?;
    let comment = comment_line.to_string();

    // A comment line with no '=' at all is an ordinary, unstructured
    // comment, not extxyz metadata -- this is what makes a plain XYZ file
    // parse (and round-trip) through this reader too. See module docs.
    let (lattice, properties_columns, info) = if comment_line.contains('=') {
        let pairs = tokenize_info_line(comment_line, 2)?;
        let mut lattice = None;
        let mut properties_columns: Option<Vec<PropertyColumn>> = None;
        let mut info = Vec::new();
        let mut seen: HashSet<String> = HashSet::new();
        for (k, v) in pairs {
            if !seen.insert(k.clone()) {
                return Err(XyzError::DuplicateInfoKey { line: 2, key: k });
            }
            match k.as_str() {
                "Lattice" => lattice = Some(parse_lattice(&v, 2)?),
                "Properties" => properties_columns = Some(parse_properties(&v, 2)?),
                _ => info.push((k, v)),
            }
        }
        (lattice, properties_columns, info)
    } else {
        (None, None, Vec::new())
    };
    let columns = properties_columns.unwrap_or_else(|| {
        vec![
            ("species".to_string(), XyzPropertyKind::String, 1),
            ("pos".to_string(), XyzPropertyKind::Real, 3),
        ]
    });
    let extra_columns = &columns[2..];
    let expected_tokens: usize = columns.iter().map(|(_, _, c)| c).sum();

    let mut atoms = Vec::with_capacity(declared);
    let mut extra_values: Vec<Vec<Vec<XyzValue>>> = vec![Vec::new(); extra_columns.len()];

    for lineno in (3usize..).take(declared) {
        let Some((raw_line, next_rest)) = next_line(rest) else {
            break;
        };
        rest = next_rest;

        let tokens: Vec<&str> = raw_line.split_whitespace().collect();
        if tokens.len() != expected_tokens {
            return Err(XyzError::PropertyColumnMismatch {
                line: lineno,
                expected: expected_tokens,
                found: tokens.len(),
            });
        }

        let element = Element::from_symbol(tokens[0]).ok_or_else(|| XyzError::UnknownElement {
            symbol: tokens[0].to_string(),
            line: lineno,
        })?;
        let parse_coord = |raw: &str, axis: &'static str| -> Result<f64, XyzError> {
            let v: f64 = raw.parse().map_err(|_| XyzError::InvalidAtomLine {
                line: lineno,
                detail: format!("cannot parse {axis} coordinate '{raw}'"),
            })?;
            if !v.is_finite() {
                return Err(XyzError::NonFiniteCoordinate {
                    line: lineno,
                    axis,
                    raw: raw.to_string(),
                });
            }
            Ok(v)
        };
        let x = parse_coord(tokens[1], "x")?;
        let y = parse_coord(tokens[2], "y")?;
        let z = parse_coord(tokens[3], "z")?;
        atoms.push(XyzAtom { element, x, y, z });

        let mut tok_idx = 4;
        for (col_idx, (name, kind, count)) in extra_columns.iter().enumerate() {
            let mut vals = Vec::with_capacity(*count);
            for _ in 0..*count {
                let raw = tokens[tok_idx];
                tok_idx += 1;
                let value = match kind {
                    XyzPropertyKind::Real => {
                        let v: f64 = raw.parse().map_err(|_| XyzError::InvalidPropertyValue {
                            line: lineno,
                            property: name.clone(),
                            raw: raw.to_string(),
                        })?;
                        if !v.is_finite() {
                            return Err(XyzError::InvalidPropertyValue {
                                line: lineno,
                                property: name.clone(),
                                raw: raw.to_string(),
                            });
                        }
                        XyzValue::Real(v)
                    }
                    XyzPropertyKind::Integer => {
                        let v: i64 = raw.parse().map_err(|_| XyzError::InvalidPropertyValue {
                            line: lineno,
                            property: name.clone(),
                            raw: raw.to_string(),
                        })?;
                        XyzValue::Integer(v)
                    }
                    XyzPropertyKind::String => XyzValue::Str(raw.to_string()),
                    XyzPropertyKind::Logical => match raw {
                        "T" | "True" | "true" | "1" => XyzValue::Logical(true),
                        "F" | "False" | "false" | "0" => XyzValue::Logical(false),
                        _ => {
                            return Err(XyzError::InvalidPropertyValue {
                                line: lineno,
                                property: name.clone(),
                                raw: raw.to_string(),
                            });
                        }
                    },
                };
                vals.push(value);
            }
            extra_values[col_idx].push(vals);
        }
    }

    if atoms.len() != declared {
        return Err(XyzError::AtomCountMismatch {
            declared,
            found: atoms.len(),
        });
    }

    let properties = extra_columns
        .iter()
        .zip(extra_values)
        .map(|((name, kind, count), values)| XyzProperty {
            name: name.clone(),
            kind: *kind,
            count: *count,
            values,
        })
        .collect();

    Ok((
        XyzFrame {
            atoms,
            comment,
            lattice,
            properties,
            info,
        },
        rest,
    ))
}

/// Parse a single extended-XYZ (extxyz) frame from the start of `text`.
/// Trailing content is ignored, same as [`parse_xyz`] -- use
/// [`ExtxyzReader`] to iterate every frame in a multi-frame file. See the
/// module-level "Extended XYZ" docs for what `Lattice=`/`Properties=`
/// support covers.
pub fn parse_extxyz(text: &str) -> Result<XyzFrame, XyzError> {
    parse_extxyz_with_limits(text, &XyzParseLimits::default())
}

/// Parse a single Extended XYZ frame while enforcing resource limits.
pub fn parse_extxyz_with_limits(text: &str, limits: &XyzParseLimits) -> Result<XyzFrame, XyzError> {
    validate_xyz_limits(text, limits)?;
    parse_one_frame_ext(text).map(|(frame, _rest)| frame)
}

/// Iterator over frames in a multi-frame extxyz (trajectory) string. Same
/// stop-on-first-error behavior as [`XyzReader`].
pub struct ExtxyzReader<'a> {
    remaining: &'a str,
}

impl<'a> ExtxyzReader<'a> {
    /// Create a new `ExtxyzReader` over the given multi-frame extxyz string.
    pub fn new(input: &'a str) -> Self {
        Self { remaining: input }
    }
}

impl<'a> Iterator for ExtxyzReader<'a> {
    type Item = Result<XyzFrame, XyzError>;

    fn next(&mut self) -> Option<Self::Item> {
        if self.remaining.trim().is_empty() {
            return None;
        }
        let leading_blank =
            self.remaining.len() - self.remaining.trim_start_matches(['\n', '\r']).len();
        self.remaining = &self.remaining[leading_blank..];

        match parse_one_frame_ext(self.remaining) {
            Ok((frame, rest)) => {
                self.remaining = rest;
                Some(Ok(frame))
            }
            Err(e) => {
                self.remaining = "";
                Some(Err(e))
            }
        }
    }
}

/// Parse every frame in a multi-frame extxyz string. Stops and returns an
/// error on the first parse failure.
pub fn parse_extxyz_all(input: &str) -> Result<Vec<XyzFrame>, XyzError> {
    validate_xyz_limits(input, &XyzParseLimits::default())?;
    ExtxyzReader::new(input).collect()
}

fn format_xyz_value(v: &XyzValue) -> String {
    match v {
        XyzValue::Real(x) => x.to_string(),
        XyzValue::Integer(i) => i.to_string(),
        XyzValue::Str(s) => s.clone(),
        XyzValue::Logical(b) => (if *b { "T" } else { "F" }).to_string(),
    }
}

/// Build the extxyz comment line for `frame`. When `lattice`, `properties`
/// and `info` are all empty, the original `comment` is used verbatim --
/// this is what keeps a plain XYZ frame's comment line byte-identical
/// through the extxyz writer (atom rows are always re-emitted through the
/// generic species/pos formatter, so *those* are structurally, not
/// byte-for-byte, unchanged -- same non-goal as [`write_xyz`] already has
/// relative to hand-written input). Otherwise the comment line is rebuilt
/// canonically as `Lattice=... Properties=... key=value ...` (in that
/// order), which is not guaranteed to match a third-party file's original
/// key ordering.
fn build_comment_line(frame: &XyzFrame) -> String {
    if frame.lattice.is_none() && frame.properties.is_empty() && frame.info.is_empty() {
        return frame.comment.clone();
    }
    let mut parts = Vec::new();
    if let Some(l) = frame.lattice {
        let nums = l
            .iter()
            .map(|v| v.to_string())
            .collect::<Vec<_>>()
            .join(" ");
        parts.push(format!("Lattice=\"{nums}\""));
    }
    let mut props = String::from("species:S:1:pos:R:3");
    for p in &frame.properties {
        let kind_char = match p.kind {
            XyzPropertyKind::Real => 'R',
            XyzPropertyKind::Integer => 'I',
            XyzPropertyKind::String => 'S',
            XyzPropertyKind::Logical => 'L',
        };
        props.push_str(&format!(":{}:{}:{}", p.name, kind_char, p.count));
    }
    parts.push(format!("Properties={props}"));
    for (k, v) in &frame.info {
        if v.is_empty() || v.chars().any(char::is_whitespace) || v.contains('"') {
            // Escape '"' and '\' so the quoted value reparses back to
            // exactly `v` -- see `tokenize_info_line`'s matching escape
            // handling, both modeled on ASE's own `key_val_str_to_dict`.
            let escaped: String = v
                .chars()
                .flat_map(|c| match c {
                    '"' => vec!['\\', '"'],
                    '\\' => vec!['\\', '\\'],
                    other => vec![other],
                })
                .collect();
            parts.push(format!("{k}=\"{escaped}\""));
        } else {
            parts.push(format!("{k}={v}"));
        }
    }
    parts.join(" ")
}

/// Rejects an [`XyzFrame`] that [`write_extxyz`]/[`ExtxyzWriter::write_frame`]
/// cannot losslessly round-trip through extxyz `key=value` comment-line
/// syntax. Returns `Err(detail)` naming the first offending field. Checks:
/// - an [`XyzFrame::info`] key or a [`XyzProperty::name`] containing
///   whitespace, `:`, `=`, or `"` (all syntactically significant to the
///   tokenizer/column-spec grammar, and -- unlike values -- names/keys have
///   no quoting or escaping to fall back on);
/// - an info key literally `"Lattice"` or `"Properties"`, which
///   [`parse_one_frame_ext`] always special-cases regardless of whether it
///   came from [`XyzFrame::lattice`]/[`properties`](XyzFrame::properties) or
///   a generic info entry, so a generic entry with either name would
///   reparse as the *wrong* field (or fail as `InvalidLattice`/
///   `InvalidProperties` if its value isn't in that field's own syntax);
/// - an info value containing an embedded newline, which no amount of
///   quoting/escaping can represent inside a single comment line;
/// - a [`XyzProperty`] declaring `count == 0`, which `Properties=`' own
///   grammar (parsed by [`parse_properties`]) requires to be at least 1.
///
/// Info values containing `"` or `\` are otherwise fine: `build_comment_line`
/// escapes them the same way [`tokenize_info_line`] un-escapes them on read
/// (both modeled on ASE's own `key_val_str_to_dict`), so they are not
/// rejected here.
fn validate_extxyz_writable(frame: &XyzFrame) -> Result<(), String> {
    for (k, v) in &frame.info {
        if k.is_empty() || k.chars().any(|c| c.is_whitespace() || c == '=' || c == '"') {
            return Err(format!(
                "info key {k:?} cannot be written (must be non-empty and contain no whitespace, '=', or '\"')"
            ));
        }
        if k == "Lattice" || k == "Properties" {
            return Err(format!(
                "info key {k:?} is reserved by extxyz -- use `XyzFrame::lattice` or \
                 `XyzFrame::properties` instead of a generic info entry"
            ));
        }
        if v.contains('\n') || v.contains('\r') {
            return Err(format!(
                "info['{k}'] value {v:?} cannot be written (extxyz comment lines cannot \
                 contain an embedded newline)"
            ));
        }
    }
    for p in &frame.properties {
        if p.name.is_empty()
            || p.name
                .chars()
                .any(|c| c.is_whitespace() || c == ':' || c == '=' || c == '"')
        {
            return Err(format!(
                "property name {:?} cannot be written (must be non-empty and contain no whitespace, ':', '=', or '\"')",
                p.name
            ));
        }
        if p.count == 0 {
            return Err(format!(
                "property '{}' declares 0 components, which extxyz's Properties= grammar \
                 cannot represent (minimum is 1)",
                p.name
            ));
        }
    }
    Ok(())
}

/// Streaming writer for a (possibly multi-frame) extxyz file.
pub struct ExtxyzWriter<W: std::io::Write> {
    writer: W,
}

impl<W: std::io::Write> ExtxyzWriter<W> {
    pub fn new(writer: W) -> Self {
        Self { writer }
    }

    /// Write one frame. Call repeatedly for a multi-frame trajectory.
    ///
    /// Returns an [`std::io::Error`] of kind [`std::io::ErrorKind::InvalidData`]
    /// (not a sink failure) if `frame.info`/`frame.properties` contains a
    /// key/value/name that cannot be represented in extxyz syntax -- see
    /// [`validate_extxyz_writable`]. [`write_extxyz`] surfaces the same
    /// check as a typed [`XyzError`] instead.
    ///
    /// # Panics
    /// Panics if `frame.properties` is inconsistent with `frame.atoms`
    /// (a `values` row missing for some atom, or a row whose length
    /// doesn't match its column's declared `count`) -- this is a caller
    /// contract on hand-built `XyzFrame` values, not something that can
    /// happen from any of this module's own parsers.
    pub fn write_frame(&mut self, frame: &XyzFrame) -> std::io::Result<()> {
        if let Err(detail) = validate_extxyz_writable(frame) {
            return Err(std::io::Error::new(std::io::ErrorKind::InvalidData, detail));
        }
        writeln!(self.writer, "{}", frame.atoms.len())?;
        writeln!(self.writer, "{}", build_comment_line(frame))?;
        for (i, atom) in frame.atoms.iter().enumerate() {
            write!(
                self.writer,
                "{} {} {} {}",
                atom.element.symbol(),
                atom.x,
                atom.y,
                atom.z
            )?;
            for prop in &frame.properties {
                let values = &prop.values[i];
                debug_assert_eq!(
                    values.len(),
                    prop.count,
                    "XyzProperty '{}' declares count {} but atom {i} has {} value(s)",
                    prop.name,
                    prop.count,
                    values.len()
                );
                for v in values {
                    write!(self.writer, " {}", format_xyz_value(v))?;
                }
            }
            writeln!(self.writer)?;
        }
        Ok(())
    }
}

/// Write a single extxyz frame to a string.
///
/// Returns [`XyzError::UnwritableMetadata`] if `frame.info`/`frame.properties`
/// contains a key/value/name that cannot be represented in extxyz syntax --
/// see [`validate_extxyz_writable`]. A frame produced by [`parse_extxyz`]
/// can never trigger this (the parser's own tokenizer already rejects those
/// characters on read); it is reachable only from a hand-built `XyzFrame`,
/// e.g. via the Python/WASM `to_extxyz` bindings.
pub fn write_extxyz(frame: &XyzFrame) -> Result<String, XyzError> {
    let mut buf = Vec::new();
    ExtxyzWriter::new(&mut buf)
        .write_frame(frame)
        .map_err(|e| match e.kind() {
            std::io::ErrorKind::InvalidData => XyzError::UnwritableMetadata {
                detail: e.to_string(),
            },
            _ => unreachable!("writing to a Vec<u8> only fails with InvalidData (see write_frame)"),
        })?;
    Ok(String::from_utf8(buf).expect("ExtxyzWriter only emits ASCII/UTF-8 text"))
}

#[cfg(test)]
mod tests {
    use super::*;

    const WATER_XYZ: &str = "3\nwater\nO 0.00000000 0.00000000 0.00000000\nH 0.75860000 0.00000000 0.50428400\nH 0.75860000 0.00000000 -0.50428400\n";

    const METHANE_XYZ: &str = "5\nmethane, generated by chematic\nC 0.00000000 0.00000000 0.00000000\nH 0.62910000 0.62910000 0.62910000\nH -0.62910000 -0.62910000 0.62910000\nH -0.62910000 0.62910000 -0.62910000\nH 0.62910000 -0.62910000 -0.62910000\n";

    #[test]
    fn parse_water_fixture() {
        let frame = parse_xyz(WATER_XYZ).unwrap();
        assert_eq!(frame.comment, "water");
        assert_eq!(frame.atoms.len(), 3);
        assert_eq!(frame.atoms[0].element, Element::O);
        assert_eq!(frame.atoms[1].element, Element::H);
        assert_eq!(frame.atoms[2].element, Element::H);
        assert_eq!(frame.atoms[0].x, 0.0);
        assert_eq!(frame.atoms[1].x, 0.7586);
        assert_eq!(frame.atoms[2].z, -0.504284);

        let mol = frame.to_molecule();
        assert_eq!(mol.atom_count(), 3);
        assert_eq!(mol.atom(chematic_core::AtomIdx(0)).element, Element::O);
        assert_eq!(mol.atom(chematic_core::AtomIdx(1)).element, Element::H);
        assert_eq!(mol.atom(chematic_core::AtomIdx(2)).element, Element::H);
        assert_eq!(mol.bond_count(), 0);

        let coords = frame.coords();
        assert_eq!(coords.len(), 3);
        assert_eq!(coords[0], (0.0, 0.0, 0.0));
    }

    #[test]
    fn parse_methane_fixture() {
        let frame = parse_xyz(METHANE_XYZ).unwrap();
        assert_eq!(frame.atoms.len(), 5);
        assert_eq!(frame.atoms[0].element, Element::C);
        for atom in &frame.atoms[1..] {
            assert_eq!(atom.element, Element::H);
        }
        let mol = frame.to_molecule();
        assert_eq!(mol.atom_count(), 5);
        assert_eq!(mol.bond_count(), 0);
    }

    #[test]
    fn roundtrip_parse_write_parse() {
        let frame = parse_xyz(WATER_XYZ).unwrap();
        let written = write_xyz(&frame);
        let reparsed = parse_xyz(&written).unwrap();
        assert_eq!(frame, reparsed);
    }

    #[test]
    fn roundtrip_methane() {
        let frame = parse_xyz(METHANE_XYZ).unwrap();
        let written = write_xyz(&frame);
        let reparsed = parse_xyz(&written).unwrap();
        assert_eq!(frame, reparsed);
    }

    #[test]
    fn multi_frame_parsing() {
        let traj = format!("{WATER_XYZ}{METHANE_XYZ}{WATER_XYZ}");
        let frames = parse_xyz_all(&traj).unwrap();
        assert_eq!(frames.len(), 3);
        assert_eq!(frames[0].atoms.len(), 3);
        assert_eq!(frames[1].atoms.len(), 5);
        assert_eq!(frames[2].atoms.len(), 3);
        assert_eq!(frames[0], frames[2]);
    }

    #[test]
    fn multi_frame_reader_matches_parse_xyz_all() {
        let traj = format!("{WATER_XYZ}{METHANE_XYZ}");
        let via_reader: Vec<XyzFrame> = XyzReader::new(&traj).collect::<Result<_, _>>().unwrap();
        let via_all = parse_xyz_all(&traj).unwrap();
        assert_eq!(via_reader, via_all);
    }

    #[test]
    fn xyz_writer_multi_frame_roundtrips() {
        let f1 = parse_xyz(WATER_XYZ).unwrap();
        let f2 = parse_xyz(METHANE_XYZ).unwrap();
        let mut buf: Vec<u8> = Vec::new();
        {
            let mut w = XyzWriter::new(&mut buf);
            w.write_frame(&f1).unwrap();
            w.write_frame(&f2).unwrap();
        }
        let text = String::from_utf8(buf).unwrap();
        let frames = parse_xyz_all(&text).unwrap();
        assert_eq!(frames, vec![f1, f2]);
    }

    #[test]
    fn fails_closed_on_atom_count_mismatch() {
        let bad = "4\nwater with wrong count\nO 0.0 0.0 0.0\nH 0.0 0.0 1.0\nH 0.0 0.0 -1.0\n";
        let err = parse_xyz(bad).unwrap_err();
        assert_eq!(
            err,
            XyzError::AtomCountMismatch {
                declared: 4,
                found: 3
            }
        );
    }

    #[test]
    fn fails_closed_on_atom_count_mismatch_zero_rows() {
        let bad = "5\nno atom rows at all\n";
        let err = parse_xyz(bad).unwrap_err();
        assert_eq!(
            err,
            XyzError::AtomCountMismatch {
                declared: 5,
                found: 0
            }
        );
    }

    #[test]
    fn zero_atom_frame_is_legal() {
        let s = "0\nempty frame\n";
        let frame = parse_xyz(s).unwrap();
        assert!(frame.atoms.is_empty());
        assert_eq!(frame.comment, "empty frame");
        assert_eq!(frame.to_molecule().atom_count(), 0);
    }

    #[test]
    fn multi_frame_survives_crlf_and_missing_final_newline() {
        // Middle frame uses CRLF line endings; the whole trajectory has no
        // trailing newline after the last atom row. Both boundary cases
        // that could desync a naive two-pass line scanner.
        let traj = "1\nlf frame\nH 0.0 0.0 0.0\n\
                     2\r\ncrlf frame\r\nO 0.0 0.0 0.0\r\nH 1.0 0.0 0.0\r\n\
                     0\nempty frame\n\
                     1\nno trailing newline\nC 1.0 2.0 3.0";
        let frames = parse_xyz_all(traj).unwrap();
        assert_eq!(frames.len(), 4);
        assert_eq!(frames[0].atoms.len(), 1);
        assert_eq!(frames[1].atoms.len(), 2);
        assert_eq!(frames[1].comment, "crlf frame");
        assert!(frames[2].atoms.is_empty());
        assert_eq!(frames[3].atoms.len(), 1);
        assert_eq!(frames[3].atoms[0].element, Element::C);
        assert_eq!(frames[3].atoms[0].z, 3.0);
    }

    #[test]
    fn fails_closed_on_non_finite_coordinate() {
        let bad = "1\nbad\nH 0.0 0.0 nan\n";
        let err = parse_xyz(bad).unwrap_err();
        assert!(matches!(
            err,
            XyzError::InvalidAtomLine { .. } | XyzError::NonFiniteCoordinate { .. }
        ));

        let bad_inf = "1\nbad\nH 0.0 0.0 inf\n";
        let err = parse_xyz(bad_inf).unwrap_err();
        assert!(matches!(err, XyzError::NonFiniteCoordinate { .. }));
    }

    #[test]
    fn fails_closed_on_unknown_element() {
        let bad = "1\nbad element\nXx 0.0 0.0 0.0\n";
        let err = parse_xyz(bad).unwrap_err();
        assert_eq!(
            err,
            XyzError::UnknownElement {
                symbol: "Xx".to_string(),
                line: 3,
            }
        );
    }

    #[test]
    fn parse_xyz_ignores_trailing_frames() {
        let traj = format!("{WATER_XYZ}{METHANE_XYZ}");
        let frame = parse_xyz(&traj).unwrap();
        assert_eq!(frame.atoms.len(), 3);
    }

    #[test]
    fn empty_comment_line_is_preserved() {
        let s = "1\n\nC 0.0 0.0 0.0\n";
        let frame = parse_xyz(s).unwrap();
        assert_eq!(frame.comment, "");
    }

    // ---- Extended XYZ (extxyz) ----

    const EXTXYZ_WATER: &str = "3\nLattice=\"10.0 0.0 0.0 0.0 10.0 0.0 0.0 0.0 10.0\" Properties=species:S:1:pos:R:3:forces:R:3:tag:I:1 energy=-76.4 pbc=\"T T T\"\nO 0.0 0.0 0.0 0.1 0.0 0.0 1\nH 0.75860000 0.0 0.50428400 0.0 0.1 0.0 2\nH 0.75860000 0.0 -0.50428400 0.0 -0.1 0.0 2\n";

    #[test]
    fn parses_lattice_properties_and_info() {
        let frame = parse_extxyz(EXTXYZ_WATER).unwrap();
        assert_eq!(frame.atoms.len(), 3);
        assert_eq!(
            frame.lattice,
            Some([10.0, 0.0, 0.0, 0.0, 10.0, 0.0, 0.0, 0.0, 10.0])
        );
        // Only Lattice/Properties are special-cased -- pbc lands in info too.
        assert_eq!(
            frame.info,
            vec![
                ("energy".to_string(), "-76.4".to_string()),
                ("pbc".to_string(), "T T T".to_string()),
            ]
        );
        assert_eq!(frame.properties.len(), 2);
        assert_eq!(frame.properties[0].name, "forces");
        assert_eq!(frame.properties[0].kind, XyzPropertyKind::Real);
        assert_eq!(frame.properties[0].count, 3);
        assert_eq!(
            frame.properties[0].values[0],
            vec![
                XyzValue::Real(0.1),
                XyzValue::Real(0.0),
                XyzValue::Real(0.0)
            ]
        );
        assert_eq!(frame.properties[1].name, "tag");
        assert_eq!(frame.properties[1].kind, XyzPropertyKind::Integer);
        assert_eq!(frame.properties[1].values[0], vec![XyzValue::Integer(1)]);
        assert_eq!(frame.properties[1].values[1], vec![XyzValue::Integer(2)]);
    }

    #[test]
    fn extxyz_roundtrip_preserves_lattice_properties_and_info() {
        let frame = parse_extxyz(EXTXYZ_WATER).unwrap();
        let written = write_extxyz(&frame).unwrap();
        let reparsed = parse_extxyz(&written).unwrap();
        assert_eq!(frame.atoms, reparsed.atoms);
        assert_eq!(frame.lattice, reparsed.lattice);
        assert_eq!(frame.properties, reparsed.properties);
        assert_eq!(frame.info, reparsed.info);
    }

    #[test]
    fn plain_xyz_roundtrips_unchanged_through_extxyz_path() {
        // A free-form comment (no '=') must parse as an ordinary comment,
        // not extxyz metadata, and the *comment line* the writer emits must
        // be byte-identical to the original (no Lattice/Properties/info to
        // reconstruct). Atom rows are always re-emitted through the
        // generic species/pos writer, so they are structurally -- not
        // byte-for-byte -- equal (same as write_xyz's own non-goal).
        let frame = parse_extxyz(WATER_XYZ).unwrap();
        assert_eq!(frame.comment, "water");
        assert_eq!(frame.lattice, None);
        assert!(frame.properties.is_empty());
        assert!(frame.info.is_empty());

        let written = write_extxyz(&frame).unwrap();
        assert_eq!(written.lines().nth(1), Some("water"));

        let reparsed = parse_extxyz(&written).unwrap();
        assert_eq!(frame.atoms, reparsed.atoms);
        assert_eq!(frame.comment, reparsed.comment);
    }

    #[test]
    fn extxyz_defaults_properties_to_species_pos_when_absent() {
        // Info keys present, but no explicit Properties= -- must still
        // default to species:S:1:pos:R:3 (plain 'element x y z' rows).
        let s = "1\nenergy=-1.0\nC 0.0 0.0 0.0\n";
        let frame = parse_extxyz(s).unwrap();
        assert!(frame.properties.is_empty());
        assert_eq!(frame.info, vec![("energy".to_string(), "-1.0".to_string())]);
        assert_eq!(frame.atoms[0].element, Element::C);
    }

    #[test]
    fn extxyz_multi_frame_reader_matches_parse_extxyz_all() {
        let traj = format!("{EXTXYZ_WATER}{WATER_XYZ}");
        let via_reader: Vec<XyzFrame> = ExtxyzReader::new(&traj).collect::<Result<_, _>>().unwrap();
        let via_all = parse_extxyz_all(&traj).unwrap();
        assert_eq!(via_reader, via_all);
        assert_eq!(via_reader.len(), 2);
    }

    #[test]
    fn fails_closed_on_invalid_lattice_count() {
        let bad = "1\nLattice=\"1.0 2.0 3.0\"\nC 0.0 0.0 0.0\n";
        let err = parse_extxyz(bad).unwrap_err();
        assert!(matches!(err, XyzError::InvalidLattice { .. }));
    }

    #[test]
    fn fails_closed_on_properties_not_starting_with_species_pos() {
        let bad = "1\nProperties=pos:R:3:species:S:1\n0.0 0.0 0.0 C\n";
        let err = parse_extxyz(bad).unwrap_err();
        assert!(matches!(err, XyzError::InvalidProperties { .. }));
    }

    #[test]
    fn fails_closed_on_unterminated_quote() {
        let bad = "1\nLattice=\"1.0 2.0 3.0\nC 0.0 0.0 0.0\n";
        let err = parse_extxyz(bad).unwrap_err();
        assert!(matches!(err, XyzError::UnterminatedQuote { .. }));
    }

    #[test]
    fn fails_closed_on_duplicate_info_key() {
        let bad = "1\nenergy=1.0 energy=2.0\nC 0.0 0.0 0.0\n";
        let err = parse_extxyz(bad).unwrap_err();
        assert_eq!(
            err,
            XyzError::DuplicateInfoKey {
                line: 2,
                key: "energy".to_string()
            }
        );
    }

    #[test]
    fn bare_info_key_defaults_to_true_flag() {
        // A bare key with no '=value' (here, trailing 'bogus' after
        // 'energy=1.0' already committed the line to key=value parsing) is
        // an implicit boolean flag defaulting to "T", matching ASE's own
        // `key_val_str_to_dict` ("len(kv_pair) == 1: default to True").
        let s = "1\nenergy=1.0 bogus\nC 0.0 0.0 0.0\n";
        let frame = parse_extxyz(s).unwrap();
        assert_eq!(
            frame.info,
            vec![
                ("energy".to_string(), "1.0".to_string()),
                ("bogus".to_string(), "T".to_string()),
            ]
        );
    }

    #[test]
    fn fails_closed_on_property_column_mismatch() {
        // Properties declares an extra 'charge:R:1' column, but the atom
        // row only has 'element x y z'.
        let bad = "1\nProperties=species:S:1:pos:R:3:charge:R:1\nC 0.0 0.0 0.0\n";
        let err = parse_extxyz(bad).unwrap_err();
        assert_eq!(
            err,
            XyzError::PropertyColumnMismatch {
                line: 3,
                expected: 5,
                found: 4,
            }
        );
    }

    #[test]
    fn fails_closed_on_non_finite_property_value() {
        let bad = "1\nProperties=species:S:1:pos:R:3:charge:R:1\nC 0.0 0.0 0.0 nan\n";
        let err = parse_extxyz(bad).unwrap_err();
        assert!(matches!(err, XyzError::InvalidPropertyValue { .. }));
    }

    #[test]
    fn fails_closed_on_invalid_logical_value() {
        let bad = "1\nProperties=species:S:1:pos:R:3:flag:L:1\nC 0.0 0.0 0.0 maybe\n";
        let err = parse_extxyz(bad).unwrap_err();
        assert!(matches!(err, XyzError::InvalidPropertyValue { .. }));
    }

    #[test]
    fn parses_logical_property_values() {
        let s = "1\nProperties=species:S:1:pos:R:3:flag:L:1\nC 0.0 0.0 0.0 T\n";
        let frame = parse_extxyz(s).unwrap();
        assert_eq!(frame.properties[0].values[0], vec![XyzValue::Logical(true)]);
    }

    #[test]
    fn extxyz_zero_atom_frame_is_legal() {
        let s = "0\nempty extxyz frame\n";
        let frame = parse_extxyz(s).unwrap();
        assert!(frame.atoms.is_empty());
        assert_eq!(write_extxyz(&frame).unwrap(), s);
    }

    #[test]
    fn write_extxyz_escapes_and_round_trips_quote_and_backslash_in_info_value() {
        // Previously rejected outright; now escaped on write and
        // un-escaped on read, matching ASE's own `key_val_str_to_dict`
        // char-by-char escape handling.
        let frame = XyzFrame {
            atoms: vec![XyzAtom {
                element: Element::C,
                x: 0.0,
                y: 0.0,
                z: 0.0,
            }],
            comment: String::new(),
            lattice: None,
            properties: Vec::new(),
            info: vec![(
                "note".to_string(),
                "x\" y=\"z and a \\backslash".to_string(),
            )],
        };
        let written = write_extxyz(&frame).unwrap();
        let reparsed = parse_extxyz(&written).unwrap();
        assert_eq!(reparsed.info, frame.info);
    }

    #[test]
    fn write_extxyz_rejects_info_key_colliding_with_lattice_or_properties() {
        // "Lattice"/"Properties" are always special-cased on read
        // (`parse_one_frame_ext`) regardless of which field wrote them, so
        // a generic info entry using either name would silently reparse as
        // the wrong field rather than as itself.
        for reserved in ["Lattice", "Properties"] {
            let frame = XyzFrame {
                atoms: vec![XyzAtom {
                    element: Element::C,
                    x: 0.0,
                    y: 0.0,
                    z: 0.0,
                }],
                comment: String::new(),
                lattice: None,
                properties: Vec::new(),
                info: vec![(reserved.to_string(), "1.0".to_string())],
            };
            let err = write_extxyz(&frame).unwrap_err();
            assert!(
                matches!(err, XyzError::UnwritableMetadata { .. }),
                "reserved key '{reserved}' must be rejected, not silently misparsed on reread"
            );
        }
    }

    #[test]
    fn write_extxyz_rejects_embedded_newline_in_info_value() {
        let frame = XyzFrame {
            atoms: vec![XyzAtom {
                element: Element::C,
                x: 0.0,
                y: 0.0,
                z: 0.0,
            }],
            comment: String::new(),
            lattice: None,
            properties: Vec::new(),
            info: vec![("note".to_string(), "line1\nline2".to_string())],
        };
        let err = write_extxyz(&frame).unwrap_err();
        assert!(matches!(err, XyzError::UnwritableMetadata { .. }));
    }

    #[test]
    fn write_extxyz_rejects_zero_count_property() {
        let frame = XyzFrame {
            atoms: Vec::new(),
            comment: String::new(),
            lattice: None,
            properties: vec![XyzProperty {
                name: "forces".to_string(),
                kind: XyzPropertyKind::Real,
                count: 0,
                values: Vec::new(),
            }],
            info: Vec::new(),
        };
        let err = write_extxyz(&frame).unwrap_err();
        assert!(matches!(err, XyzError::UnwritableMetadata { .. }));
    }

    #[test]
    fn fails_closed_on_empty_info_key() {
        let bad = "1\n=1.0\nC 0.0 0.0 0.0\n";
        let err = parse_extxyz(bad).unwrap_err();
        assert!(matches!(err, XyzError::InvalidInfoField { .. }));
    }

    #[test]
    fn write_extxyz_rejects_colon_in_property_name() {
        let frame = XyzFrame {
            atoms: vec![XyzAtom {
                element: Element::C,
                x: 0.0,
                y: 0.0,
                z: 0.0,
            }],
            comment: String::new(),
            lattice: None,
            properties: vec![XyzProperty {
                name: "bad:name".to_string(),
                kind: XyzPropertyKind::Real,
                count: 1,
                values: vec![vec![XyzValue::Real(1.0)]],
            }],
            info: Vec::new(),
        };
        let err = write_extxyz(&frame).unwrap_err();
        assert!(matches!(err, XyzError::UnwritableMetadata { .. }));
    }

    #[test]
    fn write_extxyz_accepts_info_value_with_whitespace_but_no_quote() {
        // The exact case that motivated the '"'-rejection check: a value
        // needing quotes (has whitespace) but free of the one character
        // that would corrupt the quoting itself.
        let frame = XyzFrame {
            atoms: vec![XyzAtom {
                element: Element::C,
                x: 0.0,
                y: 0.0,
                z: 0.0,
            }],
            comment: String::new(),
            lattice: None,
            properties: Vec::new(),
            info: vec![("note".to_string(), "hello world".to_string())],
        };
        let written = write_extxyz(&frame).unwrap();
        let reparsed = parse_extxyz(&written).unwrap();
        assert_eq!(reparsed.info, frame.info);
    }

    #[test]
    fn xyz_parse_limits_reject_input_atoms_lines_and_frames() {
        let limits = XyzParseLimits {
            max_input_bytes: 2,
            ..XyzParseLimits::default()
        };
        assert!(matches!(
            parse_xyz_with_limits(WATER_XYZ, &limits),
            Err(XyzError::ResourceLimit {
                resource: "input bytes",
                ..
            })
        ));

        let limits = XyzParseLimits {
            max_atoms_per_frame: 1,
            ..XyzParseLimits::default()
        };
        assert!(matches!(
            parse_xyz_with_limits(WATER_XYZ, &limits),
            Err(XyzError::ResourceLimit {
                resource: "atoms per frame",
                ..
            })
        ));

        let limits = XyzParseLimits {
            max_line_bytes: 2,
            ..XyzParseLimits::default()
        };
        assert!(matches!(
            parse_extxyz_with_limits(WATER_XYZ, &limits),
            Err(XyzError::ResourceLimit {
                resource: "line bytes",
                ..
            })
        ));

        let limits = XyzParseLimits {
            max_frames: 1,
            ..XyzParseLimits::default()
        };
        let trajectory = format!("{WATER_XYZ}{WATER_XYZ}");
        assert!(matches!(
            parse_xyz_all_with_limits(&trajectory, &limits),
            Err(XyzError::ResourceLimit {
                resource: "frames",
                ..
            })
        ));
    }
}
