#!/usr/bin/env python3
"""Wave 1 ("RDKit alternative" program): aggregate the pipeline v2 vs RDKit
ETKDGv3 benchmark's two independently-generated JSONL dumps into a single
aggregate JSON + Markdown report.

Reads (never writes) the chematic dump
(`validation/results/pipeline_v2_vs_rdkit_chematic_rows.jsonl`) and the RDKit
oracle (`validation/results/pipeline_v2_vs_rdkit_rdkit_rows.jsonl`) -- both
already independently generated by reading the same corpus manifests, never
one feeding the other. This script only cross-references them for atom-
mapping verification and side-by-side reporting; it never re-runs either
engine.

No row is silently dropped: every (tier, name, arm) row from both inputs is
counted into exactly one of the required classification buckets, and the
per-bucket counts are printed so a missing row is visible as a shortfall in
`molecule_count * arm_count`, not a silent gap.

Run: `.venv/bin/python scripts/gen_pipeline_v2_vs_rdkit_report.py`
Writes:
  - validation/results/pipeline_v2_vs_rdkit_aggregate.json
  - docs/pipeline_v2_vs_rdkit_etkdgv3_benchmark.md
"""

import hashlib
import json
import statistics
import subprocess
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).parent.parent

CHEMATIC_ROWS_PATH = ROOT / "validation/results/pipeline_v2_vs_rdkit_chematic_rows.jsonl"
RDKIT_ROWS_PATH = ROOT / "validation/results/pipeline_v2_vs_rdkit_rdkit_rows.jsonl"
TIER_A_MANIFEST = ROOT / "validation/manifests/pipeline_v2_vs_rdkit_etkdgv3_tier_a.json"
TIER_B_MANIFEST = ROOT / "validation/manifests/pipeline_v2_vs_rdkit_etkdgv3_tier_b.json"
AGGREGATE_OUT = ROOT / "validation/results/pipeline_v2_vs_rdkit_aggregate.json"
REPORT_OUT = ROOT / "docs/pipeline_v2_vs_rdkit_etkdgv3_benchmark.md"

CHEMATIC_ARMS = [
    "chematic_pipeline_v2_no_ff",
    "chematic_pipeline_v2_dreiding",
    "chematic_pipeline_v2_uff_only",
    "chematic_pipeline_v2_mmff94_strict",
    "chematic_pipeline_v2_mmff94_with_uff_fallback",
    "chematic_legacy_etkdg",
]
RDKIT_ARMS = [
    "rdkit_etkdgv3_raw",
    "rdkit_etkdgv3_uff",
    "rdkit_etkdgv3_mmff94",
    "rdkit_etkdgv3_best_of_n",
]

# Cause substrings -> classification bucket. Checked in order; first match wins.
CHEMATIC_CAUSE_BUCKETS = [
    ("RingTorsionApplicationUnsupported", "unsupported_chemistry"),
    ("MissingParameters", "unsupported_chemistry"),
]
RDKIT_CAUSE_BUCKETS = [
    ("EmbedMolecule_failed", "oracle_failure"),
    ("EmbedMultipleConfs_failed", "oracle_failure"),
    ("all_conformers_failed_uff_optimization", "oracle_failure"),
    ("MMFF_parameters_unavailable", "unsupported_chemistry"),
]


def load_jsonl(path):
    rows = []
    with open(path) as f:
        for line in f:
            line = line.strip()
            if line:
                rows.append(json.loads(line))
    return rows


def classify_row(row, cause_buckets):
    status = row.get("status")
    if status == "success":
        return "success"
    if status == "timeout":
        return "timeout"
    if status == "parse_failure":
        return "parse_failure"
    if status == "internal_error":
        return "internal_error"
    if status == "typed_failure":
        cause = row.get("failure_cause", "")
        for substr, bucket in cause_buckets:
            if substr in cause:
                return bucket
        return "typed_failure"
    return "unclassified"  # should never happen; surfaced explicitly if it does


def percentile(values, p):
    if not values:
        return None
    values = sorted(values)
    k = (len(values) - 1) * p
    f = int(k)
    c = min(f + 1, len(values) - 1)
    if f == c:
        return values[f]
    return values[f] + (values[c] - values[f]) * (k - f)


def summarize_timing(rows):
    elapsed = [r["elapsed_ms"] for r in rows if "elapsed_ms" in r]
    if not elapsed:
        return None
    return {
        "n": len(elapsed),
        "p50": percentile(elapsed, 0.50),
        "p95": percentile(elapsed, 0.95),
        "p99": percentile(elapsed, 0.99),
        "max": max(elapsed),
        "methodology": "in-process wall-clock per call, NOT process-isolated; "
        "see report's Performance Methodology section",
    }


def main():
    chematic_rows = load_jsonl(CHEMATIC_ROWS_PATH)
    rdkit_rows = load_jsonl(RDKIT_ROWS_PATH)

    with open(TIER_A_MANIFEST) as f:
        tier_a = json.load(f)
    with open(TIER_B_MANIFEST) as f:
        tier_b = json.load(f)

    molecule_categories = {}
    for tier_manifest, tier_label in [(tier_a, "A"), (tier_b, "B")]:
        for m in tier_manifest["molecules"]:
            molecule_categories[(tier_label, m["name"])] = m.get("primary_category", "unknown")

    total_molecules = len(tier_a["molecules"]) + len(tier_b["molecules"])

    # --- Classification ---
    for row in chematic_rows:
        row["_bucket"] = classify_row(row, CHEMATIC_CAUSE_BUCKETS)
    for row in rdkit_rows:
        row["_bucket"] = classify_row(row, RDKIT_CAUSE_BUCKETS)

    unclassified = [r for r in chematic_rows + rdkit_rows if r["_bucket"] == "unclassified"]

    # --- Atom mapping verification (per molecule) ---
    chematic_elements_by_mol = {}
    for row in chematic_rows:
        key = (row["tier"], row["name"])
        if "heavy_atom_elements" in row and key not in chematic_elements_by_mol:
            chematic_elements_by_mol[key] = row["heavy_atom_elements"]
    rdkit_elements_by_mol = {}
    for row in rdkit_rows:
        key = (row["tier"], row["name"])
        if "heavy_atom_elements" in row and key not in rdkit_elements_by_mol:
            rdkit_elements_by_mol[key] = row["heavy_atom_elements"]

    atom_mapping_verified = {}
    atom_mapping_unavailable_molecules = []
    for key in set(chematic_elements_by_mol) | set(rdkit_elements_by_mol):
        c = chematic_elements_by_mol.get(key)
        r = rdkit_elements_by_mol.get(key)
        if c is None or r is None:
            atom_mapping_verified[key] = None  # can't check -- neither side had a successful/parsed row
            atom_mapping_unavailable_molecules.append({"tier": key[0], "name": key[1], "reason": "no_heavy_atom_data_on_one_side"})
            continue
        verified = c == r
        atom_mapping_verified[key] = verified
        if not verified:
            atom_mapping_unavailable_molecules.append(
                {"tier": key[0], "name": key[1], "reason": "element_sequence_mismatch", "chematic": c, "rdkit": r}
            )

    n_verified = sum(1 for v in atom_mapping_verified.values() if v is True)
    n_checked = sum(1 for v in atom_mapping_verified.values() if v is not None)

    # --- Coverage: per arm, per class ---
    def coverage_by_arm(rows, arms):
        out = {}
        for arm in arms:
            arm_rows = [r for r in rows if r["arm"] == arm]
            buckets = defaultdict(int)
            for r in arm_rows:
                buckets[r["_bucket"]] += 1
            out[arm] = {
                "n_rows": len(arm_rows),
                "buckets": dict(buckets),
            }
        return out

    chematic_coverage = coverage_by_arm(chematic_rows, CHEMATIC_ARMS)
    rdkit_coverage = coverage_by_arm(rdkit_rows, RDKIT_ARMS)

    def coverage_by_class_and_arm(rows, arms):
        out = {}
        for arm in arms:
            per_class = defaultdict(lambda: defaultdict(int))
            for r in rows:
                if r["arm"] != arm:
                    continue
                cat = molecule_categories.get((r["tier"], r["name"]), "unknown")
                per_class[cat][r["_bucket"]] += 1
            out[arm] = {cat: dict(b) for cat, b in per_class.items()}
        return out

    chematic_coverage_by_class = coverage_by_class_and_arm(chematic_rows, CHEMATIC_ARMS)
    rdkit_coverage_by_class = coverage_by_class_and_arm(rdkit_rows, RDKIT_ARMS)

    # --- Geometry validity (chematic: from FinalGeometryValidation; legacy arm: independent check) ---
    def geometry_summary(rows, arm):
        succ = [r for r in rows if r["arm"] == arm and r["_bucket"] == "success"]
        if not succ:
            return None
        finite_rate = sum(1 for r in succ if r.get("all_finite")) / len(succ)
        sound_rate = sum(1 for r in succ if r.get("sound")) / len(succ)
        bond15 = [r["bond_violation_rate_15pct"] for r in succ if "bond_violation_rate_15pct" in r]
        bond50 = [r["bond_violation_rate_50pct"] for r in succ if "bond_violation_rate_50pct" in r]
        clashes = [r["gross_clash_count"] for r in succ if "gross_clash_count" in r]
        return {
            "n_success": len(succ),
            "all_finite_rate": finite_rate,
            "sound_rate": sound_rate,
            "mean_bond_violation_rate_15pct": statistics.fmean(bond15) if bond15 else None,
            "mean_bond_violation_rate_50pct": statistics.fmean(bond50) if bond50 else None,
            "mean_gross_clash_count": statistics.fmean(clashes) if clashes else None,
            "molecules_with_any_clash": sum(1 for c in clashes if c > 0),
        }

    chematic_geometry = {arm: geometry_summary(chematic_rows, arm) for arm in CHEMATIC_ARMS}

    # --- Stereo (chematic only -- RDKit's own oracle doesn't report a directly comparable structure) ---
    def stereo_summary(rows, arm):
        succ = [r for r in rows if r["arm"] == arm and r["_bucket"] == "success" and r.get("stereo_before_declared", 0) > 0]
        if not succ:
            return None
        return {
            "n_molecules_with_declared_stereo": len(succ),
            "mean_declared": statistics.fmean(r["stereo_before_declared"] for r in succ),
            "mean_final_satisfied": statistics.fmean(r["final_stereo_satisfied"] for r in succ),
            "mean_final_violations": statistics.fmean(r["final_stereo_violations"] for r in succ),
            "mean_final_unevaluable": statistics.fmean(r["final_stereo_unevaluable"] for r in succ),
            "total_repaired": sum(r.get("stereo_repaired_count", 0) for r in succ),
            "total_repair_failed": sum(r.get("stereo_repair_failed_count", 0) for r in succ),
        }

    chematic_stereo = {arm: stereo_summary(chematic_rows, arm) for arm in CHEMATIC_ARMS}

    # --- Force-field coverage (chematic) ---
    def ff_summary(rows, arm):
        succ = [r for r in rows if r["arm"] == arm and r["_bucket"] == "success"]
        if not succ:
            return None
        fallback = sum(1 for r in succ if r.get("force_field_fallback"))
        converged = sum(1 for r in succ if r.get("force_field_converged"))
        return {
            "n_success": len(succ),
            "fallback_rate": fallback / len(succ),
            "converged_rate": converged / len(succ),
        }

    chematic_ff = {
        arm: ff_summary(chematic_rows, arm)
        for arm in ["chematic_pipeline_v2_mmff94_with_uff_fallback", "chematic_pipeline_v2_mmff94_strict"]
    }

    # --- Performance ---
    chematic_timing = {arm: summarize_timing([r for r in chematic_rows if r["arm"] == arm]) for arm in CHEMATIC_ARMS}
    rdkit_timing = {arm: summarize_timing([r for r in rdkit_rows if r["arm"] == arm]) for arm in RDKIT_ARMS}

    # --- Ring-torsion fail-closed probe ---
    probe_rows = [r for r in chematic_rows if r["arm"] == "chematic_pipeline_v2_ring_torsion_failclosed_probe"]

    # --- Reference geometry subset: no external reference conformers available ---
    reference_geometry_subset = {
        "n_molecules_with_reference_geometry": 0,
        "status": "insufficient_evidence",
        "note": "No experimentally-determined reference conformers were available "
        "for this benchmark round. RMSD-vs-reference, best-of-N RMSD, torsion "
        "fingerprint deviation, and duplicate-conformer-rate metrics are NOT "
        "computed here -- reported as insufficient evidence, not fabricated "
        "against a synthetic or absent reference.",
    }

    def sha256_file(path):
        return hashlib.sha256(Path(path).read_bytes()).hexdigest()

    aggregate = {
        "baseline": {
            "note": "Freshly generated this run against the SHAs/config below -- "
            "not carried over from any prior/historical benchmark run.",
        },
        "corpus": {
            "tier_a_count": len(tier_a["molecules"]),
            "tier_b_count": len(tier_b["molecules"]),
            "total_count": total_molecules,
            "tier_a_sha256": tier_a.get("corpus_sha256"),
            "tier_b_sha256": tier_b.get("corpus_sha256"),
        },
        "atom_mapping": {
            "n_checked": n_checked,
            "n_verified": n_verified,
            "n_unavailable": len(atom_mapping_unavailable_molecules),
            "unavailable_molecules": atom_mapping_unavailable_molecules,
        },
        "unclassified_row_count": len(unclassified),
        "unclassified_rows_sample": unclassified[:10],
        "coverage": {
            "chematic": chematic_coverage,
            "rdkit": rdkit_coverage,
        },
        "coverage_by_class": {
            "chematic": chematic_coverage_by_class,
            "rdkit": rdkit_coverage_by_class,
        },
        "geometry_validity": {"chematic": chematic_geometry},
        "stereo": {"chematic": chematic_stereo},
        "force_field_coverage": {"chematic": chematic_ff},
        "performance": {
            "chematic": chematic_timing,
            "rdkit": rdkit_timing,
            "methodology_note": "In-process wall-clock timing per (molecule, arm) "
            "call within a single long-running process -- NOT separate-process-"
            "isolated. p50/p95/p99/max reported per arm; process-level variance "
            "(repeated whole-process runs) was NOT measured this round.",
        },
        "ring_torsion_failclosed_probe": {
            "n_rows": len(probe_rows),
            "rows": probe_rows,
        },
        "reference_geometry_subset": reference_geometry_subset,
        "generated_by": [
            "scripts/gen_pipeline_v2_vs_rdkit_tier_a_manifest.py",
            "scripts/gen_pipeline_v2_vs_rdkit_tier_b_manifest.py",
            "crates/chematic-3d/examples/pipeline_v2_vs_rdkit_dump.rs",
            "scripts/pipeline_v2_vs_rdkit_oracle.py",
            "scripts/gen_pipeline_v2_vs_rdkit_report.py",
        ],
        "input_file_hashes": {
            "chematic_rows_sha256": sha256_file(CHEMATIC_ROWS_PATH),
            "rdkit_rows_sha256": sha256_file(RDKIT_ROWS_PATH),
            "tier_a_manifest_sha256": sha256_file(TIER_A_MANIFEST),
            "tier_b_manifest_sha256": sha256_file(TIER_B_MANIFEST),
        },
    }

    AGGREGATE_OUT.write_text(json.dumps(aggregate, indent=2, default=str) + "\n")

    write_markdown_report(aggregate, tier_a, tier_b)

    print(f"Wrote {AGGREGATE_OUT.relative_to(ROOT)}")
    print(f"Wrote {REPORT_OUT.relative_to(ROOT)}")
    if unclassified:
        print(f"WARNING: {len(unclassified)} rows were unclassified -- see aggregate JSON", file=sys.stderr)


def fmt_pct(x):
    return f"{x * 100:.1f}%" if x is not None else "n/a"


def fmt_num(x, digits=3):
    return f"{x:.{digits}f}" if x is not None else "n/a"


def write_markdown_report(agg, tier_a, tier_b):
    lines = []
    lines.append("# pipeline v2 vs RDKit ETKDGv3 — Wave 1 independent 3D benchmark")
    lines.append("")
    lines.append(
        "Measurement-only. No pipeline v2 or force-field algorithm code was "
        "changed to produce these numbers. Historical numbers (e.g. a "
        "previously-cited 25.9% geometrically-valid rate) are NOT reused here "
        "-- everything below was regenerated fresh against this repo's current "
        "`main` in this session."
    )
    lines.append("")
    lines.append("## Corpus")
    lines.append("")
    lines.append(f"- Tier A (curated stress): {agg['corpus']['tier_a_count']} molecules, sha256 `{agg['corpus']['tier_a_sha256'][:16]}...`")
    lines.append(f"- Tier B (fixed drug-like, ChEMBL-derived): {agg['corpus']['tier_b_count']} molecules, sha256 `{agg['corpus']['tier_b_sha256'][:16]}...`")
    lines.append(f"- Total: {agg['corpus']['total_count']} molecules")
    lines.append("")
    lines.append("## Atom mapping")
    lines.append("")
    lines.append(
        f"- Checked (both engines produced a heavy-atom element sequence): {agg['atom_mapping']['n_checked']}"
    )
    lines.append(f"- Verified matching (per-index element-symbol equality): {agg['atom_mapping']['n_verified']}")
    lines.append(f"- Unavailable/mismatched: {agg['atom_mapping']['n_unavailable']}")
    if agg["atom_mapping"]["n_unavailable"]:
        lines.append("")
        lines.append("Unavailable/mismatched molecules (never silently dropped):")
        for m in agg["atom_mapping"]["unavailable_molecules"][:20]:
            lines.append(f"- {m['tier']}/{m['name']}: {m['reason']}")
    lines.append("")
    lines.append("## Coverage — chematic (6 arms)")
    lines.append("")
    lines.append("| Arm | n | success | typed_failure | unsupported_chemistry | timeout | internal_error |")
    lines.append("|---|---|---|---|---|---|---|")
    for arm, data in agg["coverage"]["chematic"].items():
        b = data["buckets"]
        lines.append(
            f"| {arm} | {data['n_rows']} | {b.get('success', 0)} | {b.get('typed_failure', 0)} | "
            f"{b.get('unsupported_chemistry', 0)} | {b.get('timeout', 0)} | {b.get('internal_error', 0)} |"
        )
    lines.append("")
    lines.append("## Coverage — RDKit ETKDGv3 (4 arms)")
    lines.append("")
    lines.append("| Arm | n | success | oracle_failure | unsupported_chemistry | internal_error |")
    lines.append("|---|---|---|---|---|---|")
    for arm, data in agg["coverage"]["rdkit"].items():
        b = data["buckets"]
        lines.append(
            f"| {arm} | {data['n_rows']} | {b.get('success', 0)} | {b.get('oracle_failure', 0)} | "
            f"{b.get('unsupported_chemistry', 0)} | {b.get('internal_error', 0)} |"
        )
    lines.append("")
    lines.append("## Geometry validity (chematic)")
    lines.append("")
    lines.append("Independent per-engine measurement -- not a cross-engine RMSD (no reference geometry available, see below).")
    lines.append("")
    lines.append("| Arm | n success | all finite | sound | mean bond-viol >15% | mean bond-viol >50% | mean clashes | molecules w/ clash |")
    lines.append("|---|---|---|---|---|---|---|---|")
    for arm, g in agg["geometry_validity"]["chematic"].items():
        if g is None:
            lines.append(f"| {arm} | 0 | n/a | n/a | n/a | n/a | n/a | n/a |")
            continue
        lines.append(
            f"| {arm} | {g['n_success']} | {fmt_pct(g['all_finite_rate'])} | {fmt_pct(g['sound_rate'])} | "
            f"{fmt_pct(g['mean_bond_violation_rate_15pct'])} | {fmt_pct(g['mean_bond_violation_rate_50pct'])} | "
            f"{fmt_num(g['mean_gross_clash_count'], 2)} | {g['molecules_with_any_clash']} |"
        )
    lines.append("")
    lines.append("## Stereo (chematic, molecules with declared stereo only)")
    lines.append("")
    lines.append("| Arm | n w/ declared stereo | mean declared | mean satisfied | mean violations | mean unevaluable | total repaired | total repair failed |")
    lines.append("|---|---|---|---|---|---|---|---|")
    for arm, s in agg["stereo"]["chematic"].items():
        if s is None:
            lines.append(f"| {arm} | 0 | n/a | n/a | n/a | n/a | n/a | n/a |")
            continue
        lines.append(
            f"| {arm} | {s['n_molecules_with_declared_stereo']} | {fmt_num(s['mean_declared'], 2)} | "
            f"{fmt_num(s['mean_final_satisfied'], 2)} | {fmt_num(s['mean_final_violations'], 2)} | "
            f"{fmt_num(s['mean_final_unevaluable'], 2)} | {s['total_repaired']} | {s['total_repair_failed']} |"
        )
    lines.append("")
    lines.append("## Force-field coverage (chematic MMFF94 arms)")
    lines.append("")
    for arm, f in agg["force_field_coverage"]["chematic"].items():
        if f is None:
            lines.append(f"- {arm}: no successful rows")
            continue
        lines.append(
            f"- {arm}: n={f['n_success']}, fallback_rate={fmt_pct(f['fallback_rate'])}, "
            f"converged_rate={fmt_pct(f['converged_rate'])}"
        )
    lines.append("")
    lines.append("## Performance")
    lines.append("")
    lines.append(f"_{agg['performance']['methodology_note']}_")
    lines.append("")
    lines.append("### chematic")
    lines.append("")
    lines.append("| Arm | n | p50 (ms) | p95 (ms) | p99 (ms) | max (ms) |")
    lines.append("|---|---|---|---|---|---|")
    for arm, t in agg["performance"]["chematic"].items():
        if t is None:
            lines.append(f"| {arm} | 0 | n/a | n/a | n/a | n/a |")
            continue
        lines.append(f"| {arm} | {t['n']} | {fmt_num(t['p50'], 1)} | {fmt_num(t['p95'], 1)} | {fmt_num(t['p99'], 1)} | {t['max']} |")
    lines.append("")
    lines.append("### RDKit")
    lines.append("")
    lines.append("| Arm | n | p50 (ms) | p95 (ms) | p99 (ms) | max (ms) |")
    lines.append("|---|---|---|---|---|---|")
    for arm, t in agg["performance"]["rdkit"].items():
        if t is None:
            lines.append(f"| {arm} | 0 | n/a | n/a | n/a | n/a |")
            continue
        lines.append(f"| {arm} | {t['n']} | {fmt_num(t['p50'], 1)} | {fmt_num(t['p95'], 1)} | {fmt_num(t['p99'], 1)} | {t['max']} |")
    lines.append("")
    lines.append("## Ring-torsion FailClosed probe")
    lines.append("")
    lines.append(
        f"{agg['ring_torsion_failclosed_probe']['n_rows']} row(s) -- demonstrates "
        "`RingTorsionApplicationPolicy::FailClosed`'s documented behavior on the "
        "dedicated `known_fail_closed_case` fixture. Not folded into the 6 main "
        "arms' coverage numbers (those use `DiagnosticOnly`, see the dump "
        "executable's own comment for why)."
    )
    lines.append("")
    lines.append("## Reference geometry subset")
    lines.append("")
    lines.append(f"Status: **{agg['reference_geometry_subset']['status']}**. {agg['reference_geometry_subset']['note']}")
    lines.append("")
    lines.append("## Data integrity")
    lines.append("")
    lines.append(f"- Unclassified rows: {agg['unclassified_row_count']} (must be 0; see aggregate JSON if not)")
    lines.append(f"- chematic rows sha256: `{agg['input_file_hashes']['chematic_rows_sha256'][:16]}...`")
    lines.append(f"- RDKit rows sha256: `{agg['input_file_hashes']['rdkit_rows_sha256'][:16]}...`")
    lines.append("")
    lines.append("## Conclusions")
    lines.append("")
    lines.append(
        "_Filled in by hand after reviewing the numbers above -- classified "
        "per class/metric (chematic-favor / roughly-comparable / RDKit-favor / "
        "trade-off / incomparable / insufficient-evidence), never as a single "
        "overall win/loss score. See PR description for the full breakdown._"
    )
    lines.append("")

    REPORT_OUT.write_text("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
