#!/usr/bin/env python3
"""Freeze RDKit ETKDG conformer coordinates + RDKit's own G1 3D-descriptor
values into a shared JSON fixture for chematic's `rdkit_*` 3D descriptors
(crates/chematic-3d/src/rdkit_shape_descriptors.rs).

Methodology (see CLAUDE.md / v0.7 Accuracy Wave "Phase G1" task spec):
  1. Parse each test SMILES with RDKit, add explicit hydrogens (Chem.AddHs).
  2. Embed conformer(s) with RDKit's own ETKDGv3 (`AllChem.EmbedMolecule` /
     `EmbedMultipleConfs`), fixed random seed for reproducibility. No force-field
     refinement is applied -- these are raw ETKDG embeds, sufficient to exercise
     the descriptor math, not a conformer-quality claim (see the module's
     "publication-quality-conformer boundary" doc note).
  3. Freeze the resulting per-atom (atomic_num, x, y, z) coordinates -- for
     EVERY atom in the RDKit mol's current atom order (heavy + explicit H) --
     into this JSON file.
  4. Compute RDKit's own rdMolDescriptors.Calc{PMI1,PMI2,PMI3,NPR1,NPR2,
     RadiusOfGyration,InertialShapeFactor,Eccentricity,Asphericity,
     SpherocityIndex} and Descriptors3D-equivalent CalcPBF on that SAME
     conformer (same confId), and record them as "expected" values.

The frozen coordinates are later read from Rust (crates/chematic-3d/tests/
rdkit_g1_parity.rs) and fed to chematic's `rdkit_*` functions -- the *same*
array, never regenerated by chematic's own conformer generator -- so any
numeric agreement/disagreement is a genuine cross-implementation check, not a
self-comparison.

Run inside a FRESH venv (not the shared repo .venv):
    python3 -m venv /tmp/chematic-3dG-venv
    /tmp/chematic-3dG-venv/bin/pip install rdkit==2026.03.3
    /tmp/chematic-3dG-venv/bin/python3 scripts/gen_rdkit_3d_g1_fixtures.py
"""

import json
import sys
from pathlib import Path

from rdkit import Chem
from rdkit.Chem import AllChem, rdMolDescriptors

REPO_ROOT = Path(__file__).resolve().parent.parent
OUT_PATH = REPO_ROOT / "validation" / "rdkit_3d_g1_fixtures.json"

# name -> (smiles, n_confs)
MOLECULES = [
    ("methane", "C", 1),
    ("ethane", "CC", 1),
    ("ethanol", "CCO", 1),
    ("benzene", "c1ccccc1", 1),
    ("toluene", "Cc1ccccc1", 1),
    ("phenol", "Oc1ccccc1", 1),
    ("pyridine", "c1ccncc1", 1),
    ("naphthalene", "c1ccc2ccccc2c1", 1),
    ("cyclohexane", "C1CCCCC1", 1),
    ("adamantane", "C1C2CC3CC1CC(C2)C3", 1),
    ("norbornane", "C1CC2CCC1C2", 1),
    ("n_hexane", "CCCCCC", 1),
    ("n_decane", "CCCCCCCCCC", 1),
    ("aspirin", "CC(=O)Oc1ccccc1C(=O)O", 1),
    ("ibuprofen", "CC(C)Cc1ccc(cc1)C(C)C(=O)O", 3),  # multi-conformer case
    ("caffeine", "Cn1cnc2c1c(=O)n(C)c(=O)n2C", 1),
    ("paracetamol", "CC(=O)Nc1ccc(O)cc1", 1),
    ("cyclododecane_macrocycle", "C1CCCCCCCCCCC1", 1),  # 12-ring: RDKit's own
    # minMacrocycleRingSize (BoundsMatrixBuilder.cpp:38, pinned commit) is 9.
    # Halogen/S/P coverage: the atomic-weight table covers all 118 elements,
    # but only elements that actually appear in a fixture molecule are
    # empirically exercised by the comparison test -- these four add Cl, F,
    # S, and P to that set (the earlier corpus was C/H/N/O only).
    ("chlorobenzotrifluoride", "Clc1ccccc1C(F)(F)F", 1),
    ("thioanisole", "CSc1ccccc1", 1),
    ("trimethylphosphine_oxide", "CP(C)(C)=O", 1),
    ("dimethyl_sulfone", "CS(C)(=O)=O", 1),
]


def calc_all(mol: Chem.Mol, conf_id: int) -> dict:
    return {
        "pmi1": rdMolDescriptors.CalcPMI1(mol, confId=conf_id),
        "pmi2": rdMolDescriptors.CalcPMI2(mol, confId=conf_id),
        "pmi3": rdMolDescriptors.CalcPMI3(mol, confId=conf_id),
        "npr1": rdMolDescriptors.CalcNPR1(mol, confId=conf_id),
        "npr2": rdMolDescriptors.CalcNPR2(mol, confId=conf_id),
        "radius_of_gyration": rdMolDescriptors.CalcRadiusOfGyration(mol, confId=conf_id),
        "inertial_shape_factor": rdMolDescriptors.CalcInertialShapeFactor(mol, confId=conf_id),
        "eccentricity": rdMolDescriptors.CalcEccentricity(mol, confId=conf_id),
        "asphericity": rdMolDescriptors.CalcAsphericity(mol, confId=conf_id),
        "spherocity_index": rdMolDescriptors.CalcSpherocityIndex(mol, confId=conf_id),
        "pbf": rdMolDescriptors.CalcPBF(mol, confId=conf_id),
    }


def freeze_atoms(mol: Chem.Mol, conf_id: int) -> list:
    conf = mol.GetConformer(conf_id)
    atoms = []
    for atom in mol.GetAtoms():
        p = conf.GetAtomPosition(atom.GetIdx())
        atoms.append(
            {
                "atomic_num": atom.GetAtomicNum(),
                "symbol": atom.GetSymbol(),
                # repr()-round-trippable full double precision
                "x": p.x,
                "y": p.y,
                "z": p.z,
            }
        )
    return atoms


def main() -> None:
    print(f"RDKit version: {Chem.rdBase.rdkitVersion}", file=sys.stderr)

    fixtures = []
    for name, smiles, n_confs in MOLECULES:
        mol = Chem.MolFromSmiles(smiles)
        if mol is None:
            raise SystemExit(f"failed to parse SMILES for {name!r}: {smiles!r}")
        mol = Chem.AddHs(mol)

        params = AllChem.ETKDGv3()
        params.randomSeed = 0xC0FFEE
        if n_confs == 1:
            cid = AllChem.EmbedMolecule(mol, params)
            if cid < 0:
                raise SystemExit(f"ETKDG embedding failed for {name!r}")
            conf_ids = [cid]
        else:
            conf_ids = list(AllChem.EmbedMultipleConfs(mol, numConfs=n_confs, params=params))
            if len(conf_ids) < n_confs:
                raise SystemExit(f"ETKDG multi-embedding failed for {name!r}")

        for cid in conf_ids:
            fixtures.append(
                {
                    "name": name,
                    "smiles": smiles,
                    "conf_id": cid,
                    "atoms": freeze_atoms(mol, cid),
                    "expected": calc_all(mol, cid),
                }
            )
        print(f"  {name}: {len(conf_ids)} conformer(s), {mol.GetNumAtoms()} atoms (incl. H)", file=sys.stderr)

    doc = {
        "rdkit_version": Chem.rdBase.rdkitVersion,
        "rdkit_pinned_source_commit": "8afba32ec539dcb2369bc84549d802aca3f7eb39",
        "generated_by": "scripts/gen_rdkit_3d_g1_fixtures.py",
        "embedding": "AllChem.EmbedMolecule/EmbedMultipleConfs, ETKDGv3, randomSeed=0xC0FFEE, no FF refinement",
        "notes": (
            "atoms[] lists EVERY atom in RDKit's mol order (heavy + explicit H, "
            "post Chem.AddHs), matching what rdMolDescriptors.Calc* consumed for "
            "'expected'. chematic's rdkit_* functions must be fed the identical "
            "atom set/order to compare meaningfully -- RDKit's PMI/PBF/etc. always "
            "include explicit H (ignoreHs is hardcoded false in RDKit's own "
            "Descriptors/PMI.cpp getMoments()/getMomentsFromGyration())."
        ),
        "fixtures": fixtures,
    }

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    with open(OUT_PATH, "w") as f:
        json.dump(doc, f, indent=1)
        f.write("\n")
    print(f"wrote {len(fixtures)} fixture records to {OUT_PATH}", file=sys.stderr)


if __name__ == "__main__":
    main()
