#!/usr/bin/env python3
"""Prepare a provenance-bound 2,000/8,000 RDKit accuracy cohort.

This command intentionally cannot turn an existing repository corpus into a
sealed evaluation set.  It accepts independently acquired source data plus an
identity audit (canonical, parent and Bemis-Murcko scaffold keys) generated by
a pinned chemistry oracle.  The output remains ``prepared_not_sealed`` until a
candidate freeze is combined with either an explicit unused-data attestation
or machine-verifiable post-freeze source acquisition.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import subprocess
from collections.abc import Iterable
from datetime import datetime, timezone
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
REQUIRED_IDENTITY_KEYS = ("input_smiles", "canonical_smiles", "parent_smiles", "scaffold_smiles")


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def read_smiles(path: Path) -> list[str]:
    return [line.split(maxsplit=1)[0] for line in path.read_text(encoding="utf-8").splitlines() if line.strip()]


def read_identity(path: Path) -> list[dict[str, str]]:
    rows: list[dict[str, str]] = []
    for line_no, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        if not line.strip():
            continue
        try:
            row = json.loads(line)
        except json.JSONDecodeError as error:
            raise ValueError(f"{path}:{line_no}: invalid JSON: {error.msg}") from error
        if not isinstance(row, dict) or any(not isinstance(row.get(key), str) for key in REQUIRED_IDENTITY_KEYS):
            raise ValueError(f"{path}:{line_no}: expected string keys {', '.join(REQUIRED_IDENTITY_KEYS)}")
        rows.append({key: row[key] for key in REQUIRED_IDENTITY_KEYS})
    return rows


def identity_index(rows: Iterable[dict[str, str]]) -> dict[str, set[str]]:
    return {key: {row[key] for row in rows if row[key]} for key in REQUIRED_IDENTITY_KEYS[1:]}


def validate_source_metadata(path: Path, source_path: Path) -> dict[str, object]:
    metadata = json.loads(path.read_text(encoding="utf-8"))
    required = ("source_url", "source_release", "license", "acquired_at", "source_sha256")
    missing = [key for key in required if not isinstance(metadata.get(key), str) or not metadata[key].strip()]
    if missing:
        raise ValueError(f"source metadata missing required fields: {', '.join(missing)}")
    observed = sha256(source_path)
    if metadata["source_sha256"] != observed:
        raise ValueError("source metadata source_sha256 does not match --source")
    return metadata


def write_lines(path: Path, rows: list[dict[str, str]]) -> None:
    path.write_text("".join(f"{row['input_smiles']}\n" for row in rows), encoding="utf-8")


def resolve_git_commit(revision: str) -> str:
    completed = subprocess.run(
        ["git", "-C", str(ROOT), "rev-parse", "--verify", f"{revision}^{{commit}}"],
        capture_output=True,
        text=True,
    )
    if completed.returncode != 0:
        raise ValueError(f"candidate revision does not resolve to a commit: {revision}")
    return completed.stdout.strip()


def verify_candidate_freeze(candidate_commit: str, candidate_tag: str) -> dict[str, str]:
    resolved_commit = resolve_git_commit(candidate_commit)
    resolved_tag = resolve_git_commit(candidate_tag)
    if resolved_commit != resolved_tag:
        raise ValueError(
            f"candidate tag {candidate_tag} resolves to {resolved_tag}, not candidate commit {resolved_commit}"
        )
    completed = subprocess.run(
        [
            "git",
            "-C",
            str(ROOT),
            "for-each-ref",
            "--format=%(objecttype)%00%(taggerdate:iso-strict)",
            f"refs/tags/{candidate_tag}",
        ],
        capture_output=True,
        text=True,
    )
    object_type, separator, tagged_at = completed.stdout.strip().partition("\0")
    if completed.returncode != 0 or object_type != "tag" or not separator or not tagged_at:
        raise ValueError("candidate freeze requires an annotated candidate tag with a tagger timestamp")
    parse_rfc3339(tagged_at, "candidate tag timestamp")
    return {
        "candidate_commit": resolved_commit,
        "candidate_tag": candidate_tag,
        "candidate_tagged_at": tagged_at,
    }


def parse_rfc3339(value: str, field: str) -> datetime:
    try:
        parsed = datetime.fromisoformat(value.replace("Z", "+00:00"))
    except ValueError as error:
        raise ValueError(f"{field} must be an RFC 3339 timestamp") from error
    if parsed.tzinfo is None:
        raise ValueError(f"{field} must include a timezone")
    return parsed


def verify_attestation_timing(candidate_freeze: dict[str, str], attested_at: str) -> None:
    tagged_at = parse_rfc3339(candidate_freeze["candidate_tagged_at"], "candidate tag timestamp")
    attested = parse_rfc3339(attested_at, "attestation timestamp")
    if attested < tagged_at:
        raise ValueError(
            "unused-data attestation predates the annotated candidate tag; "
            "freeze the candidate before attesting"
        )


def verify_post_freeze_acquisition(
    candidate_freeze: dict[str, str], source_metadata: dict[str, object]
) -> None:
    tagged_at = parse_rfc3339(candidate_freeze["candidate_tagged_at"], "candidate tag timestamp")
    acquired_at = source_metadata.get("acquired_at")
    if not isinstance(acquired_at, str):
        raise ValueError("source metadata acquired_at must be a string")
    acquired = parse_rfc3339(acquired_at, "source acquisition timestamp")
    if acquired <= tagged_at:
        raise ValueError(
            "source acquisition must be later than the annotated candidate tag "
            "for post-freeze chronology attestation"
        )


def write_post_freeze_attestation(
    path: Path,
    candidate_freeze: dict[str, str],
    source_metadata: dict[str, object],
) -> dict[str, str]:
    verify_post_freeze_acquisition(candidate_freeze, source_metadata)
    source_sha256 = source_metadata["source_sha256"]
    acquired_at = source_metadata["acquired_at"]
    assert isinstance(source_sha256, str)
    assert isinstance(acquired_at, str)
    value = {
        "kind": "post_freeze_acquisition",
        "attestor": "automated chronology gate",
        "attested_at": datetime.now(timezone.utc).replace(microsecond=0).isoformat(),
        "statement": (
            "The source was acquired after the annotated candidate freeze and therefore "
            "could not have been used to select, tune, or develop that candidate."
        ),
        "source_sha256": source_sha256,
        "source_acquired_at": acquired_at,
        "candidate_commit": candidate_freeze["candidate_commit"],
        "candidate_tag": candidate_freeze["candidate_tag"],
        "candidate_tagged_at": candidate_freeze["candidate_tagged_at"],
    }
    path.write_text(json.dumps(value, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return {key: str(item) for key, item in value.items()} | {"sha256": sha256(path)}


def cohort_sealing_state(attestation: dict[str, str] | None) -> tuple[bool, str]:
    sealed = attestation is not None
    return sealed, "sealed" if sealed else "prepared_not_sealed"


def read_unused_attestation(path: Path, source_sha256: str) -> dict[str, str]:
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as error:
        raise ValueError(f"cannot read unused-data attestation: {error}") from error
    required = ("attestor", "attested_at", "statement", "source_sha256")
    if not isinstance(value, dict) or any(
        not isinstance(value.get(key), str) or not value[key].strip() for key in required
    ):
        raise ValueError(f"attestation requires non-empty string fields: {', '.join(required)}")
    if value["source_sha256"] != source_sha256:
        raise ValueError("attestation source_sha256 does not match the candidate source")
    return {key: value[key] for key in required} | {"sha256": sha256(path)}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, required=True, help="new independently acquired .smi input")
    parser.add_argument("--source-metadata", type=Path, required=True, help="JSON source URL/release/license/hash record")
    parser.add_argument("--identity-audit", type=Path, required=True, help="JSONL keys for every source row")
    parser.add_argument("--reference-identity-audit", type=Path, action="append", default=[], help="JSONL keys for exposed development/regression rows")
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--development-rows", type=int, default=2_000)
    parser.add_argument("--sealed-rows", type=int, default=8_000)
    parser.add_argument("--candidate-commit")
    parser.add_argument("--candidate-tag")
    parser.add_argument("--attest-unused", action="store_true", help="record maintainer attestation that source was not used for development")
    parser.add_argument("--attestation-file", type=Path, help="recorded JSON unused-data attestation for --attest-unused")
    parser.add_argument(
        "--attest-post-freeze-acquisition",
        action="store_true",
        help="seal only when source metadata proves acquisition after the annotated candidate tag",
    )
    args = parser.parse_args()
    if args.development_rows <= 0 or args.sealed_rows <= 0:
        parser.error("split sizes must be positive")
    if bool(args.candidate_commit) != bool(args.candidate_tag):
        parser.error("--candidate-commit and --candidate-tag must be supplied together")
    if args.attest_unused and not args.candidate_commit:
        parser.error("--attest-unused requires a candidate commit and tag")
    if args.attest_unused and not args.attestation_file:
        parser.error("--attest-unused requires --attestation-file")
    if args.attestation_file and not args.attest_unused:
        parser.error("--attestation-file requires --attest-unused")
    if args.attest_unused and args.attest_post_freeze_acquisition:
        parser.error("choose either --attest-unused or --attest-post-freeze-acquisition")
    if args.attest_post_freeze_acquisition and not args.candidate_commit:
        parser.error("--attest-post-freeze-acquisition requires a candidate commit and tag")

    source = args.source.resolve()
    identity_path = args.identity_audit.resolve()
    if not source.is_file() or not identity_path.is_file():
        parser.error("--source and --identity-audit must be readable files")
    source_rows = read_smiles(source)
    identities = read_identity(identity_path)
    if len(source_rows) != len(identities):
        parser.error("source and identity audit must have exactly the same row count")
    if any(smiles != row["input_smiles"] for smiles, row in zip(source_rows, identities, strict=True)):
        parser.error("source rows and identity audit input_smiles differ")
    metadata = validate_source_metadata(args.source_metadata.resolve(), source)
    candidate_freeze = (
        verify_candidate_freeze(args.candidate_commit, args.candidate_tag)
        if args.candidate_commit
        else None
    )
    output = args.output_dir.resolve()
    output.mkdir(parents=True, exist_ok=True)
    attestation = (
        read_unused_attestation(args.attestation_file.resolve(), metadata["source_sha256"])
        if args.attest_unused
        else None
    )
    if attestation is not None and candidate_freeze is not None:
        verify_attestation_timing(candidate_freeze, attestation["attested_at"])
    if args.attest_post_freeze_acquisition:
        assert candidate_freeze is not None
        attestation = write_post_freeze_attestation(
            output / "post-freeze-attestation.json", candidate_freeze, metadata
        )

    references: list[dict[str, str]] = []
    for path in args.reference_identity_audit:
        references.extend(read_identity(path.resolve()))
    reference_keys = identity_index(references)

    seen_canonical: set[str] = set()
    eligible: list[dict[str, str]] = []
    excluded: dict[str, int] = {"duplicate_canonical": 0, "reference_canonical": 0, "reference_parent": 0, "reference_scaffold": 0}
    for row in identities:
        canonical = row["canonical_smiles"]
        if canonical in seen_canonical:
            excluded["duplicate_canonical"] += 1
            continue
        seen_canonical.add(canonical)
        if canonical in reference_keys["canonical_smiles"]:
            excluded["reference_canonical"] += 1
            continue
        if row["parent_smiles"] and row["parent_smiles"] in reference_keys["parent_smiles"]:
            excluded["reference_parent"] += 1
            continue
        if row["scaffold_smiles"] and row["scaffold_smiles"] in reference_keys["scaffold_smiles"]:
            excluded["reference_scaffold"] += 1
            continue
        eligible.append(row)

    required = args.development_rows + args.sealed_rows
    if len(eligible) < required:
        parser.error(f"only {len(eligible)} eligible rows after audit; need {required}")
    development = eligible[:args.development_rows]
    sealed = eligible[args.development_rows:required]
    development_path = output / "development.smi"
    sealed_path = output / "sealed_holdout.smi"
    write_lines(development_path, development)
    write_lines(sealed_path, sealed)
    cohort_sealed, status = cohort_sealing_state(attestation)
    if args.attest_post_freeze_acquisition:
        reason = "candidate freeze predates independently recorded source acquisition"
    elif args.attest_unused:
        reason = "maintainer attestation and candidate freeze recorded"
    else:
        reason = "requires a candidate freeze and unused-data evidence"
    manifest = {
        "schema_version": 1,
        "protocol": "rdkit-accuracy-sealed-cohort-v1",
        "status": status,
        "sealed": cohort_sealed,
        "reason": reason,
        "prepared_at": datetime.now(timezone.utc).replace(microsecond=0).isoformat(),
        "source": {**metadata, "path": str(source), "observed_sha256": sha256(source), "input_rows": len(source_rows)},
        "identity_audit": {"path": str(identity_path), "sha256": sha256(identity_path), "required_keys": list(REQUIRED_IDENTITY_KEYS), "reference_audits": [{"path": str(path), "sha256": sha256(path)} for path in args.reference_identity_audit]},
        "deduplication": {"internal": "canonical_smiles", "against_references": ["canonical_smiles", "parent_smiles", "scaffold_smiles"], "excluded_rows": excluded},
        "splits": {"development": {"path": str(development_path), "rows": len(development), "sha256": sha256(development_path)}, "sealed_holdout": {"path": str(sealed_path), "rows": len(sealed), "sha256": sha256(sealed_path)}},
        "candidate_freeze": candidate_freeze,
        "unused_data_attestation": attestation,
    }
    (output / "manifest.json").write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(json.dumps({"status": status, "eligible_rows": len(eligible), "sealed_rows": len(sealed), "excluded_rows": excluded}, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
