//! RDKit-parity test for chematic's `rdkit_*` G1 3D scalar descriptors.
//!
//! Reads `validation/rdkit_3d_g1_fixtures.json` -- frozen RDKit ETKDGv3
//! conformer coordinates (heavy + explicit H, RDKit's own atom order) plus
//! RDKit's own `rdMolDescriptors.Calc*` reference values computed on those
//! *same* coordinates -- generated by
//! `scripts/gen_rdkit_3d_g1_fixtures.py` against a fresh `rdkit==2026.03.3`
//! venv (see that script's docstring for exact regeneration steps).
//!
//! The coordinates are fed to chematic's `rdkit_*` functions unmodified --
//! chematic's own conformer generator is never involved in this comparison
//! (see `crates/chematic-3d/src/rdkit_shape_descriptors.rs` module docs).
//!
//! Tolerance: measured, not assumed. This test prints per-descriptor max
//! absolute and max relative error across the whole fixture corpus, then
//! asserts against a tolerance set FROM that measurement (see the constants
//! below and the PR body for the actual measured numbers).

use chematic_3d::coords::{Coords3D, Point3};
use chematic_3d::rdkit_shape_descriptors::{
    MacrocycleStatus, RdkitDescriptorError, rdkit_asphericity, rdkit_eccentricity,
    rdkit_inertial_shape_factor, rdkit_npr1, rdkit_npr2, rdkit_pbf, rdkit_pmi1, rdkit_pmi2,
    rdkit_pmi3, rdkit_radius_of_gyration, rdkit_spherocity_index,
};
use chematic_core::{Atom, AtomIdx, Element, Molecule, MoleculeBuilder};
use serde_json::Value;

const FIXTURES: &str = include_str!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../validation/rdkit_3d_g1_fixtures.json"
));

// Measured from a full run against the 24-record / 22-molecule fixture corpus:
// observed max abs error 1.364e-12 (pmi2), observed max rel error 1.627e-11
// (pbf) -- both consistent with double-precision eigensolver noise (Eigen's
// SelfAdjointEigenSolver vs. chematic's Jacobi rotation solver), not a
// systematic formula difference. Tolerance below has ~500-700x headroom
// above those observed maxima -- generous enough to absorb ordinary
// cross-platform float variance, still tight enough to catch a real formula
// regression (see PR body for the full printed summary).
const MAX_ABS_TOL: f64 = 1e-9;
const MAX_REL_TOL: f64 = 1e-9;
/// Below this |expected| a relative-error comparison is meaningless (both
/// RDKit and chematic legitimately land near a numerical-noise-scale zero,
/// e.g. spherocity_index/PBF for a near-perfectly-planar ring); use absolute
/// error only in that regime.
const REL_FLOOR: f64 = 1e-6;

/// Builds a chematic `Molecule` + `Coords3D` from a fixture's frozen atom
/// list. Deliberately **bond-free** -- none of the G1 scalar descriptors
/// need connectivity, only per-atom element + position (see
/// `rdkit_shape_descriptors.rs` module docs) -- but this means
/// `detect_macrocycle_status` can never see real ring perception on these
/// molecules; every record here is expected to report
/// `MacrocycleStatus::Unscreenable`, asserted explicitly below rather than
/// silently ignored (see `crates/chematic-3d/src/rdkit_shape_descriptors.rs`
/// for why `Unscreenable` -- not a silent "not a macrocycle" -- is the
/// correct answer for a bond-free `Molecule`, even for the
/// `cyclododecane_macrocycle` fixture record, which genuinely is a 12-ring).
fn build_molecule(atoms: &[Value]) -> (Molecule, Coords3D) {
    let mut b = MoleculeBuilder::new();
    let mut coords = Coords3D::new_zeroed(atoms.len());
    for (i, a) in atoms.iter().enumerate() {
        let z = a["atomic_num"].as_u64().unwrap() as u8;
        let elem = Element::from_atomic_number(z)
            .unwrap_or_else(|| panic!("fixture has unsupported atomic number {z}"));
        b.add_atom(Atom::new(elem));
        let x = a["x"].as_f64().unwrap();
        let y = a["y"].as_f64().unwrap();
        let zc = a["z"].as_f64().unwrap();
        coords.set(AtomIdx(i as u32), Point3::new(x, y, zc));
    }
    (b.build(), coords)
}

#[derive(Default)]
struct ErrTracker {
    max_abs: f64,
    max_rel: f64,
    n_ok: usize,
}

impl ErrTracker {
    fn observe(&mut self, expected: f64, actual: f64) {
        let abs_err = (expected - actual).abs();
        self.max_abs = self.max_abs.max(abs_err);
        if expected.abs() > REL_FLOOR {
            let rel_err = abs_err / expected.abs();
            self.max_rel = self.max_rel.max(rel_err);
        }
        self.n_ok += 1;
    }
}

#[test]
fn rdkit_g1_descriptors_match_frozen_rdkit_oracle() {
    let doc: Value = serde_json::from_str(FIXTURES).expect("fixture JSON must parse");
    let rdkit_version = doc["rdkit_version"].as_str().unwrap();
    assert!(
        !rdkit_version.is_empty(),
        "fixture must record RDKit version"
    );

    let fixtures = doc["fixtures"].as_array().unwrap();
    assert!(
        fixtures.len() >= 15,
        "expected a real fixture corpus (>= 15 records), got {}",
        fixtures.len()
    );

    let names = [
        "pmi1",
        "pmi2",
        "pmi3",
        "npr1",
        "npr2",
        "radius_of_gyration",
        "inertial_shape_factor",
        "eccentricity",
        "asphericity",
        "spherocity_index",
        "pbf",
    ];
    let mut trackers: std::collections::BTreeMap<&str, ErrTracker> =
        names.iter().map(|&n| (n, ErrTracker::default())).collect();
    let mut degenerate_excluded: std::collections::BTreeMap<&str, usize> =
        names.iter().map(|&n| (n, 0usize)).collect();

    // Cross-check: every atomic number appearing in the fixture corpus is
    // actually covered (i.e. this run exercises more than just C/H/N/O).
    let mut atomic_numbers_seen = std::collections::BTreeSet::new();

    for fx in fixtures {
        let name = fx["name"].as_str().unwrap();
        let conf_id = fx["conf_id"].as_i64().unwrap();
        let atoms = fx["atoms"].as_array().unwrap();
        for a in atoms {
            atomic_numbers_seen.insert(a["atomic_num"].as_u64().unwrap());
        }
        let (mol, coords) = build_molecule(atoms);
        let expected = &fx["expected"];

        // See `build_molecule` doc comment: these are bond-free Molecules,
        // so macrocycle screening cannot run real ring perception on them --
        // it must honestly report `Unscreenable`, not silently claim
        // `NotMacrocyclic` (this is exactly what a real caller would get
        // back too, for a Molecule built the same bond-free way).
        let status_check = rdkit_pmi1(&mol, &coords).unwrap().macrocycle_status;
        assert_eq!(
            status_check,
            MacrocycleStatus::Unscreenable,
            "[{name}]: bond-free fixture Molecule must report Unscreenable, not a silent macrocycle answer"
        );

        macro_rules! check {
            ($key:literal, $func:expr) => {
                match $func(&mol, &coords) {
                    Ok(dv) => {
                        let exp = expected[$key].as_f64().unwrap();
                        trackers.get_mut($key).unwrap().observe(exp, dv.value);
                    }
                    Err(RdkitDescriptorError::DegenerateGeometry { .. }) => {
                        *degenerate_excluded.get_mut($key).unwrap() += 1;
                        eprintln!(
                            "  [{name} conf {conf_id}] {}: excluded (chematic DegenerateGeometry; \
                             RDKit's own silent-0.0 guard fired for this input)",
                            $key
                        );
                    }
                    Err(e) => panic!("[{name} conf {conf_id}] {}: unexpected error: {e}", $key),
                }
            };
        }

        check!("pmi1", rdkit_pmi1);
        check!("pmi2", rdkit_pmi2);
        check!("pmi3", rdkit_pmi3);
        check!("npr1", rdkit_npr1);
        check!("npr2", rdkit_npr2);
        check!("radius_of_gyration", rdkit_radius_of_gyration);
        check!("inertial_shape_factor", rdkit_inertial_shape_factor);
        check!("eccentricity", rdkit_eccentricity);
        check!("asphericity", rdkit_asphericity);
        check!("spherocity_index", rdkit_spherocity_index);
        check!("pbf", rdkit_pbf);
    }

    // Halogen/S/P coverage check -- these element weights are otherwise only
    // hand-transcribed from a live-oracle dump, never exercised numerically.
    for z in [9u64, 15, 16, 17] {
        assert!(
            atomic_numbers_seen.contains(&z),
            "fixture corpus does not exercise atomic number {z} (F=9/P=15/S=16/Cl=17) -- \
             add a molecule containing it so its RDKIT_ATOMIC_WEIGHTS entry is actually verified"
        );
    }

    eprintln!(
        "\n=== RDKit G1 parity summary (rdkit=={rdkit_version}, {} fixture records, {} distinct elements) ===",
        fixtures.len(),
        atomic_numbers_seen.len()
    );
    eprintln!(
        "{:<24} {:>8} {:>8} {:>14} {:>14}",
        "descriptor", "ok", "excluded", "max_abs_err", "max_rel_err"
    );
    let mut worst_abs = 0.0f64;
    let mut worst_rel = 0.0f64;
    for &n in &names {
        let t = &trackers[n];
        let excl = degenerate_excluded[n];
        eprintln!(
            "{:<24} {:>8} {:>8} {:>14.3e} {:>14.3e}",
            n, t.n_ok, excl, t.max_abs, t.max_rel
        );
        worst_abs = worst_abs.max(t.max_abs);
        worst_rel = worst_rel.max(t.max_rel);
        assert!(
            t.n_ok > 0,
            "{n}: zero successful comparisons -- fixture/descriptor mismatch"
        );
        assert!(
            t.max_abs < MAX_ABS_TOL,
            "{n}: max abs error {:.3e} exceeds tolerance {MAX_ABS_TOL:.3e}",
            t.max_abs
        );
        assert!(
            t.max_rel < MAX_REL_TOL,
            "{n}: max rel error {:.3e} exceeds tolerance {MAX_REL_TOL:.3e}",
            t.max_rel
        );
    }
    eprintln!("=== worst across all descriptors: abs={worst_abs:.3e} rel={worst_rel:.3e} ===\n");
}

/// Negative control: proves this harness is actually sensitive to a real
/// disagreement, not vacuously passing. Takes ONE real fixture record,
/// corrupts its expected PMI1 value by an amount far above [`MAX_ABS_TOL`],
/// and confirms the same tolerance assertion this test relies on would fail.
/// Standing lesson from this repo's own history: a parity script needs a
/// negative control, not just a positive one (see
/// `feedback_measurement_harness_controls` in the maintainer's notes).
#[test]
#[should_panic(expected = "exceeds tolerance")]
fn negative_control_corrupted_expected_value_is_detected() {
    let doc: Value = serde_json::from_str(FIXTURES).unwrap();
    let fixtures = doc["fixtures"].as_array().unwrap();
    let fx = &fixtures[0];
    let atoms = fx["atoms"].as_array().unwrap();
    let (mol, coords) = build_molecule(atoms);

    let actual = rdkit_pmi1(&mol, &coords).unwrap().value;
    // Corrupt the "expected" value by 1000x the tolerance -- this must NOT
    // be silently tolerated.
    let corrupted_expected = actual + MAX_ABS_TOL * 1000.0;
    let abs_err = (corrupted_expected - actual).abs();
    assert!(
        abs_err < MAX_ABS_TOL,
        "pmi1: max abs error {abs_err:.3e} exceeds tolerance {MAX_ABS_TOL:.3e}"
    );
}
