//! Chiral-volume / improper-torsion stereo constraint verification and repair
//! for already-embedded 3D geometries. 3D Breakthrough Program, Wave 2, Agent D
//! -- see `docs/rfcs/3d_breakthrough_master_plan.md` §0/§3 and `docs/rfcs/etkdg_3d_gap_rfc.md`
//! Phase 3 for the diagnosis this module answers.
//!
//! # What this is
//!
//! Given a `(mol, coords)` pair -- any already-embedded geometry, regardless of
//! which engine produced it -- this module:
//!
//! 1. [`verify_stereo`]: checks every declared tetrahedral (`@`/`@@`) center and every
//!    declared alkene E/Z bond (`/`/`\`) against the actual 3D geometry, and reports a
//!    typed, per-center/per-bond [`StereoStatus`] (never just a pooled boolean).
//! 2. [`repair_stereo`]: for every `Violated` entry, produces a corrected [`Coords3D`]
//!    that satisfies the declared stereo there, moving as little of the rest of the
//!    geometry as possible, and fails closed (typed [`RepairFailureReport`]) rather than
//!    ever returning coordinates that still violate a declared stereo element while
//!    claiming success.
//!
//! This is the module the fail-closed stub in `distance_geometry_v2.rs`
//! (`EmbedFailureCause::StereoConstraintFailed`) exists to be replaced by, once
//! Coordinator wires it in as a Wave 2 integration step. This module does not import
//! from or modify `distance_geometry_v2.rs`; it operates purely on `(mol, coords)`,
//! the same shape `bounds_conformance`/`assign_stereo_from_3d` already use, so it is
//! usable as a post-processing pass over any embedder's output.
//!
//! # Design: raw declared parity, not CIP R/S/E/Z labels
//!
//! `assign_stereo_from_3d` (this crate's existing 3D-to-stereo *perception* function,
//! the opposite direction from this module's job) requires `mol.neighbors(idx).count()
//! == 4` for tetrahedral centers -- i.e. **zero coverage** for any stereocenter with an
//! implicit hydrogen (one heavy neighbor short of 4), which is the majority case in
//! real molecules (L-alanine, ibuprofen, naproxen, menthol, ...) since `Coords3D` is
//! heavy-atom-only and never materializes H (`docs/rfcs/etkdg_3d_gap_rfc.md` §3). Routing
//! this module's verifier through that function would silently make it a no-op on
//! most of its own job.
//!
//! Instead, this module checks the **raw declared parity** directly:
//! `Molecule::stereo_neighbor_order` (the literal SMILES chirality-neighbor order,
//! with [`chematic_core::STEREO_H_SENTINEL`] standing in for an implicit H) plus the
//! `@`/`@@` `Chirality` flag define a signed-volume sign with **no CIP ranking
//! involved at all** -- see `assign_tetrahedral` in `chematic-chem/src/cip.rs`'s own
//! doc comment: "`@@` means: looking FROM neighbors[0], the sequence
//! neighbors[1]→neighbors[2]→neighbors[3] goes clockwise (CW)". Checking whether a 3D
//! geometry reproduces that raw ordering does not require resolving CIP priority, so
//! it works even when CIP ranking would be tied (a real, non-rare failure mode for the
//! project's existing CIP implementations) and covers implicit-H centers via a
//! standard "phantom" position for the missing 4th substituent (the direction
//! opposite the sum of the other three unit bond vectors -- exact for an ideal
//! tetrahedron, where the four unit vectors from the center sum to zero; only the
//! *sign* of the resulting volume matters, not phantom bond length precision).
//!
//! E/Z similarly never needs CIP: a declared `/`/`\` marks a *specific* substituent's
//! side directly (see `substituent_is_up` in `chematic-chem/src/cip.rs`), so this
//! module reproduces that same per-atom up/down convention and compares the declared
//! same-side/opposite-side relationship against the actual dihedral sign -- reusing
//! `stereo3d::dihedral` (already `pub(crate)`, called here rather than duplicated).
//!
//! Sign convention calibrated and verified against an **external oracle** (RDKit
//! `AssignStereochemistryFrom3D`), not derived from the doc comments above or from
//! any internal "CCW/CW when viewed from n0" reasoning -- an earlier version of this
//! module built exactly that reasoning and got the sign backwards, confirmed only
//! after independent review reproduced it against RDKit-embedded, RDKit-re-perception-
//! confirmed conformers (see `tetrahedral_matches_rdkit_*` tests and the PR body's
//! "sign convention correction" section for the full account). Internal hand
//! re-derivations of the same convention independently reproduced the same wrong
//! sign twice, which is why every fixture anchoring this predicate now (this
//! module's tests and `examples/stereo_constraints_gap_check.rs`'s fixture controls)
//! uses coordinates generated by RDKit, not hand-picked ones.
//!
//! # Repair design
//!
//! Tetrahedral: reflect one substituent's *direction* from the center through the
//! plane of the other three, then re-place it at the **original bond length** along
//! that new direction (a plain geometric reflection through that plane, without
//! renormalizing, inflates the bond length by ~67% even for a perfectly ideal
//! tetrahedron -- verified by hand for the regular-tetrahedron case, see PR body --
//! which would itself trip this codebase's bond-length-blowup convention). The moved
//! substituent's entire downstream subtree is translated rigidly by the same
//! displacement, so every bond length/angle *within* that subtree is preserved
//! exactly; only the one bond from the center to that substituent changes.
//!
//! E/Z: rotate one alkene terminus's entire non-double-bond substituent group 180°
//! around the axis through the two double-bond atoms. A rigid rotation about a fixed
//! axis preserves every bond length/angle within the rotated group exactly and
//! guarantees the cis/trans relationship to the other (untouched) terminus flips.
//!
//! Both repairs first verify the chosen substituent/group is a genuine graph bridge
//! (removing the center/terminus bond disconnects it from the rest of the molecule) --
//! translating or rotating part of a ring that closes back through the stereocenter
//! would corrupt the ring closure, so such candidates are rejected, not attempted.
//! Both repairs re-verify the specific element they targeted immediately after
//! applying the transform, and [`repair_stereo`] additionally re-verifies, at the
//! end, both every originally-`Satisfied` element AND every individually-"fixed"
//! element against the final geometry, to catch any cross-element regression --
//! including one repair silently undoing an *already-confirmed* fix on a different
//! element (found on real corpus data: two ring-fused stereocenters whose
//! individually bridge-safe substituents still overlapped enough for this to
//! happen). Never silently returns coordinates that still violate (or newly
//! violate) a declared stereo element while reporting success.

use std::collections::{HashSet, VecDeque};

use chematic_core::{
    AtomIdx, BondIdx, BondOrder, Chirality, Molecule, STEREO_H_SENTINEL, implicit_hcount,
};

use crate::coords::{Coords3D, Point3};

/// Signed-volume magnitude below this (phantom bond length is 1.0, real bond lengths
/// ~1-2 Å, so a genuine tetrahedral volume is order-1 or larger) is treated as a
/// degenerate/coplanar arrangement rather than floating-point noise.
/// Matches `stereo3d.rs`'s own `1e-6` convention for the identical signed-volume test.
const VOLUME_EPS: f64 = 1e-6;

/// Magnitude of the summed unit bond vectors below which the implicit-H phantom
/// direction is considered ill-defined (the three real substituents are arranged too
/// close to symmetric/planar to infer which side the missing 4th substituent is on).
///
/// ponytail: fixed threshold, not a tunable parameter -- revisit if a real corpus
/// molecule needs a different cutoff.
const PHANTOM_DIRECTION_EPS: f64 = 1e-3;

/// Arbitrary unit length for the implicit-H phantom position. Only the *direction*
/// (hence the sign of the resulting signed volume) matters for this module's checks;
/// this is never used as a physically accurate bond length anywhere.
const PHANTOM_BOND_LENGTH: f64 = 1.0;

// ---------------------------------------------------------------------------
// Public result types
// ---------------------------------------------------------------------------

/// Why a stereocenter or declared E/Z bond could not be evaluated against a geometry.
/// Mirrors `chematic_perception::stereo2d_local::StereoRejectionReason`'s pattern of
/// typed, named rejection (never a silent skip pooled into "no violation found").
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum StereoRejectionReason {
    /// The atom's declared-neighbor-order shape isn't a plain 4-substituent
    /// tetrahedral center (wrong neighbor count, more than one implicit-H sentinel,
    /// an inconsistent implicit-H count, or a non-single/up/down bond among its
    /// neighbors -- e.g. an allene/axial-chirality atom, not a simple tetrahedral one).
    UnsupportedCoordination,
    /// The signed volume (tetrahedral) or dihedral (E/Z) is within its epsilon of
    /// zero/undefined -- a coplanar or otherwise degenerate 3D arrangement.
    DegenerateGeometry,
    /// The three real substituents' bond directions summed to a near-zero vector, so
    /// the implicit-H phantom position's direction is ill-defined.
    DegenerateImplicitHDirection,
    /// The double bond is part of a cumulated system (allene-like: another double
    /// bond at one of its own atoms) -- not a simple E/Z bond. A double bond that is
    /// terminal on at least one end (no real substituent besides the other alkene
    /// atom, e.g. a carbonyl C=O) is filtered out earlier and never reported at all
    /// (it structurally cannot carry declared E/Z, regardless of markers elsewhere
    /// in the molecule -- see `verify_double_bond`'s doc comment), so this variant is
    /// reserved for the cumulated case in practice; kept as one name since both
    /// describe "not a simple E/Z bond".
    TerminalOrCumulatedAlkene,
    /// The bond carries a declared direction marker somewhere, but at least one
    /// alkene terminus has no substituent with an actual `/`/`\` marker (or an
    /// invertible complement) to anchor the comparison.
    AmbiguousDirection,
}

/// Verification outcome for one declared stereocenter or declared E/Z bond.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum StereoStatus {
    /// The 3D geometry reproduces the declared stereo.
    Satisfied,
    /// The 3D geometry contradicts the declared stereo.
    Violated,
    /// Could not be evaluated; see [`StereoRejectionReason`].
    Unevaluable(StereoRejectionReason),
}

impl StereoStatus {
    pub fn is_satisfied(&self) -> bool {
        matches!(self, StereoStatus::Satisfied)
    }
    pub fn is_violated(&self) -> bool {
        matches!(self, StereoStatus::Violated)
    }
}

/// A declared stereocenter (tetrahedral atom) or declared E/Z double bond, identified
/// uniformly for reporting/repair bookkeeping.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum StereoElement {
    Tetrahedral(AtomIdx),
    DoubleBond(BondIdx),
}

/// One declared tetrahedral stereocenter, turned into a constraint a future
/// embedding-time consumer could check or enforce -- independent of any particular
/// geometry (built from `mol` alone). See the "Constraint representation" section
/// near [`build_stereo_constraints`] for how this differs from [`TetrahedralReport`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) struct TetrahedralConstraint {
    pub atom: AtomIdx,
    /// Declared SMILES chirality-neighbor order (see [`declared_neighbor_order`]);
    /// one entry may be [`STEREO_H_SENTINEL`] for an implicit-H stereocenter. A
    /// consumer resolving this against real coordinates must substitute a phantom
    /// position for that slot the same way [`tetrahedral_positions`] does.
    pub order: [u32; 4],
    /// RDKit-calibrated (see this struct's constructor and the module's
    /// `tetrahedral_matches_rdkit_*` tests): `true` means a satisfying geometry must
    /// produce a NEGATIVE `signed_volume(order[1], order[2], order[3], order[0])`;
    /// `false` means positive. Expressed as the sign directly, not as a `@`/`@@`/CCW
    /// label, so a consumer never has to re-derive the CCW-to-sign mapping that this
    /// module's own sign convention got backwards twice before being pinned against
    /// an external RDKit oracle.
    pub requires_negative_volume: bool,
}

/// One declared E/Z double bond, turned into a constraint a future embedding-time
/// consumer could check or enforce -- independent of any particular geometry. See
/// [`build_stereo_constraints`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) struct DoubleBondConstraint {
    pub bond: BondIdx,
    pub end1: AtomIdx,
    pub end2: AtomIdx,
    /// The specific direction-marked substituent on `end1`'s side (see
    /// [`marked_substituent`]).
    pub sub1: AtomIdx,
    /// The specific direction-marked substituent on `end2`'s side.
    pub sub2: AtomIdx,
    /// `true` when a satisfying geometry must place `sub1` and `sub2` on the same
    /// side of the `end1`-`end2` axis (dihedral magnitude < 90°, matching
    /// [`verify_double_bond`]'s convention) -- not itself "cis"/"trans" or "Z"/"E",
    /// since those labels depend on CIP priority, which this module deliberately
    /// never resolves (see the module's "Design" doc section).
    pub same_side: bool,
}

/// One tetrahedral center's verification result.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct TetrahedralReport {
    pub atom: AtomIdx,
    pub status: StereoStatus,
}

/// One declared E/Z double bond's verification result.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct DoubleBondReport {
    pub bond: BondIdx,
    pub status: StereoStatus,
}

/// Full verification report for one `(mol, coords)` pair: every atom with declared
/// tetrahedral chirality, and every double bond with a declared `/`/`\` direction
/// marker on at least one adjacent bond -- nothing pooled into a single number.
#[derive(Debug, Clone, Default)]
pub struct StereoVerification {
    pub tetrahedral: Vec<TetrahedralReport>,
    pub double_bond: Vec<DoubleBondReport>,
}

impl StereoVerification {
    pub fn n_declared(&self) -> usize {
        self.tetrahedral.len() + self.double_bond.len()
    }

    pub fn n_satisfied(&self) -> usize {
        self.tetrahedral
            .iter()
            .filter(|r| r.status.is_satisfied())
            .count()
            + self
                .double_bond
                .iter()
                .filter(|r| r.status.is_satisfied())
                .count()
    }

    pub fn n_violations(&self) -> usize {
        self.tetrahedral
            .iter()
            .filter(|r| r.status.is_violated())
            .count()
            + self
                .double_bond
                .iter()
                .filter(|r| r.status.is_violated())
                .count()
    }

    pub fn n_unevaluable(&self) -> usize {
        self.n_declared() - self.n_satisfied() - self.n_violations()
    }

    pub fn violations(&self) -> Vec<StereoElement> {
        let mut out: Vec<StereoElement> = self
            .tetrahedral
            .iter()
            .filter(|r| r.status.is_violated())
            .map(|r| StereoElement::Tetrahedral(r.atom))
            .collect();
        out.extend(
            self.double_bond
                .iter()
                .filter(|r| r.status.is_violated())
                .map(|r| StereoElement::DoubleBond(r.bond)),
        );
        out
    }

    /// `true` when there are zero `Violated` entries (Unevaluable entries don't count
    /// against this -- they're unknown, not contradicted).
    pub fn is_fully_satisfied(&self) -> bool {
        self.n_violations() == 0
    }
}

// ---------------------------------------------------------------------------
// Verification entry point
// ---------------------------------------------------------------------------

/// Verify every declared tetrahedral stereocenter and declared E/Z double bond in
/// `mol` against `coords`. See the module docs for the raw-parity (no-CIP) design.
pub fn verify_stereo(mol: &Molecule, coords: &Coords3D) -> StereoVerification {
    let mut tetrahedral = Vec::new();
    for i in 0..mol.atom_count() {
        let idx = AtomIdx(i as u32);
        if mol.atom(idx).chirality == Chirality::None {
            continue;
        }
        tetrahedral.push(TetrahedralReport {
            atom: idx,
            status: verify_tetrahedral_center(mol, coords, idx),
        });
    }

    let mut double_bond = Vec::new();
    for j in 0..mol.bond_count() {
        let bidx = BondIdx(j as u32);
        if let Some(status) = verify_double_bond(mol, coords, bidx) {
            double_bond.push(DoubleBondReport { bond: bidx, status });
        }
    }

    StereoVerification {
        tetrahedral,
        double_bond,
    }
}

// ---------------------------------------------------------------------------
// Constraint representation (declared stereo, independent of any geometry)
// ---------------------------------------------------------------------------
//
// Everything above this point answers "does this geometry satisfy the declared
// stereo?" -- it needs `coords`. `build_stereo_constraints` answers a different,
// coords-free question: "what would a satisfying geometry have to look like?" --
// i.e. it is the "SMILES stereo -> StereoConstraintSet" step of the
// `SMILES stereo -> StereoConstraintSet -> bounds/chiral-volume/dihedral
// constraints -> DG -> verify` pipeline described in `docs/rfcs/etkdg_3d_gap_rfc.md`'s
// Phase 3 (issues #285, #210, #291). It reuses `tetrahedral_constraint_for`/
// `double_bond_constraint_for` -- the exact same declared-parity extraction
// `verify_stereo` itself runs -- so the constraint set and the verifier can never
// disagree about what's declared; see this module's `constraint_set_*_matches_rdkit_*`
// tests for that property checked directly against the RDKit-confirmed fixtures
// above, not just asserted.
//
// `pub(crate)` deliberately, not `pub`: `double_bond` now has a real embedding-time
// consumer (`distance_geometry_v2.rs`'s `apply_declared_ez_bounds`, `enforce_
// chirality`-only -- see that function's doc), but `tetrahedral` still doesn't
// (tetrahedral chiral-volume/dihedral bounds remain future, separately-scoped work,
// same reflection-invariance limitation `apply_declared_ez_bounds`'s own doc
// explains). Publishing this type before that second half is wired in would still
// overclaim what it does, the same shape of premature-publish this session already
// declined for issue #272's `topological_equivalence_classes`. Promote to `pub` once
// an embedder reads `tetrahedral` too.

/// Every declared tetrahedral/E-Z constraint `mol` implies, independent of any
/// particular geometry -- the coords-free counterpart to [`StereoVerification`].
///
/// `double_bond` has a real production consumer: `distance_geometry_v2.rs`'s
/// `apply_declared_ez_bounds` (`enforce_chirality` path only). `tetrahedral` does
/// not yet -- tetrahedral chiral-volume bounds are separately-scoped future work
/// (see that function's doc), so [`TetrahedralConstraint`] keeps its own
/// `#[allow(dead_code)]`.
#[derive(Debug, Clone, Default)]
pub(crate) struct StereoConstraintSet {
    pub tetrahedral: Vec<TetrahedralConstraint>,
    pub double_bond: Vec<DoubleBondConstraint>,
    /// Declared stereo elements that could not be turned into a constraint, with
    /// why -- kept in the set rather than silently dropped, since a consumer that
    /// only reads `tetrahedral`/`double_bond` and treats an incomplete set as
    /// exhaustive would silently under-constrain exactly the way issue #291
    /// documents production under-constraining today. Only the three
    /// [`StereoRejectionReason`] variants reachable without geometry can appear
    /// here (`UnsupportedCoordination`, `TerminalOrCumulatedAlkene`,
    /// `AmbiguousDirection`) -- `DegenerateGeometry`/`DegenerateImplicitHDirection`
    /// are geometry-dependent and never produced by this function.
    // `apply_declared_ez_bounds` only reads `double_bond` (an unsupported/ambiguous
    // declared bond has nothing this bound-construction step could act on); no
    // production consumer reads this field yet, hence the allow.
    #[allow(dead_code)]
    pub unsupported: Vec<(StereoElement, StereoRejectionReason)>,
}

#[allow(dead_code)]
impl StereoConstraintSet {
    pub fn n_constraints(&self) -> usize {
        self.tetrahedral.len() + self.double_bond.len()
    }
}

/// Build every declared stereo constraint in `mol`. Pure function of `mol` alone --
/// no `Coords3D` involved, unlike [`verify_stereo`]. See the section doc above for
/// what this is for and why it's `pub(crate)`.
pub(crate) fn build_stereo_constraints(mol: &Molecule) -> StereoConstraintSet {
    let mut tetrahedral = Vec::new();
    let mut unsupported = Vec::new();
    for i in 0..mol.atom_count() {
        let idx = AtomIdx(i as u32);
        if mol.atom(idx).chirality == Chirality::None {
            continue;
        }
        match tetrahedral_constraint_for(mol, idx) {
            Ok(c) => tetrahedral.push(c),
            Err(reason) => unsupported.push((StereoElement::Tetrahedral(idx), reason)),
        }
    }

    let mut double_bond = Vec::new();
    for j in 0..mol.bond_count() {
        let bidx = BondIdx(j as u32);
        if let Some(result) = double_bond_constraint_for(mol, bidx) {
            match result {
                Ok(c) => double_bond.push(c),
                Err(reason) => unsupported.push((StereoElement::DoubleBond(bidx), reason)),
            }
        }
    }

    StereoConstraintSet {
        tetrahedral,
        double_bond,
        unsupported,
    }
}

// ---------------------------------------------------------------------------
// Tetrahedral verification internals
// ---------------------------------------------------------------------------

/// Declared SMILES chirality-neighbor order for `idx` (4 entries, one possibly
/// [`STEREO_H_SENTINEL`]). Prefers the parser-recorded `stereo_neighbor_order`
/// (true textual encounter order, ring closures resolved correctly); falls back to
/// adjacency order + the same preceding-atom heuristic `chematic-chem/src/cip.rs`'s
/// private `stereo_neighbors` uses, for molecules built without parse-time stereo
/// data (e.g. directly via `MoleculeBuilder`). Returns `None` only when `idx` has no
/// declared chirality at all.
fn declared_neighbor_order(mol: &Molecule, idx: AtomIdx) -> Option<Vec<u32>> {
    if let Some(order) = mol.stereo_neighbor_order(idx) {
        return Some(order.to_vec());
    }
    let atom = mol.atom(idx);
    if atom.chirality == Chirality::None {
        return None;
    }
    let mut neighbors: Vec<u32> = mol.neighbors(idx).map(|(nb, _)| nb.0).collect();
    let has_bracket_h = atom.hydrogen_count.is_some_and(|h| h > 0);
    if has_bracket_h {
        let has_preceding = neighbors.first().map(|&nb| nb < idx.0).unwrap_or(false);
        let h_pos = if has_preceding { 1 } else { 0 };
        neighbors.insert(h_pos, STEREO_H_SENTINEL);
    }
    Some(neighbors)
}

/// Signed volume of the tetrahedron with vertices p1, p2, p3, p4 -- own copy of
/// `stereo3d.rs`'s (module-private there) formula; identical math (`(p1-p4) . ((p2-p4)
/// x (p3-p4))`), reimplemented here rather than exposing that private fn.
fn signed_volume(p1: Point3, p2: Point3, p3: Point3, p4: Point3) -> f64 {
    let a = p1.sub(&p4);
    let b = p2.sub(&p4);
    let c = p3.sub(&p4);
    a.dot(&b.cross(&c))
}

/// Estimate the position of a missing 4th (implicit-H) substituent: the direction
/// opposite the sum of the other three (unit) bond vectors from `center`. Exact for
/// an ideal tetrahedron (the four unit bond vectors from the center sum to zero);
/// only the resulting *sign* of a signed-volume test is relied on anywhere this is
/// used, never the exact position.
fn phantom_neighbor_position(
    center: Point3,
    real_neighbor_positions: &[Point3],
) -> Result<Point3, StereoRejectionReason> {
    let mut sum = Point3::new(0.0, 0.0, 0.0);
    for &p in real_neighbor_positions {
        let dir = p
            .sub(&center)
            .try_normalize()
            .ok_or(StereoRejectionReason::DegenerateGeometry)?;
        sum = sum.add(&dir);
    }
    let sum_norm = sum.norm();
    if sum_norm < PHANTOM_DIRECTION_EPS {
        return Err(StereoRejectionReason::DegenerateImplicitHDirection);
    }
    let phantom_dir = sum.scale(-1.0 / sum_norm);
    Ok(center.add(&phantom_dir.scale(PHANTOM_BOND_LENGTH)))
}

/// The 4 declared-order positions (real coordinates, or a computed phantom for the
/// implicit-H sentinel slot).
fn tetrahedral_positions(
    coords: &Coords3D,
    center_idx: AtomIdx,
    order: &[u32],
) -> Result<[Point3; 4], StereoRejectionReason> {
    let center = coords.get(center_idx);
    let real_positions: Vec<Point3> = order
        .iter()
        .filter(|&&n| n != STEREO_H_SENTINEL)
        .map(|&n| coords.get(AtomIdx(n)))
        .collect();
    let mut out = [Point3::new(0.0, 0.0, 0.0); 4];
    for (i, &n) in order.iter().enumerate() {
        out[i] = if n == STEREO_H_SENTINEL {
            phantom_neighbor_position(center, &real_positions)?
        } else {
            coords.get(AtomIdx(n))
        };
    }
    Ok(out)
}

/// Declared-parity-only prefix of tetrahedral verification, needing no geometry --
/// same gates, same order, as the coords-dependent code that used to precede the
/// geometry check inline (kept behavior-identical on purpose: this is a pure
/// extraction, see the PR that introduced [`TetrahedralConstraint`] for the
/// before/after test evidence). Only a plain tetrahedral center (single/up/down
/// bonds only) is in scope -- mirrors `stereo3d.rs`'s `assign_stereo_from_3d` gate,
/// excluding e.g. allene central atoms (which declare axial chirality via bond
/// directions, not `Atom::chirality`, and are handled by the double-bond path
/// instead).
fn tetrahedral_constraint_for(
    mol: &Molecule,
    idx: AtomIdx,
) -> Result<TetrahedralConstraint, StereoRejectionReason> {
    let atom = mol.atom(idx);
    // Only `CounterClockwise`/`Clockwise` are tetrahedral; `SquarePlanar` is
    // also `!= Chirality::None` but must never be coerced into a
    // chiral-volume check decided by `VOLUME_EPS` -- that tolerance is only
    // meaningful for a real tetrahedral arrangement, and treating a
    // square-planar center as "@@ tetrahedral" (the old
    // `requires_negative_volume: atom.chirality == Chirality::CounterClockwise`
    // silently did exactly this, since it's always `false` for
    // `SquarePlanar`) can make `repair_stereo` corrupt a correctly-declared
    // square-planar center. Reusing `UnsupportedCoordination`, the same
    // variant this function already returns a few lines below for other
    // "not a plain tetrahedral center" reasons, means every existing caller's
    // `Unevaluable`-is-"unknown, not contradicted" handling (e.g.
    // `repair_stereo`'s filter) applies for free.
    if !atom.chirality.is_tetrahedral() {
        return Err(StereoRejectionReason::UnsupportedCoordination);
    }

    let all_single_ish = mol.neighbors(idx).all(|(_, bidx)| {
        matches!(
            mol.bond(bidx).order,
            BondOrder::Single | BondOrder::Up | BondOrder::Down
        )
    });
    if !all_single_ish {
        return Err(StereoRejectionReason::UnsupportedCoordination);
    }

    let Some(order) = declared_neighbor_order(mol, idx) else {
        return Err(StereoRejectionReason::UnsupportedCoordination);
    };
    let n_sentinels = order.iter().filter(|&&n| n == STEREO_H_SENTINEL).count();
    if order.len() != 4 || n_sentinels > 1 {
        return Err(StereoRejectionReason::UnsupportedCoordination);
    }
    if n_sentinels == 1 && implicit_hcount(mol, idx) != 1 {
        return Err(StereoRejectionReason::UnsupportedCoordination);
    }

    Ok(TetrahedralConstraint {
        atom: idx,
        order: [order[0], order[1], order[2], order[3]],
        // RDKit-calibrated (see module docs and `tetrahedral_matches_rdkit_*`
        // tests): declared `@` (`Chirality::CounterClockwise`) requires a NEGATIVE
        // `signed_volume(order[1], order[2], order[3], order[0])`; `@@` requires
        // positive. Not derived from an internal "CCW/CW when viewed from n0"
        // mental model -- an earlier version of this predicate used that framing
        // and got the sign backwards twice (see git history / PR discussion).
        requires_negative_volume: atom.chirality == Chirality::CounterClockwise,
    })
}

fn verify_tetrahedral_center(mol: &Molecule, coords: &Coords3D, idx: AtomIdx) -> StereoStatus {
    let constraint = match tetrahedral_constraint_for(mol, idx) {
        Ok(c) => c,
        Err(reason) => return StereoStatus::Unevaluable(reason),
    };

    let positions = match tetrahedral_positions(coords, idx, &constraint.order) {
        Ok(p) => p,
        Err(reason) => return StereoStatus::Unevaluable(reason),
    };

    let volume = signed_volume(positions[1], positions[2], positions[3], positions[0]);
    if volume.abs() < VOLUME_EPS {
        return StereoStatus::Unevaluable(StereoRejectionReason::DegenerateGeometry);
    }
    let actual_negative = volume < 0.0;

    if actual_negative == constraint.requires_negative_volume {
        StereoStatus::Satisfied
    } else {
        StereoStatus::Violated
    }
}

// ---------------------------------------------------------------------------
// Double-bond (E/Z) verification internals
// ---------------------------------------------------------------------------

/// `true` when `atom_idx` has a double bond other than `exclude_bond` -- i.e. it's
/// part of a cumulated system (allene-like), not a simple isolated alkene terminus.
fn is_cumulated(mol: &Molecule, atom_idx: AtomIdx, exclude_bond: BondIdx) -> bool {
    mol.neighbors(atom_idx)
        .any(|(_, bidx)| bidx != exclude_bond && mol.bond(bidx).order == BondOrder::Double)
}

/// Find a substituent of `alkene_end` (excluding `other_end`) that carries an
/// explicit `/`/`\` direction marker, and whether it is on the "up" side. Mirrors
/// `substituent_is_up` in `chematic-chem/src/cip.rs` (reimplemented here rather than
/// depending on that private fn / pulling in CIP machinery this module doesn't need).
fn marked_substituent(
    mol: &Molecule,
    alkene_end: AtomIdx,
    other_end: AtomIdx,
) -> Option<(AtomIdx, bool)> {
    for (nb, bidx) in mol.neighbors(alkene_end) {
        if nb == other_end {
            continue;
        }
        let bond = mol.bond(bidx);
        if bond.order == BondOrder::Double {
            continue;
        }
        let effective = mol.bond_direction(bidx).unwrap_or(bond.order);
        match effective {
            BondOrder::Up => return Some((nb, bond.atom1 == alkene_end)),
            BondOrder::Down => return Some((nb, bond.atom1 == nb)),
            _ => continue,
        }
    }
    None
}

fn has_any_direction_marker(mol: &Molecule, alkene_end: AtomIdx, other_end: AtomIdx) -> bool {
    mol.neighbors(alkene_end).any(|(nb, bidx)| {
        nb != other_end
            && matches!(
                mol.bond_direction(bidx).unwrap_or(mol.bond(bidx).order),
                BondOrder::Up | BondOrder::Down
            )
    })
}

/// `true` when `atom_idx` has at least one heavy-atom neighbor other than
/// `other_end` -- i.e. it's a genuine, non-terminal alkene end that could plausibly
/// carry its own substituent-direction marker.
fn has_real_substituent(mol: &Molecule, atom_idx: AtomIdx, other_end: AtomIdx) -> bool {
    mol.neighbors(atom_idx).any(|(nb, _)| nb != other_end)
}

/// Declared-parity-only prefix of double-bond verification, needing no geometry --
/// same gates, same order, as the coords-dependent code that used to precede the
/// dihedral check inline (kept behavior-identical on purpose: this is a pure
/// extraction). `None` when `bond_idx` isn't a double bond, or has no declared
/// direction marker anywhere on it (not part of "declared stereo" at all, so not
/// reported -- callers must keep this outer `Option` distinct from the inner
/// `Result`'s `Err`: "not declared" and "declared but unsupported" are different
/// things everywhere else in this module). `Some(Err(..))` for a bond that clearly
/// *is* meant to carry declared E/Z but can't be turned into a constraint.
fn double_bond_constraint_for(
    mol: &Molecule,
    bond_idx: BondIdx,
) -> Option<Result<DoubleBondConstraint, StereoRejectionReason>> {
    let bond = mol.bond(bond_idx);
    if bond.order != BondOrder::Double {
        return None;
    }
    let a1 = bond.atom1;
    let a2 = bond.atom2;

    // A double bond with a terminal end (no substituent besides the other alkene
    // atom -- e.g. a carbonyl C=O, where O has no further substituent) structurally
    // cannot have E/Z stereo, full stop. This check must run BEFORE the marker scan
    // below: without it, a carbonyl carbon that happens to be directly bonded (via a
    // plain single bond) to a DIFFERENT, genuinely stereo-marked alkene elsewhere in
    // the molecule (e.g. `OC(=O)/C=C/c1ccccc1` -- the carbonyl carbon is bonded
    // directly to the alkene carbon carrying that alkene's own `/` marker) gets
    // mistaken for having *its own* declared E/Z, because the marker scan only looks
    // at "is there any Up/Down-marked bond among this atom's neighbors" without
    // checking whose double bond that marker actually belongs to. Found and fixed
    // via this module's own validation harness (`examples/
    // stereo_constraints_gap_check.rs`), not by inspection -- see the PR body.
    //
    // ponytail: this closes the exact cross-contamination pattern observed in the
    // frozen 58-molecule corpus (a C=O directly bonded to a marked alkene carbon).
    // It does not attempt full "which double bond does this single marked bond
    // belong to" disambiguation for the theoretical case of two non-terminal,
    // directly-connected double bonds sharing a marked connector bond (e.g. a
    // conjugated dienone) -- not present in this corpus (re-verified after this fix);
    // revisit if a real molecule needs it.
    if !has_real_substituent(mol, a1, a2) || !has_real_substituent(mol, a2, a1) {
        return None;
    }

    if !has_any_direction_marker(mol, a1, a2) && !has_any_direction_marker(mol, a2, a1) {
        return None; // no declared E/Z on this double bond
    }

    if is_cumulated(mol, a1, bond_idx) || is_cumulated(mol, a2, bond_idx) {
        return Some(Err(StereoRejectionReason::TerminalOrCumulatedAlkene));
    }

    let Some((sub1, up1)) = marked_substituent(mol, a1, a2) else {
        return Some(Err(StereoRejectionReason::AmbiguousDirection));
    };
    let Some((sub2, up2)) = marked_substituent(mol, a2, a1) else {
        return Some(Err(StereoRejectionReason::AmbiguousDirection));
    };

    Some(Ok(DoubleBondConstraint {
        bond: bond_idx,
        end1: a1,
        end2: a2,
        sub1,
        sub2,
        same_side: up1 == up2,
    }))
}

/// `None` when `bond_idx` isn't a double bond, or has no declared direction marker
/// anywhere on it (not part of "declared stereo" at all, so not reported). `Some`
/// otherwise, including `Unevaluable` outcomes for a bond that clearly *is* meant to
/// carry declared E/Z but can't be evaluated.
fn verify_double_bond(
    mol: &Molecule,
    coords: &Coords3D,
    bond_idx: BondIdx,
) -> Option<StereoStatus> {
    let constraint = match double_bond_constraint_for(mol, bond_idx)? {
        Ok(c) => c,
        Err(reason) => return Some(StereoStatus::Unevaluable(reason)),
    };

    let Some(angle) = crate::stereo3d::dihedral(
        coords.get(constraint.end1),
        coords.get(constraint.end2),
        coords.get(constraint.sub1),
        coords.get(constraint.sub2),
    ) else {
        return Some(StereoStatus::Unevaluable(
            StereoRejectionReason::DegenerateGeometry,
        ));
    };
    let actual_same_side = angle.abs() < std::f64::consts::FRAC_PI_2;

    Some(if actual_same_side == constraint.same_side {
        StereoStatus::Satisfied
    } else {
        StereoStatus::Violated
    })
}

/// Diagnostic-only detail for one declared E/Z double bond: everything
/// [`verify_double_bond`] computes internally and discards -- the constraint's
/// atom indices, the raw dihedral angle (radians), and the resulting status --
/// plus how far past the hard 90 degree satisfied/violated boundary the actual
/// angle lands (`margin_from_boundary_deg`, always >= 0; small values mean the
/// call is close to the boundary, not a robust result either way). Added for
/// issue #227 Phase 2's BCI-fix stereo-drift investigation
/// (`chembl_tier_b_0082`): production `verify_double_bond`/`verify_stereo`
/// intentionally keep this data internal (a per-atom-index/per-radian API
/// would be a much larger public surface than the raw Satisfied/Violated/
/// Unevaluable status callers need) -- this is purely additive, not called
/// from any production path.
#[derive(Debug, Clone, Copy)]
pub struct DoubleBondDebugInfo {
    pub bond: BondIdx,
    pub end1: AtomIdx,
    pub end2: AtomIdx,
    pub sub1: AtomIdx,
    pub sub2: AtomIdx,
    pub declared_same_side: bool,
    pub actual_angle_rad: f64,
    pub actual_angle_deg: f64,
    pub actual_same_side: bool,
    pub margin_from_boundary_deg: f64,
    pub status: StereoStatus,
}

/// Diagnostic counterpart to [`verify_double_bond`] -- same computation, but
/// returns the full [`DoubleBondDebugInfo`] instead of just [`StereoStatus`].
/// `None` under the identical conditions `verify_double_bond` would return
/// `None` for (not a double bond, or no declared E/Z on it); a bond that *is*
/// declared but unevaluable (e.g. degenerate geometry, ambiguous direction)
/// returns `None` here too, since there is no angle to report -- callers that
/// need the [`StereoRejectionReason`] should call `verify_double_bond`/
/// `verify_stereo` directly.
pub fn debug_double_bond(
    mol: &Molecule,
    coords: &Coords3D,
    bond_idx: BondIdx,
) -> Option<DoubleBondDebugInfo> {
    let constraint = double_bond_constraint_for(mol, bond_idx)?.ok()?;

    let angle = crate::stereo3d::dihedral(
        coords.get(constraint.end1),
        coords.get(constraint.end2),
        coords.get(constraint.sub1),
        coords.get(constraint.sub2),
    )?;
    let actual_same_side = angle.abs() < std::f64::consts::FRAC_PI_2;
    let status = if actual_same_side == constraint.same_side {
        StereoStatus::Satisfied
    } else {
        StereoStatus::Violated
    };
    let boundary_deg = 90.0;
    let angle_deg = angle.to_degrees();
    let margin_from_boundary_deg = (angle_deg.abs() - boundary_deg).abs();

    Some(DoubleBondDebugInfo {
        bond: bond_idx,
        end1: constraint.end1,
        end2: constraint.end2,
        sub1: constraint.sub1,
        sub2: constraint.sub2,
        declared_same_side: constraint.same_side,
        actual_angle_rad: angle,
        actual_angle_deg: angle_deg,
        actual_same_side,
        margin_from_boundary_deg,
        status,
    })
}

/// Diagnostic helper: every declared-E/Z double bond in `mol`, with full
/// [`DoubleBondDebugInfo`] where evaluable. Iterates all bonds (small
/// molecules only -- linear scan, not indexed) rather than requiring the
/// caller to already know which `BondIdx` carries declared E/Z.
pub fn debug_all_double_bonds(mol: &Molecule, coords: &Coords3D) -> Vec<DoubleBondDebugInfo> {
    (0..mol.bond_count())
        .filter_map(|i| debug_double_bond(mol, coords, BondIdx(i as u32)))
        .collect()
}

// ---------------------------------------------------------------------------
// Repair
// ---------------------------------------------------------------------------

/// Why a repair attempt for one stereo element failed.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RepairRejectionReason {
    /// No candidate substituent/terminus group could be isolated as a genuine graph
    /// bridge (every option is part of a ring that closes back through the center/
    /// other alkene atom) -- moving any of them would corrupt a ring closure.
    NoBridgeEligibleSubstituent,
    /// The plane through the three fixed reference points is degenerate (collinear
    /// points), so no reflection direction could be computed.
    DegenerateReflectionPlane,
    /// The direction from the center to the reflected point (tetrahedral) or the
    /// double-bond axis direction (E/Z) is degenerate (near-zero length).
    DegenerateReflectionDirection,
    /// The targeted element was re-checked immediately after applying the repair and
    /// is still `Violated` -- the geometric transform did not have the expected
    /// effect (should be rare; reported, never silently treated as success).
    StillViolatedAfterRepair,
    /// An element that was fine a moment ago -- either `Satisfied` before repair
    /// started, or `Violated` and already individually confirmed fixed by its own
    /// repair attempt -- ended up `Violated` in the final geometry because some
    /// *other*, unrelated repair in the same `repair_stereo` call moved
    /// shared/overlapping geometry it depended on.
    RepairCausedNewViolation,
}

/// One successfully repaired stereo element.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct RepairedElement {
    pub element: StereoElement,
    /// Number of atoms whose position changed to perform this repair.
    pub atoms_moved: usize,
    /// Magnitude of the largest single-atom displacement this repair caused (Å).
    pub max_displacement: f64,
}

/// Result of a fully successful [`repair_stereo`] call: every originally-`Violated`
/// element now `Satisfied`, and no originally-`Satisfied` element regressed.
#[derive(Debug, Clone)]
pub struct RepairOutcome {
    pub coords: Coords3D,
    pub repaired: Vec<RepairedElement>,
    /// Elements that were `Unevaluable` before repair and were left untouched (not
    /// attempted -- there is nothing to compare a repair's result against).
    pub unevaluable: Vec<StereoElement>,
}

/// Result of a [`repair_stereo`] call that could not fully succeed. `partial_coords`
/// reflects every repair attempt made (successes and the one that first failed) but
/// must **not** be treated as satisfying every declared stereo element -- see
/// `failures` for exactly which element(s) don't.
#[derive(Debug, Clone)]
pub struct RepairFailureReport {
    pub partial_coords: Coords3D,
    pub repaired: Vec<RepairedElement>,
    pub failures: Vec<(StereoElement, RepairRejectionReason)>,
}

/// BFS component reachable from `starts`, never stepping into `blocked`. Returns
/// `None` if the search reaches any atom in `forbidden` -- meaning the starting
/// point(s) are not a clean graph bridge off `blocked` (some path loops back to the
/// rest of the molecule through a ring, not just through `blocked` itself).
fn bridge_component(
    mol: &Molecule,
    starts: &[AtomIdx],
    blocked: AtomIdx,
    forbidden: &[AtomIdx],
) -> Option<HashSet<AtomIdx>> {
    let mut seen: HashSet<AtomIdx> = starts.iter().copied().collect();
    let mut queue: VecDeque<AtomIdx> = starts.iter().copied().collect();
    while let Some(cur) = queue.pop_front() {
        for (nb, _) in mol.neighbors(cur) {
            if nb == blocked {
                continue;
            }
            if forbidden.contains(&nb) {
                return None;
            }
            if seen.insert(nb) {
                queue.push_back(nb);
            }
        }
    }
    Some(seen)
}

fn repair_tetrahedral_center(
    mol: &Molecule,
    coords: &mut Coords3D,
    idx: AtomIdx,
) -> Result<RepairedElement, RepairRejectionReason> {
    let order = declared_neighbor_order(mol, idx)
        .expect("already validated Some by verify_stereo before repair was attempted");
    let real_neighbors: Vec<u32> = order
        .iter()
        .copied()
        .filter(|&n| n != STEREO_H_SENTINEL)
        .collect();

    // Pick the smallest bridge-eligible real substituent to move (least disturbance).
    let mut best: Option<(u32, HashSet<AtomIdx>)> = None;
    for &cand in &real_neighbors {
        let others: Vec<AtomIdx> = real_neighbors
            .iter()
            .copied()
            .filter(|&n| n != cand)
            .map(AtomIdx)
            .collect();
        if let Some(component) = bridge_component(mol, &[AtomIdx(cand)], idx, &others)
            && best
                .as_ref()
                .map(|(_, c)| component.len() < c.len())
                .unwrap_or(true)
        {
            best = Some((cand, component));
        }
    }
    let Some((moved, component)) = best else {
        return Err(RepairRejectionReason::NoBridgeEligibleSubstituent);
    };

    // Declared-order positions BEFORE any mutation (phantom computed from the
    // original, not-yet-moved real neighbor positions).
    let center = coords.get(idx);
    let positions4: Vec<Point3> = order
        .iter()
        .map(|&n| {
            if n == STEREO_H_SENTINEL {
                let real_positions: Vec<Point3> = real_neighbors
                    .iter()
                    .map(|&r| coords.get(AtomIdx(r)))
                    .collect();
                phantom_neighbor_position(center, &real_positions)
                    .expect("already validated by verify_stereo before repair was attempted")
            } else {
                coords.get(AtomIdx(n))
            }
        })
        .collect();

    let moved_slot = order
        .iter()
        .position(|&n| n == moved)
        .expect("moved came from order");
    let others: Vec<Point3> = (0..4)
        .filter(|&i| i != moved_slot)
        .map(|i| positions4[i])
        .collect();

    let normal = others[1]
        .sub(&others[0])
        .cross(&others[2].sub(&others[0]))
        .try_normalize()
        .ok_or(RepairRejectionReason::DegenerateReflectionPlane)?;

    let p_moved = positions4[moved_slot];
    let signed_dist = normal.dot(&p_moved.sub(&others[0]));
    let reflected = p_moved.sub(&normal.scale(2.0 * signed_dist));
    let direction = reflected
        .sub(&center)
        .try_normalize()
        .ok_or(RepairRejectionReason::DegenerateReflectionDirection)?;
    let bond_len = p_moved.sub(&center).norm();
    let new_p_moved = center.add(&direction.scale(bond_len));
    let displacement = new_p_moved.sub(&p_moved);
    let displacement_mag = displacement.norm();

    for &atom in &component {
        let old = coords.get(atom);
        coords.set(atom, old.add(&displacement));
    }

    match verify_tetrahedral_center(mol, coords, idx) {
        StereoStatus::Satisfied => Ok(RepairedElement {
            element: StereoElement::Tetrahedral(idx),
            atoms_moved: component.len(),
            max_displacement: displacement_mag,
        }),
        _ => Err(RepairRejectionReason::StillViolatedAfterRepair),
    }
}

fn rotate_180_around_axis(p: Point3, axis_point: Point3, axis_dir: Point3) -> Point3 {
    let v = p.sub(&axis_point);
    let parallel = axis_dir.scale(v.dot(&axis_dir));
    let perp = v.sub(&parallel);
    let new_v = parallel.sub(&perp);
    axis_point.add(&new_v)
}

fn repair_double_bond(
    mol: &Molecule,
    coords: &mut Coords3D,
    bond_idx: BondIdx,
) -> Result<RepairedElement, RepairRejectionReason> {
    let bond = mol.bond(bond_idx);
    let a1 = bond.atom1;
    let a2 = bond.atom2;

    let a1_subs: Vec<AtomIdx> = mol
        .neighbors(a1)
        .filter(|&(nb, _)| nb != a2)
        .map(|(nb, _)| nb)
        .collect();
    let a2_subs: Vec<AtomIdx> = mol
        .neighbors(a2)
        .filter(|&(nb, _)| nb != a1)
        .map(|(nb, _)| nb)
        .collect();

    let a1_component = if a1_subs.is_empty() {
        None
    } else {
        bridge_component(mol, &a1_subs, a1, &[a2])
    };
    let a2_component = if a2_subs.is_empty() {
        None
    } else {
        bridge_component(mol, &a2_subs, a2, &[a1])
    };

    let (pivot, other_end, component) = match (a1_component, a2_component) {
        (Some(c1), Some(c2)) => {
            if c1.len() <= c2.len() {
                (a1, a2, c1)
            } else {
                (a2, a1, c2)
            }
        }
        (Some(c1), None) => (a1, a2, c1),
        (None, Some(c2)) => (a2, a1, c2),
        (None, None) => return Err(RepairRejectionReason::NoBridgeEligibleSubstituent),
    };

    let axis_point = coords.get(pivot);
    let axis_dir = coords
        .get(other_end)
        .sub(&axis_point)
        .try_normalize()
        .ok_or(RepairRejectionReason::DegenerateReflectionDirection)?;

    let mut max_disp = 0.0_f64;
    for &atom in &component {
        let old = coords.get(atom);
        let new = rotate_180_around_axis(old, axis_point, axis_dir);
        let disp = new.sub(&old).norm();
        if disp > max_disp {
            max_disp = disp;
        }
        coords.set(atom, new);
    }

    match verify_double_bond(mol, coords, bond_idx) {
        Some(StereoStatus::Satisfied) => Ok(RepairedElement {
            element: StereoElement::DoubleBond(bond_idx),
            atoms_moved: component.len(),
            max_displacement: max_disp,
        }),
        _ => Err(RepairRejectionReason::StillViolatedAfterRepair),
    }
}

/// Verify `(mol, coords)`, then repair every `Violated` element found. Returns
/// `Ok(RepairOutcome)` only when every originally-`Violated` element is now
/// `Satisfied` **and** no originally-`Satisfied` element regressed; otherwise
/// `Err(RepairFailureReport)` naming exactly which element(s) failed and why.
/// `Unevaluable` elements are left untouched either way (nothing to compare a repair
/// against).
pub fn repair_stereo(
    mol: &Molecule,
    coords: &Coords3D,
) -> Result<RepairOutcome, RepairFailureReport> {
    let initial = verify_stereo(mol, coords);
    let mut working = coords.clone();
    let mut repaired = Vec::new();
    let mut failures: Vec<(StereoElement, RepairRejectionReason)> = Vec::new();

    let unevaluable: Vec<StereoElement> = initial
        .tetrahedral
        .iter()
        .filter(|r| matches!(r.status, StereoStatus::Unevaluable(_)))
        .map(|r| StereoElement::Tetrahedral(r.atom))
        .chain(
            initial
                .double_bond
                .iter()
                .filter(|r| matches!(r.status, StereoStatus::Unevaluable(_)))
                .map(|r| StereoElement::DoubleBond(r.bond)),
        )
        .collect();

    for t in &initial.tetrahedral {
        if t.status.is_violated() {
            match repair_tetrahedral_center(mol, &mut working, t.atom) {
                Ok(info) => repaired.push(info),
                Err(reason) => failures.push((StereoElement::Tetrahedral(t.atom), reason)),
            }
        }
    }
    for d in &initial.double_bond {
        if d.status.is_violated() {
            match repair_double_bond(mol, &mut working, d.bond) {
                Ok(info) => repaired.push(info),
                Err(reason) => failures.push((StereoElement::DoubleBond(d.bond), reason)),
            }
        }
    }

    // Unconditional final reconciliation pass -- runs whether or not the loop above
    // already produced failures, and checks BOTH directions:
    //   (a) an originally-Satisfied element disturbed by some OTHER element's repair.
    //   (b) an originally-Violated element that `repair_tetrahedral_center`/
    //       `repair_double_bond`'s OWN immediate re-verify confirmed fixed (already
    //       pushed to `repaired`), but which a STILL LATER, unrelated repair in this
    //       same call silently moved back into violation.
    // (b) is not hypothetical: found via this module's own validation harness on
    // real corpus data (cholesterol) -- two ring-fused stereocenters whose bridge-
    // safe substituents can still overlap enough that fixing one undoes an
    // already-confirmed fix on another, even though each individual repair's own
    // bridge check passed. Both directions are reported the same way
    // (`RepairCausedNewViolation`): from the caller's perspective, both mean "some
    // OTHER repair in this call broke something that was fine a moment ago." This
    // is a detect-and-fail-closed pass, not an iterate-to-a-fixed-point one -- a
    // caller can retry `repair_stereo` on the returned `partial_coords` if a fixed
    // point is reachable, but this function does not loop internally.
    let final_check = verify_stereo(mol, &working);

    let mut still_repaired = Vec::with_capacity(repaired.len());
    for info in repaired {
        let now = match info.element {
            StereoElement::Tetrahedral(a) => final_check
                .tetrahedral
                .iter()
                .find(|x| x.atom == a)
                .map(|x| x.status),
            StereoElement::DoubleBond(b) => final_check
                .double_bond
                .iter()
                .find(|x| x.bond == b)
                .map(|x| x.status),
        };
        if matches!(now, Some(StereoStatus::Satisfied)) {
            still_repaired.push(info);
        } else {
            failures.push((
                info.element,
                RepairRejectionReason::RepairCausedNewViolation,
            ));
        }
    }
    let repaired = still_repaired;

    for t in &initial.tetrahedral {
        if t.status.is_satisfied() {
            let now = final_check
                .tetrahedral
                .iter()
                .find(|x| x.atom == t.atom)
                .map(|x| x.status);
            if matches!(now, Some(StereoStatus::Violated)) {
                failures.push((
                    StereoElement::Tetrahedral(t.atom),
                    RepairRejectionReason::RepairCausedNewViolation,
                ));
            }
        }
    }
    for d in &initial.double_bond {
        if d.status.is_satisfied() {
            let now = final_check
                .double_bond
                .iter()
                .find(|x| x.bond == d.bond)
                .map(|x| x.status);
            if matches!(now, Some(StereoStatus::Violated)) {
                failures.push((
                    StereoElement::DoubleBond(d.bond),
                    RepairRejectionReason::RepairCausedNewViolation,
                ));
            }
        }
    }

    if !failures.is_empty() {
        return Err(RepairFailureReport {
            partial_coords: working,
            repaired,
            failures,
        });
    }

    Ok(RepairOutcome {
        coords: working,
        repaired,
        unevaluable,
    })
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use chematic_smiles::parse;

    fn mol(s: &str) -> Molecule {
        parse(s).unwrap_or_else(|e| panic!("parse '{s}': {e:?}"))
    }

    // -------------------------------------------------------------------------
    // Sign-convention empirical verification, against an EXTERNAL oracle (RDKit),
    // not internal hand-derived math.
    // -------------------------------------------------------------------------
    //
    // An earlier version of this test suite anchored the sign convention on
    // `stereo3d.rs`'s own `signed_volume_positive_ccw` test and on hand-derived
    // "CCW/CW when viewed from n0" reasoning. Both turned out unreliable: the
    // "CCW" label in that borrowed fixture doesn't mean what it was assumed to
    // mean here (harmless in `stereo3d.rs`, where the volume sign maps straight to
    // R/S without ever naming an intermediate CCW/CW concept -- but load-bearing
    // once this module built an actual CCW/CW predicate on top of it), and hand
    // math independently re-derived the same wrong sign twice. Every fixture below
    // instead uses coordinates generated by RDKit (`AllChem.EmbedMolecule` +
    // `AllChem.MMFFOptimizeMolecule`, ETKDGv3, `randomSeed=0xF00D`) and confirmed
    // by RDKit's OWN `Chem.AssignStereochemistryFrom3D` to reproduce the declared
    // `@`/`@@` tag (or E/Z bond stereo) -- i.e. ground truth from a second,
    // independent cheminformatics engine's 3D-structure re-perception, not from
    // reasoning about this codebase's own conventions.

    /// RDKit ETKDGv3-embedded, MMFF-optimized coordinates for `[C@](Br)(Cl)(F)I`,
    /// confirmed by `Chem.AssignStereochemistryFrom3D` to reproduce the declared
    /// `@` (R) configuration.
    fn rdkit_quaternary_ccw_coords(m: &Molecule) -> Coords3D {
        let mut c = Coords3D::new_zeroed(m.atom_count());
        c.set(AtomIdx(0), Point3::new(-0.038544, 0.056669, -0.102453)); // C
        c.set(AtomIdx(1), Point3::new(-1.336020, -1.293737, 0.415705)); // Br
        c.set(AtomIdx(2), Point3::new(-0.374767, 1.560598, 0.764440)); // Cl
        c.set(AtomIdx(3), Point3::new(-0.129589, 0.278956, -1.439801)); // F
        c.set(AtomIdx(4), Point3::new(1.878920, -0.602486, 0.362108)); // I
        c
    }

    /// RDKit-confirmed coordinates for `[C@@](Br)(Cl)(F)I` (declared `@@` / S).
    fn rdkit_quaternary_cw_coords(m: &Molecule) -> Coords3D {
        let mut c = Coords3D::new_zeroed(m.atom_count());
        c.set(AtomIdx(0), Point3::new(-0.040296, 0.057521, 0.101297)); // C
        c.set(AtomIdx(1), Point3::new(-1.320960, -1.308229, -0.418469)); // Br
        c.set(AtomIdx(2), Point3::new(-0.376115, 1.549123, -0.786792)); // Cl
        c.set(AtomIdx(3), Point3::new(-0.150489, 0.294049, 1.434755)); // F
        c.set(AtomIdx(4), Point3::new(1.887860, -0.592463, -0.330791)); // I
        c
    }

    #[test]
    fn tetrahedral_matches_rdkit_quaternary_ccw() {
        let m = mol("[C@](Br)(Cl)(F)I");
        let coords = rdkit_quaternary_ccw_coords(&m);
        let report = verify_stereo(&m, &coords);
        assert_eq!(report.tetrahedral.len(), 1);
        assert_eq!(
            report.tetrahedral[0].status,
            StereoStatus::Satisfied,
            "RDKit confirmed this geometry reproduces declared `@` -- must be Satisfied"
        );
    }

    #[test]
    fn tetrahedral_matches_rdkit_quaternary_cw() {
        let m = mol("[C@@](Br)(Cl)(F)I");
        let coords = rdkit_quaternary_cw_coords(&m);
        let report = verify_stereo(&m, &coords);
        assert_eq!(
            report.tetrahedral[0].status,
            StereoStatus::Satisfied,
            "RDKit confirmed this geometry reproduces declared `@@` -- must be Satisfied"
        );
    }

    #[test]
    fn tetrahedral_rdkit_quaternary_flips_for_opposite_declared_tag() {
        // Same RDKit-confirmed-correct-for-`@` coordinates, but paired with the
        // OPPOSITE declared tag (`@@`) -> must read Violated. Proves the predicate
        // discriminates rather than always returning Satisfied.
        let m_wrong_tag = mol("[C@@](Br)(Cl)(F)I");
        let coords = rdkit_quaternary_ccw_coords(&m_wrong_tag);
        let report = verify_stereo(&m_wrong_tag, &coords);
        assert_eq!(report.tetrahedral[0].status, StereoStatus::Violated);
    }

    #[test]
    fn tetrahedral_swapped_rdkit_coords_violate() {
        // Swapping two substituent positions in an RDKit-confirmed-correct geometry
        // is a mechanically guaranteed sign flip (odd permutation of the signed-
        // volume arguments), independent of any CCW/CW framing -- must be Violated.
        let m = mol("[C@](Br)(Cl)(F)I");
        let mut coords = rdkit_quaternary_ccw_coords(&m);
        let p1 = coords.get(AtomIdx(1));
        let p2 = coords.get(AtomIdx(2));
        coords.set(AtomIdx(1), p2);
        coords.set(AtomIdx(2), p1);
        let report = verify_stereo(&m, &coords);
        assert_eq!(report.tetrahedral[0].status, StereoStatus::Violated);
    }

    // -------------------------------------------------------------------------
    // Implicit-H (phantom) tetrahedral verification
    // -------------------------------------------------------------------------

    #[test]
    fn implicit_h_stereocenter_evaluable_and_direction_sensitive() {
        // L-alanine: N[C@@H](C)C(=O)O -- 3 heavy neighbors + 1 implicit H at atom 1.
        // Coordinates: RDKit ETKDGv3-embedded, MMFF-optimized (all-atom, heavy atoms
        // only used below -- Coords3D is heavy-atom-only), confirmed by RDKit's own
        // `Chem.AssignStereochemistryFrom3D` to reproduce the declared `@@` (S)
        // configuration. This is the ground truth this test checks against -- not a
        // hand-derived phantom-position computation (which independently reproduced
        // the same inverted sign this module's core predicate had, see PR body).
        let m = mol("N[C@@H](C)C(=O)O");
        let idx = AtomIdx(1);
        assert_ne!(m.atom(idx).chirality, Chirality::None);
        assert_eq!(chematic_core::implicit_hcount(&m, idx), 1);

        let order = m.stereo_neighbor_order(idx).expect("stereo order recorded");
        assert_eq!(order.len(), 4);
        assert_eq!(order.iter().filter(|&&n| n == STEREO_H_SENTINEL).count(), 1);

        let mut coords = Coords3D::new_zeroed(m.atom_count());
        coords.set(AtomIdx(0), Point3::new(-1.029655, -1.350290, 0.249121)); // N
        coords.set(idx, Point3::new(-0.278484, -0.251876, -0.400037)); // C (stereocenter)
        coords.set(AtomIdx(2), Point3::new(-0.983462, 1.068581, -0.122130)); // C (methyl)
        coords.set(AtomIdx(3), Point3::new(1.164492, -0.221382, 0.114110)); // C (carboxyl)
        coords.set(AtomIdx(4), Point3::new(1.656783, -0.980050, 0.936364)); // O
        coords.set(AtomIdx(5), Point3::new(1.916290, 0.736776, -0.462302)); // O

        let report = verify_stereo(&m, &coords);
        let status = report
            .tetrahedral
            .iter()
            .find(|r| r.atom == idx)
            .unwrap()
            .status;
        assert_eq!(
            status,
            StereoStatus::Satisfied,
            "RDKit confirmed this geometry reproduces declared `@@` -- must be Satisfied, got {status:?}"
        );

        // Swapping two real substituent positions is a mechanically guaranteed sign
        // flip (odd permutation) -- must read Violated, proving the phantom-H
        // placement is actually direction-sensitive rather than degenerate/ignored.
        let mut coords2 = coords.clone();
        let p2 = coords2.get(AtomIdx(2));
        let p3 = coords2.get(AtomIdx(3));
        coords2.set(AtomIdx(2), p3);
        coords2.set(AtomIdx(3), p2);
        let report2 = verify_stereo(&m, &coords2);
        let status2 = report2
            .tetrahedral
            .iter()
            .find(|r| r.atom == idx)
            .unwrap()
            .status;
        assert_eq!(
            status2,
            StereoStatus::Violated,
            "swapping two real substituents must flip the verdict to Violated, got {status2:?}"
        );
    }

    #[test]
    fn implicit_h_stereocenter_matches_rdkit_ccw_tag() {
        // D-alanine: N[C@H](C)C(=O)O -- the `@` enantiomer of the fixture above.
        // Coordinates: RDKit-embedded/optimized, confirmed by
        // `Chem.AssignStereochemistryFrom3D` to reproduce declared `@` (R).
        let m = mol("N[C@H](C)C(=O)O");
        let idx = AtomIdx(1);
        let mut coords = Coords3D::new_zeroed(m.atom_count());
        coords.set(AtomIdx(0), Point3::new(-0.971481, -1.291400, -0.412620)); // N
        coords.set(idx, Point3::new(-0.243156, -0.218233, 0.293903)); // C (stereocenter)
        coords.set(AtomIdx(2), Point3::new(-0.879928, 1.117632, -0.065974)); // C (methyl)
        coords.set(AtomIdx(3), Point3::new(1.248347, -0.278606, -0.063537)); // C (carboxyl)
        coords.set(AtomIdx(4), Point3::new(1.861530, -1.270589, -0.432974)); // O
        coords.set(AtomIdx(5), Point3::new(1.911932, 0.873994, 0.154466)); // O

        let report = verify_stereo(&m, &coords);
        let status = report
            .tetrahedral
            .iter()
            .find(|r| r.atom == idx)
            .unwrap()
            .status;
        assert_eq!(
            status,
            StereoStatus::Satisfied,
            "RDKit confirmed this geometry reproduces declared `@` -- must be Satisfied, got {status:?}"
        );
    }

    #[test]
    fn unsupported_coordination_is_named_not_silently_dropped() {
        // Same molecule/geometry as above, but corrupt the count by using a
        // 2-heavy-neighbor atom with declared chirality is not constructible via
        // normal parsing; instead exercise the bond-order gate: an atom with a
        // double bond among its neighbors and (hypothetically) chirality set is
        // out of scope. Since real SMILES won't produce that combination easily,
        // this test instead checks the length/sentinel-count gate directly via a
        // molecule with a genuinely degenerate implicit-H count mismatch is hard to
        // construct from SMILES too -- so this test asserts the *documented*
        // behavior via the public API on a case that legitimately can't be built:
        // fewer than 4 total (heavy + implicit H) substituents.
        // `[C@H](F)Cl` has only 3 total substituents (F, Cl, + 1 H = 3, not 4).
        let m = mol("[C@H](F)Cl");
        let coords = Coords3D::new_zeroed(m.atom_count());
        let report = verify_stereo(&m, &coords);
        assert_eq!(report.tetrahedral.len(), 1);
        assert_eq!(
            report.tetrahedral[0].status,
            StereoStatus::Unevaluable(StereoRejectionReason::UnsupportedCoordination)
        );
    }

    /// Regression for the bug this PR fixes: a `SquarePlanar`-tagged center
    /// must never be coerced into a tetrahedral chiral-volume check. Before
    /// the fix, `tetrahedral_constraint_for`'s only guard was
    /// `debug_assert!(atom.chirality != Chirality::None)` -- a release-mode
    /// no-op that's also wrong even in debug, since `SquarePlanar` is also
    /// `!= None`. `requires_negative_volume: atom.chirality ==
    /// Chirality::CounterClockwise` is then always `false` for a
    /// `SquarePlanar` atom, silently treating it as a declared `@@`
    /// tetrahedral center and deciding Satisfied/Violated by
    /// `VOLUME_EPS = 1e-6` noise -- reachable via ordinary (non-dative)
    /// square-planar SMILES like `[Pt@SP1](Cl)(Cl)(N)N`, since plain SMILES
    /// bonds parse as `BondOrder::Single` and pass this function's own
    /// dative-bond exemption.
    ///
    /// Coordinates are deliberately puckered (z = +-0.05, not exactly
    /// coplanar) so `|signed_volume|` clears `VOLUME_EPS` -- with perfectly
    /// planar/zeroed coordinates the pre-fix code would degrade to
    /// `DegenerateGeometry` anyway, which would make this test pass for the
    /// wrong reason (never exercising the actual mis-coercion into a
    /// confident tetrahedral verdict).
    ///
    /// This is the full assertion chain for the bug, not just the
    /// `Unevaluable` verdict in isolation: (1) `tetrahedral_constraint_for`
    /// itself -- the exact function that had the bug -- rejects the atom as
    /// `UnsupportedCoordination`, i.e. it is not even a *candidate*
    /// tetrahedral center, not just one that later fails a geometry check;
    /// (2) `verify_stereo`'s public report reflects that same rejection,
    /// never `Satisfied`/`Violated`; (3) `chematic_chem::assign_cip` (a
    /// different crate, exercising a completely different code path)
    /// independently agrees the atom gets no CIP code at all -- the same
    /// property `chematic-chem/src/cip.rs`'s
    /// `square_planar_center_never_gets_a_bogus_tetrahedral_cip_code` and
    /// `chematic-cip/src/tests.rs`'s
    /// `square_planar_center_is_skipped_not_assigned_a_bogus_cip_code`
    /// already prove independently for the CIP layer specifically -- this
    /// test cross-checks the same invariant from the 3D-stereo-verification
    /// side; (4) the atom's stored `Chirality::SquarePlanar` value is
    /// unchanged after all of the above -- true by construction, not just
    /// by observation: `verify_stereo`, `repair_stereo`, and `assign_cip`
    /// all take `mol: &Molecule` (an immutable reference), so none of them
    /// can mutate `Chirality` even in principle: the borrow checker rules
    /// it out at compile time, this assertion just makes that guarantee
    /// visible in the test.
    #[test]
    fn square_planar_center_is_never_coerced_into_a_tetrahedral_chiral_volume_check() {
        let m = mol("[Pt@SP1](Cl)(Cl)(N)N");
        let pt = (0..m.atom_count())
            .map(|i| AtomIdx(i as u32))
            .find(|&i| m.atom(i).element == chematic_core::Element::PT)
            .expect("fixture has a Pt atom");
        let original_chirality = m.atom(pt).chirality;
        assert!(
            matches!(original_chirality, Chirality::SquarePlanar(_)),
            "fixture must actually carry a SquarePlanar tag"
        );

        // (1) Not even a tetrahedral *candidate* -- the exact function this
        // PR's guard was added to.
        assert_eq!(
            tetrahedral_constraint_for(&m, pt),
            Err(StereoRejectionReason::UnsupportedCoordination),
            "a square-planar center must be rejected as a tetrahedral candidate outright"
        );

        let mut coords = Coords3D::new_zeroed(m.atom_count());
        coords.set(pt, Point3::new(0.0, 0.0, 0.0));
        let order = m
            .stereo_neighbor_order(pt)
            .expect("square-planar center has a recorded neighbor order")
            .to_vec();
        // Deliberately asymmetric z-offsets (not a +/- mirror pattern) so
        // the resulting signed volume can't accidentally cancel to exactly
        // zero by symmetry -- verified directly below via the module's own
        // `signed_volume`/`tetrahedral_positions`, not just assumed.
        let puckered = [
            Point3::new(1.0, 0.0, 0.05),
            Point3::new(-1.0, 0.0, -0.03),
            Point3::new(0.0, 1.0, 0.07),
            Point3::new(0.0, -1.0, -0.02),
        ];
        for (&nb, &p) in order.iter().zip(puckered.iter()) {
            coords.set(AtomIdx(nb), p);
        }

        // Confirm this geometry is genuinely non-degenerate for a
        // tetrahedral-style volume check -- i.e. the pre-fix code, absent
        // this PR's guard, would have reached a confident Satisfied/Violated
        // verdict here, not fallen through to `DegenerateGeometry` for an
        // unrelated reason. This is what makes the assertion below a real
        // test of the guard, not a test of degenerate-geometry handling.
        let order_arr: [u32; 4] = order.clone().try_into().unwrap();
        let positions = tetrahedral_positions(&coords, pt, &order_arr).unwrap();
        let volume = signed_volume(positions[1], positions[2], positions[3], positions[0]);
        assert!(
            volume.abs() > VOLUME_EPS,
            "fixture must be non-degenerate (|volume|={} must exceed VOLUME_EPS={VOLUME_EPS}) \
             for this to be a real test of the coercion guard",
            volume.abs()
        );

        // (2) `verify_stereo`'s public report agrees.
        let report = verify_stereo(&m, &coords);
        let status = report
            .tetrahedral
            .iter()
            .find(|r| r.atom == pt)
            .expect("Pt center must still appear in the report")
            .status;
        assert_eq!(
            status,
            StereoStatus::Unevaluable(StereoRejectionReason::UnsupportedCoordination),
            "a square-planar center must never be evaluated as tetrahedral, got {status:?}"
        );
        assert!(!status.is_satisfied() && !status.is_violated());

        // (3) An independent crate/code path (chematic-chem's CIP engine,
        // not this module) agrees: no CIP code at all for this atom. Same
        // property `chematic-chem/src/cip.rs`'s
        // `square_planar_center_never_gets_a_bogus_tetrahedral_cip_code`
        // proves for the CIP layer in isolation; asserted again here so the
        // 3D-stereo-verification side and the CIP side are checked against
        // each other in one place, not just independently.
        assert_eq!(
            chematic_chem::assign_cip(&m).get(pt),
            None,
            "a square-planar center must never receive a tetrahedral CIP code"
        );

        // (4) The stored `Chirality` is byte-for-byte unchanged. Every
        // function called above takes `&Molecule`, so this is guaranteed by
        // the borrow checker, not just by these functions' current
        // implementations -- this assertion exists to make that guarantee
        // visible and regression-checked, not because it was ever in doubt.
        assert_eq!(
            m.atom(pt).chirality,
            original_chirality,
            "a square-planar center's declared Chirality must never be mutated by verification"
        );
    }

    // -------------------------------------------------------------------------
    // Degenerate geometry
    // -------------------------------------------------------------------------

    #[test]
    fn coplanar_neighbors_is_degenerate_not_silently_satisfied() {
        let m = mol("[C@](Br)(Cl)(F)I");
        let order = m.stereo_neighbor_order(AtomIdx(0)).unwrap();
        let mut coords = Coords3D::new_zeroed(m.atom_count());
        coords.set(AtomIdx(0), Point3::new(0.0, 0.0, 0.0));
        // All 4 substituents coplanar (z=0) -> degenerate signed volume.
        coords.set(AtomIdx(order[0]), Point3::new(1.0, 0.0, 0.0));
        coords.set(AtomIdx(order[1]), Point3::new(-1.0, 0.0, 0.0));
        coords.set(AtomIdx(order[2]), Point3::new(0.0, 1.0, 0.0));
        coords.set(AtomIdx(order[3]), Point3::new(0.0, -1.0, 0.0));

        let report = verify_stereo(&m, &coords);
        assert_eq!(
            report.tetrahedral[0].status,
            StereoStatus::Unevaluable(StereoRejectionReason::DegenerateGeometry)
        );
    }

    // -------------------------------------------------------------------------
    // E/Z verification
    // -------------------------------------------------------------------------

    fn trans_but2ene_coords(m: &Molecule) -> Coords3D {
        // C/C=C/C: atom0=C(methyl), atom1=C(alkene), atom2=C(alkene), atom3=C(methyl).
        let mut c = Coords3D::new_zeroed(m.atom_count());
        c.set(AtomIdx(0), Point3::new(-1.5, 0.5, 0.0));
        c.set(AtomIdx(1), Point3::new(-0.67, 0.0, 0.0));
        c.set(AtomIdx(2), Point3::new(0.67, 0.0, 0.0));
        c.set(AtomIdx(3), Point3::new(1.5, -0.5, 0.0)); // opposite side -> trans/E
        c
    }

    fn cis_but2ene_coords(m: &Molecule) -> Coords3D {
        let mut c = Coords3D::new_zeroed(m.atom_count());
        c.set(AtomIdx(0), Point3::new(-1.5, 0.5, 0.0));
        c.set(AtomIdx(1), Point3::new(-0.67, 0.0, 0.0));
        c.set(AtomIdx(2), Point3::new(0.67, 0.0, 0.0));
        c.set(AtomIdx(3), Point3::new(1.5, 0.5, 0.0)); // same side -> cis/Z
        c
    }

    #[test]
    fn ez_declared_e_matches_trans_geometry() {
        let m = mol("C/C=C/C"); // but2ene_E
        let coords = trans_but2ene_coords(&m);
        let report = verify_stereo(&m, &coords);
        assert_eq!(report.double_bond.len(), 1);
        assert_eq!(report.double_bond[0].status, StereoStatus::Satisfied);
    }

    #[test]
    fn ez_declared_e_violated_by_cis_geometry() {
        let m = mol("C/C=C/C"); // but2ene_E, declared trans
        let coords = cis_but2ene_coords(&m); // but built cis
        let report = verify_stereo(&m, &coords);
        assert_eq!(report.double_bond[0].status, StereoStatus::Violated);
    }

    #[test]
    fn ez_matches_rdkit_e_and_z() {
        // Independent check against RDKit (ETKDGv3-embedded, MMFF-optimized,
        // confirmed by `Chem.AssignStereochemistryFrom3D` to reproduce the declared
        // E/Z bond stereo) -- not just the hand-built dihedral fixtures above.
        let m_e = mol("C/C=C/C");
        let mut c_e = Coords3D::new_zeroed(m_e.atom_count());
        c_e.set(AtomIdx(0), Point3::new(1.949328, 0.033766, 0.369285));
        c_e.set(AtomIdx(1), Point3::new(0.529189, -0.230326, 0.751313));
        c_e.set(AtomIdx(2), Point3::new(-0.529189, 0.230328, 0.067504));
        c_e.set(AtomIdx(3), Point3::new(-1.949328, -0.033765, 0.449532));
        assert_eq!(
            verify_stereo(&m_e, &c_e).double_bond[0].status,
            StereoStatus::Satisfied,
            "RDKit confirmed this geometry reproduces declared E"
        );

        let m_z = mol(r"C/C=C\C");
        let mut c_z = Coords3D::new_zeroed(m_z.atom_count());
        c_z.set(AtomIdx(0), Point3::new(1.550829, 0.471766, 0.248193));
        c_z.set(AtomIdx(1), Point3::new(0.731718, -0.628075, -0.345406));
        c_z.set(AtomIdx(2), Point3::new(-0.606159, -0.726762, -0.391896));
        c_z.set(AtomIdx(3), Point3::new(-1.616617, 0.238123, 0.138127));
        assert_eq!(
            verify_stereo(&m_z, &c_z).double_bond[0].status,
            StereoStatus::Satisfied,
            "RDKit confirmed this geometry reproduces declared Z"
        );

        // Cross-wiring (Z-declared molecule + E-shaped geometry) must violate.
        let mut c_wrong = Coords3D::new_zeroed(m_z.atom_count());
        c_wrong.set(AtomIdx(0), Point3::new(1.949328, 0.033766, 0.369285));
        c_wrong.set(AtomIdx(1), Point3::new(0.529189, -0.230326, 0.751313));
        c_wrong.set(AtomIdx(2), Point3::new(-0.529189, 0.230328, 0.067504));
        c_wrong.set(AtomIdx(3), Point3::new(-1.949328, -0.033765, 0.449532));
        assert_eq!(
            verify_stereo(&m_z, &c_wrong).double_bond[0].status,
            StereoStatus::Violated
        );
    }

    #[test]
    fn ez_declared_z_matches_cis_geometry() {
        let m = mol(r"C/C=C\C"); // but2ene_Z
        let coords = cis_but2ene_coords(&m);
        let report = verify_stereo(&m, &coords);
        assert_eq!(report.double_bond[0].status, StereoStatus::Satisfied);
    }

    #[test]
    fn ez_declared_z_violated_by_trans_geometry() {
        let m = mol(r"C/C=C\C"); // but2ene_Z, declared cis
        let coords = trans_but2ene_coords(&m);
        let report = verify_stereo(&m, &coords);
        assert_eq!(report.double_bond[0].status, StereoStatus::Violated);
    }

    #[test]
    fn no_declared_ez_is_not_reported_at_all() {
        let m = mol("CC=CC"); // plain 2-butene, no direction markers
        let coords = trans_but2ene_coords(&m);
        let report = verify_stereo(&m, &coords);
        assert!(report.double_bond.is_empty());
    }

    #[test]
    fn carbonyl_adjacent_to_marked_alkene_is_not_spuriously_reported() {
        // Regression test for a real bug found via examples/stereo_constraints_gap_check.rs:
        // the carbonyl C=O in `OC(=O)/C=C/c1ccccc1` (cinnamic acid) was being
        // misreported as "has declared E/Z" because its carbon is directly bonded to
        // the alkene carbon carrying that alkene's OWN `/` marker -- a cross-
        // contamination between two adjacent double bonds sharing a connector bond.
        // The carbonyl (terminal on the =O end) must not appear in the report at
        // all, and the real alkene bond must still be correctly evaluated.
        let m = mol(r"OC(=O)/C=C/c1ccccc1");
        let mut coords = Coords3D::new_zeroed(m.atom_count());
        coords.set(AtomIdx(1), Point3::new(-1.5, 0.5, 0.0));
        coords.set(AtomIdx(3), Point3::new(-0.67, 0.0, 0.0));
        coords.set(AtomIdx(4), Point3::new(0.67, 0.0, 0.0));
        coords.set(AtomIdx(5), Point3::new(1.5, -0.5, 0.0)); // trans -> declared E, matches

        let report = verify_stereo(&m, &coords);
        assert_eq!(
            report.double_bond.len(),
            1,
            "only the real alkene bond should be reported, not the adjacent carbonyl: {:?}",
            report.double_bond
        );
        assert_eq!(report.double_bond[0].status, StereoStatus::Satisfied);
    }

    // -------------------------------------------------------------------------
    // Repair: tetrahedral
    // -------------------------------------------------------------------------

    #[test]
    fn repair_tetrahedral_fixes_violation_without_moving_other_atoms() {
        let m = mol("[C@](Br)(Cl)(F)I");
        // Swap two substituents in the RDKit-confirmed-correct geometry -> a
        // mechanically guaranteed sign flip (odd permutation), i.e. a genuine
        // violation to repair.
        let mut coords = rdkit_quaternary_ccw_coords(&m);
        let p1 = coords.get(AtomIdx(1));
        let p2 = coords.get(AtomIdx(2));
        coords.set(AtomIdx(1), p2);
        coords.set(AtomIdx(2), p1);

        let before = verify_stereo(&m, &coords);
        assert_eq!(before.tetrahedral[0].status, StereoStatus::Violated);

        let outcome = repair_stereo(&m, &coords).expect("repair should succeed");
        assert_eq!(outcome.repaired.len(), 1);

        let after = verify_stereo(&m, &outcome.coords);
        assert_eq!(after.tetrahedral[0].status, StereoStatus::Satisfied);

        // Exactly one atom should have moved (a quaternary center's substituent has
        // no further subtree), and the center itself must not have moved.
        assert_eq!(outcome.repaired[0].atoms_moved, 1);
        assert_eq!(outcome.coords.get(AtomIdx(0)), coords.get(AtomIdx(0)));
    }

    #[test]
    fn repair_preserves_bond_length_to_center() {
        let m = mol("[C@](Br)(Cl)(F)I");
        let mut coords = rdkit_quaternary_ccw_coords(&m);
        let p1 = coords.get(AtomIdx(1));
        let p2 = coords.get(AtomIdx(2));
        coords.set(AtomIdx(1), p2);
        coords.set(AtomIdx(2), p1);
        assert_eq!(
            verify_stereo(&m, &coords).tetrahedral[0].status,
            StereoStatus::Violated,
            "this test exercises the actual-repair path, not the no-op path"
        );

        let order = m.stereo_neighbor_order(AtomIdx(0)).unwrap().to_vec();
        let before_lengths: Vec<f64> = order
            .iter()
            .map(|&n| coords.get(AtomIdx(0)).distance(&coords.get(AtomIdx(n))))
            .collect();

        let outcome = repair_stereo(&m, &coords).expect("repair should succeed");
        let after_lengths: Vec<f64> = order
            .iter()
            .map(|&n| {
                outcome
                    .coords
                    .get(AtomIdx(0))
                    .distance(&outcome.coords.get(AtomIdx(n)))
            })
            .collect();

        for (b, a) in before_lengths.iter().zip(after_lengths.iter()) {
            assert!(
                (b - a).abs() < 1e-9,
                "bond length to center must be preserved: {b} vs {a}"
            );
        }
    }

    #[test]
    fn repair_is_noop_success_when_already_satisfied() {
        let m = mol("[C@](Br)(Cl)(F)I");
        let coords = rdkit_quaternary_ccw_coords(&m); // RDKit-confirmed already correct
        assert_eq!(
            verify_stereo(&m, &coords).tetrahedral[0].status,
            StereoStatus::Satisfied
        );

        let outcome = repair_stereo(&m, &coords).expect("already satisfied -> ok");
        assert!(outcome.repaired.is_empty());
        for i in 0..m.atom_count() {
            assert_eq!(
                outcome.coords.get(AtomIdx(i as u32)),
                coords.get(AtomIdx(i as u32))
            );
        }
    }

    // -------------------------------------------------------------------------
    // Repair: E/Z
    // -------------------------------------------------------------------------

    #[test]
    fn repair_ez_fixes_violation() {
        let m = mol("C/C=C/C"); // declared E (trans)
        let coords = cis_but2ene_coords(&m); // built cis -> violated

        let before = verify_stereo(&m, &coords);
        assert_eq!(before.double_bond[0].status, StereoStatus::Violated);

        let outcome = repair_stereo(&m, &coords).expect("repair should succeed");
        let after = verify_stereo(&m, &outcome.coords);
        assert_eq!(after.double_bond[0].status, StereoStatus::Satisfied);
    }

    #[test]
    fn repair_ez_preserves_bond_lengths_within_rotated_group() {
        let m = mol("C/C=C/C");
        let coords = cis_but2ene_coords(&m);
        let before_len = coords.get(AtomIdx(2)).distance(&coords.get(AtomIdx(3)));

        let outcome = repair_stereo(&m, &coords).expect("repair should succeed");
        let after_len = outcome
            .coords
            .get(AtomIdx(2))
            .distance(&outcome.coords.get(AtomIdx(3)));
        assert!((before_len - after_len).abs() < 1e-9);
    }

    // -------------------------------------------------------------------------
    // Ring-bridge safety: a ring-fused stereocenter with no safe exocyclic
    // substituent should fail closed, not corrupt the ring.
    // -------------------------------------------------------------------------

    #[test]
    fn bridge_component_rejects_ring_closing_path() {
        // A 4-membered ring where every neighbor of atom 0 eventually loops back:
        // bridge_component from one ring neighbor, forbidding the other, must
        // detect the loop and return None.
        let m = mol("C1CCC1");
        // atom0's neighbors are atom1 and atom3 (ring). BFS from atom1, blocked=atom0,
        // forbidden=[atom3] must reach atom3 via atom1->atom2->atom3.
        let result = bridge_component(&m, &[AtomIdx(1)], AtomIdx(0), &[AtomIdx(3)]);
        assert!(
            result.is_none(),
            "ring-closing path must be detected, not treated as a bridge"
        );
    }

    #[test]
    fn bridge_component_accepts_genuine_branch() {
        // Butane: atom0-atom1-atom2-atom3, no ring. BFS from atom0 (blocked=atom1,
        // forbidden=[]) must succeed trivially (atom0 is a genuine leaf branch).
        let m = mol("CCCC");
        let result = bridge_component(&m, &[AtomIdx(0)], AtomIdx(1), &[]);
        assert!(result.is_some());
        assert_eq!(
            result.unwrap(),
            [AtomIdx(0)].into_iter().collect::<HashSet<_>>()
        );
    }

    // -------------------------------------------------------------------------
    // build_stereo_constraints: drift guards against verify_stereo /
    // RDKit-confirmed geometry -- the constraint set and the verifier must never
    // disagree about what's declared, checked directly rather than assumed from
    // both calling the same extraction functions.
    // -------------------------------------------------------------------------

    #[test]
    fn constraint_set_tetrahedral_quaternary_ccw_matches_rdkit_geometry() {
        let m = mol("[C@](Br)(Cl)(F)I");
        let coords = rdkit_quaternary_ccw_coords(&m);
        let set = build_stereo_constraints(&m);
        assert_eq!(set.tetrahedral.len(), 1);
        assert!(set.double_bond.is_empty());
        assert!(set.unsupported.is_empty());
        let c = &set.tetrahedral[0];
        assert_eq!(c.atom, AtomIdx(0));

        // Independently recompute the actual sign from the RDKit-confirmed
        // geometry (not just trusting verify_stereo's verdict) and check it
        // agrees with what the constraint requires.
        let positions = tetrahedral_positions(&coords, c.atom, &c.order).unwrap();
        let volume = signed_volume(positions[1], positions[2], positions[3], positions[0]);
        assert!(volume < 0.0, "RDKit-confirmed @ geometry must be negative");
        assert!(
            c.requires_negative_volume,
            "constraint for declared @ must require negative volume"
        );
        assert_eq!(
            verify_stereo(&m, &coords).tetrahedral[0].status,
            StereoStatus::Satisfied
        );
    }

    #[test]
    fn constraint_set_tetrahedral_quaternary_cw_matches_rdkit_geometry() {
        let m = mol("[C@@](Br)(Cl)(F)I");
        let coords = rdkit_quaternary_cw_coords(&m);
        let set = build_stereo_constraints(&m);
        let c = &set.tetrahedral[0];

        let positions = tetrahedral_positions(&coords, c.atom, &c.order).unwrap();
        let volume = signed_volume(positions[1], positions[2], positions[3], positions[0]);
        assert!(volume > 0.0, "RDKit-confirmed @@ geometry must be positive");
        assert!(
            !c.requires_negative_volume,
            "constraint for declared @@ must require positive (not negative) volume"
        );
        assert_eq!(
            verify_stereo(&m, &coords).tetrahedral[0].status,
            StereoStatus::Satisfied
        );
    }

    #[test]
    fn constraint_set_implicit_h_stereocenter_matches_rdkit_geometry() {
        // L-alanine: N[C@@H](C)C(=O)O -- exercises the STEREO_H_SENTINEL slot.
        let m = mol("N[C@@H](C)C(=O)O");
        let idx = AtomIdx(1);
        let mut coords = Coords3D::new_zeroed(m.atom_count());
        coords.set(AtomIdx(0), Point3::new(-1.029655, -1.350290, 0.249121));
        coords.set(idx, Point3::new(-0.278484, -0.251876, -0.400037));
        coords.set(AtomIdx(2), Point3::new(-0.983462, 1.068581, -0.122130));
        coords.set(AtomIdx(3), Point3::new(1.164492, -0.221382, 0.114110));
        coords.set(AtomIdx(4), Point3::new(1.656783, -0.980050, 0.936364));
        coords.set(AtomIdx(5), Point3::new(1.916290, 0.736776, -0.462302));

        let set = build_stereo_constraints(&m);
        let c = set
            .tetrahedral
            .iter()
            .find(|c| c.atom == idx)
            .expect("declared stereocenter must appear in the constraint set");
        assert!(
            c.order.contains(&STEREO_H_SENTINEL),
            "implicit-H stereocenter's constraint order must carry the sentinel"
        );

        let positions = tetrahedral_positions(&coords, c.atom, &c.order).unwrap();
        let volume = signed_volume(positions[1], positions[2], positions[3], positions[0]);
        let actual_negative = volume < 0.0;
        assert_eq!(
            actual_negative, c.requires_negative_volume,
            "constraint sign must agree with the RDKit-confirmed-Satisfied geometry"
        );
        assert_eq!(
            verify_stereo(&m, &coords)
                .tetrahedral
                .iter()
                .find(|r| r.atom == idx)
                .unwrap()
                .status,
            StereoStatus::Satisfied
        );
    }

    #[test]
    fn constraint_set_ez_e_and_z_match_rdkit_geometry() {
        let m_e = mol("C/C=C/C");
        let mut c_e = Coords3D::new_zeroed(m_e.atom_count());
        c_e.set(AtomIdx(0), Point3::new(1.949328, 0.033766, 0.369285));
        c_e.set(AtomIdx(1), Point3::new(0.529189, -0.230326, 0.751313));
        c_e.set(AtomIdx(2), Point3::new(-0.529189, 0.230328, 0.067504));
        c_e.set(AtomIdx(3), Point3::new(-1.949328, -0.033765, 0.449532));

        let set_e = build_stereo_constraints(&m_e);
        assert_eq!(set_e.double_bond.len(), 1);
        let ce = &set_e.double_bond[0];
        let angle = crate::stereo3d::dihedral(
            c_e.get(ce.end1),
            c_e.get(ce.end2),
            c_e.get(ce.sub1),
            c_e.get(ce.sub2),
        )
        .unwrap();
        let actual_same_side = angle.abs() < std::f64::consts::FRAC_PI_2;
        assert_eq!(
            actual_same_side, ce.same_side,
            "constraint's same_side must agree with the RDKit-confirmed-E geometry"
        );
        assert_eq!(
            verify_stereo(&m_e, &c_e).double_bond[0].status,
            StereoStatus::Satisfied
        );

        let m_z = mol(r"C/C=C\C");
        let mut c_z = Coords3D::new_zeroed(m_z.atom_count());
        c_z.set(AtomIdx(0), Point3::new(1.550829, 0.471766, 0.248193));
        c_z.set(AtomIdx(1), Point3::new(0.731718, -0.628075, -0.345406));
        c_z.set(AtomIdx(2), Point3::new(-0.606159, -0.726762, -0.391896));
        c_z.set(AtomIdx(3), Point3::new(-1.616617, 0.238123, 0.138127));

        let set_z = build_stereo_constraints(&m_z);
        let cz = &set_z.double_bond[0];
        let angle_z = crate::stereo3d::dihedral(
            c_z.get(cz.end1),
            c_z.get(cz.end2),
            c_z.get(cz.sub1),
            c_z.get(cz.sub2),
        )
        .unwrap();
        let actual_same_side_z = angle_z.abs() < std::f64::consts::FRAC_PI_2;
        assert_eq!(
            actual_same_side_z, cz.same_side,
            "constraint's same_side must agree with the RDKit-confirmed-Z geometry"
        );
        // E and Z constraints for the two enantiomeric-direction molecules must
        // disagree with each other -- proves same_side is discriminating, not a
        // constant.
        assert_ne!(ce.same_side, cz.same_side);
    }

    #[test]
    fn constraint_set_ordering_regression_carbonyl_adjacent_to_marked_alkene() {
        // Same molecule as the verify_stereo regression test above
        // (`carbonyl_adjacent_to_marked_alkene_is_not_spuriously_reported`): the
        // carbonyl C=O in cinnamic acid must produce NEITHER a constraint NOR an
        // `unsupported` entry -- it must not appear in the set at all, preserving
        // the same has_real_substituent-before-marker-scan check order that fix
        // depends on.
        let m = mol(r"OC(=O)/C=C/c1ccccc1");
        let set = build_stereo_constraints(&m);
        assert_eq!(
            set.double_bond.len(),
            1,
            "only the real alkene should produce a constraint: {:?}",
            set.double_bond
        );
        assert!(
            set.unsupported.is_empty(),
            "the carbonyl must not appear even as unsupported: {:?}",
            set.unsupported
        );
    }

    #[test]
    fn constraint_set_unsupported_tetrahedral_is_named_not_dropped() {
        // Same fixture as `unsupported_coordination_is_named_not_silently_dropped`:
        // `[C@H](F)Cl` has only 3 total substituents (F, Cl, + 1 H = 3, not 4).
        let m = mol("[C@H](F)Cl");
        let set = build_stereo_constraints(&m);
        assert!(set.tetrahedral.is_empty());
        assert_eq!(set.n_constraints(), 0);
        assert_eq!(
            set.unsupported,
            vec![(
                StereoElement::Tetrahedral(AtomIdx(0)),
                StereoRejectionReason::UnsupportedCoordination
            )]
        );
    }

    #[test]
    fn constraint_set_cumulated_diene_is_named_not_dropped() {
        // C/C=C=C/C: a substituted buta-1,2-diene (cumulated double bonds sharing
        // atom 2). Both double bonds carry direction markers and real substituents,
        // but neither is a simple isolated alkene -- must be reported as
        // TerminalOrCumulatedAlkene for both, not silently skipped and not treated
        // as a plain E/Z constraint (verified empirically against this exact
        // fixture before writing this assertion, not assumed).
        let m = mol("C/C=C=C/C");
        let set = build_stereo_constraints(&m);
        assert!(set.double_bond.is_empty());
        assert_eq!(set.unsupported.len(), 2);
        for (_, reason) in &set.unsupported {
            assert_eq!(*reason, StereoRejectionReason::TerminalOrCumulatedAlkene);
        }
    }

    #[test]
    fn constraint_set_ambiguous_direction_is_named_not_dropped() {
        // Only one alkene terminus carries a `/` marker; the other has two plain
        // substituents with no direction marker at all -- AmbiguousDirection, not
        // silently skipped (skipping is reserved for "no marker anywhere").
        let m = mol("C/C=C(C)C");
        let set = build_stereo_constraints(&m);
        assert!(set.double_bond.is_empty());
        assert_eq!(set.unsupported.len(), 1);
        assert_eq!(
            set.unsupported[0].1,
            StereoRejectionReason::AmbiguousDirection
        );
    }

    #[test]
    fn constraint_set_no_declared_stereo_is_empty_not_unsupported() {
        // Plain, fully unmarked molecule: must produce an empty set outright, not
        // a set full of `unsupported` entries -- "not declared" and "declared but
        // unsupported" must stay distinguishable everywhere in this module.
        let m = mol("CCCC");
        let set = build_stereo_constraints(&m);
        assert_eq!(set.n_constraints(), 0);
        assert!(set.unsupported.is_empty());
    }

    #[test]
    fn constraint_set_is_pure_function_of_molecule_no_coords_needed() {
        // Sanity check on the design itself: the same molecule always yields the
        // same constraint set regardless of how many times it's called -- there is
        // no hidden coordinate/geometry dependency anywhere in this code path.
        let m = mol("N[C@@H](C)C(=O)O");
        let set1 = build_stereo_constraints(&m);
        let set2 = build_stereo_constraints(&m);
        assert_eq!(set1.tetrahedral, set2.tetrahedral);
        assert_eq!(set1.double_bond, set2.double_bond);
        assert_eq!(set1.unsupported, set2.unsupported);
    }
}
