//! Regression tests: chematic property values vs RDKit reference (v0.1.1 baseline).
//!
//! Reference values generated by scripts/gen_rdkit_reference.py using RDKit 2024.x.
//!
//! Tolerances:
//!   MW:   ±0.01 Da   (average isotope masses; differences arise at ~4th decimal place)
//!   TPSA: ±5.0 Å²   (Ertl 2000 table; tighter for simple rings, wider for amide N)
//!   HAC:  ±0         (exact integer)
//!   HBD:  ±0         (exact integer)

use chematic_chem::descriptors::{
    molecular_weight, tpsa, heavy_atom_count, hbd_count, hba_count, logp_crippen, lipinski_passes,
    num_aromatic_heterocycles, num_aliphatic_heterocycles, num_saturated_heterocycles,
    num_spiro_atoms, num_bridgehead_atoms,
};
use chematic_smiles::parse;

fn mol(smi: &str) -> chematic_core::molecule::Molecule {
    parse(smi).unwrap_or_else(|e| panic!("parse({smi:?}) failed: {e}"))
}

fn assert_approx(label: &str, got: f64, expected: f64, tol: f64) {
    assert!(
        (got - expected).abs() <= tol,
        "{label}: got {got:.4}, expected {expected:.4} ±{tol}"
    );
}

// ── Molecular weight ─────────────────────────────────────────────────────────

#[test]
fn mw_aspirin() {
    // C9H8O4 — RDKit: 180.159
    assert_approx("MW aspirin", molecular_weight(&mol("CC(=O)Oc1ccccc1C(=O)O")), 180.159, 0.01);
}

#[test]
fn mw_caffeine() {
    // C8H10N4O2 — RDKit: 194.194
    assert_approx("MW caffeine", molecular_weight(&mol("Cn1cnc2c1c(=O)n(c(=O)n2C)C")), 194.194, 0.01);
}

#[test]
fn mw_indole() {
    // C8H7N — RDKit: 117.151
    assert_approx("MW indole", molecular_weight(&mol("c1ccc2[nH]ccc2c1")), 117.151, 0.01);
}

#[test]
fn mw_glucose() {
    // C6H12O6 — RDKit: 180.156
    assert_approx("MW glucose", molecular_weight(&mol("OC[C@H]1O[C@@H](O)[C@H](O)[C@@H](O)[C@@H]1O")), 180.156, 0.01);
}

#[test]
fn mw_lidocaine() {
    // C14H22N2O — RDKit: 234.338
    assert_approx("MW lidocaine", molecular_weight(&mol("CCN(CC)CC(=O)Nc1c(C)cccc1C")), 234.338, 0.01);
}

#[test]
fn mw_warfarin() {
    // Real warfarin: C19H16O4 — RDKit: 308.333
    assert_approx("MW warfarin", molecular_weight(&mol("CC(=O)CC(c1ccccc1)C1C(=O)c2ccccc2OC1=O")), 308.333, 0.01);
}

#[test]
fn mw_naproxen() {
    // C14H14O3 — RDKit: 230.259
    assert_approx("MW naproxen", molecular_weight(&mol("CC(C(=O)O)c1ccc2cc(OC)ccc2c1")), 230.259, 0.01);
}

#[test]
fn mw_methotrexate() {
    // C20H22N8O5 — RDKit: 454.447
    assert_approx("MW methotrexate",
        molecular_weight(&mol("CN(Cc1cnc2nc(N)nc(N)c2n1)c1ccc(cc1)C(=O)NC(CCC(=O)O)C(=O)O")),
        454.447, 0.01);
}

#[test]
fn mw_paracetamol() {
    // C8H9NO2 — RDKit: 151.163
    assert_approx("MW paracetamol", molecular_weight(&mol("CC(=O)Nc1ccc(O)cc1")), 151.163, 0.01);
}

#[test]
fn mw_ibuprofen() {
    // C13H18O2 — RDKit: 206.285
    assert_approx("MW ibuprofen", molecular_weight(&mol("CC(C)Cc1ccc(cc1)C(C)C(=O)O")), 206.285, 0.01);
}

#[test]
fn mw_glycine() {
    // C2H5NO2 — RDKit: 75.067
    assert_approx("MW glycine", molecular_weight(&mol("NCC(=O)O")), 75.067, 0.01);
}

#[test]
fn mw_benzene() {
    // C6H6 — RDKit: 78.114
    assert_approx("MW benzene", molecular_weight(&mol("c1ccccc1")), 78.114, 0.01);
}

#[test]
fn mw_naphthalene() {
    // C10H8 — RDKit: 128.174
    assert_approx("MW naphthalene", molecular_weight(&mol("c1ccc2ccccc2c1")), 128.174, 0.01);
}

// ── TPSA ─────────────────────────────────────────────────────────────────────

#[test]
fn tpsa_aspirin() {
    // RDKit: 63.60 Å²
    assert_approx("TPSA aspirin", tpsa(&mol("CC(=O)Oc1ccccc1C(=O)O")), 63.60, 1.0);
}

#[test]
fn tpsa_caffeine() {
    // RDKit: 61.82 Å²
    // Fix: aromatic N with deg≥3 (N-substituted) gets 4.93 (RDKit value), not 12.89.
    // 3 N-methyl/N-aryl @ 4.93 + 1 pyridine-type @ 12.89 + 2 C=O @ 17.07 = 61.82.
    assert_approx("TPSA caffeine", tpsa(&mol("Cn1cnc2c1c(=O)n(c(=O)n2C)C")), 61.82, 1.0);
}

#[test]
fn tpsa_paracetamol() {
    // RDKit: 49.33 Å²
    assert_approx("TPSA paracetamol", tpsa(&mol("CC(=O)Nc1ccc(O)cc1")), 49.33, 5.0);
}

#[test]
fn tpsa_lidocaine() {
    // RDKit: 32.34 Å² (amide N-H + tertiary N)
    assert_approx("TPSA lidocaine", tpsa(&mol("CCN(CC)CC(=O)Nc1c(C)cccc1C")), 32.34, 10.0);
}

#[test]
fn tpsa_glucose() {
    // RDKit: 110.38 Å²
    assert_approx("TPSA glucose",
        tpsa(&mol("OC[C@H]1O[C@@H](O)[C@H](O)[C@@H](O)[C@@H]1O")), 110.38, 1.0);
}

#[test]
fn tpsa_pyridine() {
    // RDKit: 12.89 Å²
    assert_approx("TPSA pyridine", tpsa(&mol("c1ccncc1")), 12.89, 0.1);
}

#[test]
fn tpsa_aniline() {
    // RDKit: 26.02 Å²
    assert_approx("TPSA aniline", tpsa(&mol("Nc1ccccc1")), 26.02, 0.1);
}

#[test]
fn tpsa_benzene() {
    // RDKit: 0.00 Å²
    assert_approx("TPSA benzene", tpsa(&mol("c1ccccc1")), 0.00, 0.01);
}

#[test]
fn tpsa_thiophene() {
    // RDKit: 28.24 Å² (aromatic S contribution from Ertl 2000)
    assert_approx("TPSA thiophene", tpsa(&mol("c1ccsc1")), 28.24, 0.1);
}

#[test]
fn tpsa_thiazole() {
    // RDKit: 41.13 Å² (aromatic S 28.24 + aromatic N 12.89)
    assert_approx("TPSA thiazole", tpsa(&mol("c1csc(n1)")), 41.13, 0.1);
}

#[test]
fn tpsa_dimethyl_sulfoxide() {
    // RDKit: 36.28 Å² (sulfoxide S; S=O oxygen contributes 0 — S carries polarity)
    assert_approx("TPSA DMSO", tpsa(&mol("CS(C)=O")), 36.28, 0.1);
}

#[test]
fn tpsa_dimethyl_sulfone() {
    // RDKit: 42.52 Å² (sulfone S; each S=O oxygen contributes 0)
    assert_approx("TPSA dimethylsulfone", tpsa(&mol("CS(C)(=O)=O")), 42.52, 0.1);
}

#[test]
fn tpsa_methanesulfonic_acid() {
    // RDKit: 62.75 Å² (sulfone 42.52 + OH 20.23)
    assert_approx("TPSA methanesulfonic acid", tpsa(&mol("CS(=O)(=O)O")), 62.75, 0.1);
}

#[test]
fn tpsa_furan() {
    // RDKit: 13.14 Å² (aromatic O)
    assert_approx("TPSA furan", tpsa(&mol("c1ccco1")), 13.14, 0.1);
}

#[test]
fn tpsa_indole() {
    // RDKit: 15.79 Å² (aromatic NH — RDKit uses 15.79, not Ertl 2000's 13.97)
    assert_approx("TPSA indole", tpsa(&mol("c1ccc2[nH]ccc2c1")), 15.79, 0.1);
}

#[test]
fn tpsa_methotrexate() {
    // RDKit: 210.54 Å²
    assert_approx("TPSA methotrexate",
        tpsa(&mol("CN(Cc1cnc2nc(N)nc(N)c2n1)c1ccc(cc1)C(=O)NC(CCC(=O)O)C(=O)O")),
        210.54, 2.0);
}

#[test]
fn tpsa_aspirin_no_ester_overcounting() {
    // Ensure ester O (ether-like) gets 9.23, not 17.07 or 20.23.
    // aspirin: CC(=O)Oc1ccccc1C(=O)O
    //   2 × C=O: 17.07 × 2 = 34.14
    //   1 × ester O (ether): 9.23
    //   1 × carboxyl OH: 20.23
    //   Total expected: 63.60
    let t = tpsa(&mol("CC(=O)Oc1ccccc1C(=O)O"));
    assert_approx("TPSA aspirin (ester O)", t, 63.60, 0.1);
}

// ── Heavy atom count ──────────────────────────────────────────────────────────

#[test]
fn hac_ethanol() {
    assert_eq!(heavy_atom_count(&mol("CCO")), 3);
}

#[test]
fn hac_benzene() {
    assert_eq!(heavy_atom_count(&mol("c1ccccc1")), 6);
}

#[test]
fn hac_aspirin() {
    assert_eq!(heavy_atom_count(&mol("CC(=O)Oc1ccccc1C(=O)O")), 13);
}

#[test]
fn hac_caffeine() {
    assert_eq!(heavy_atom_count(&mol("Cn1cnc2c1c(=O)n(c(=O)n2C)C")), 14);
}

// ── HBD ──────────────────────────────────────────────────────────────────────

#[test]
fn hbd_aspirin() {
    // 1 carboxylic OH
    assert_eq!(hbd_count(&mol("CC(=O)Oc1ccccc1C(=O)O")), 1);
}

#[test]
fn hbd_glucose() {
    // 5 OH groups
    assert_eq!(hbd_count(&mol("OC[C@H]1O[C@@H](O)[C@H](O)[C@@H](O)[C@@H]1O")), 5);
}

#[test]
fn hbd_caffeine() {
    // no NH or OH
    assert_eq!(hbd_count(&mol("Cn1cnc2c1c(=O)n(c(=O)n2C)C")), 0);
}

#[test]
fn hbd_paracetamol() {
    // NH + phenol OH = 2
    assert_eq!(hbd_count(&mol("CC(=O)Nc1ccc(O)cc1")), 2);
}

// ── Lipinski ─────────────────────────────────────────────────────────────────

#[test]
fn lipinski_aspirin_passes() {
    assert!(lipinski_passes(&mol("CC(=O)Oc1ccccc1C(=O)O")));
}

#[test]
fn lipinski_caffeine_passes() {
    assert!(lipinski_passes(&mol("Cn1cnc2c1c(=O)n(c(=O)n2C)C")));
}

#[test]
fn lipinski_cyclosporine_fails() {
    // Cyclosporine A — MW > 1200, fails Lipinski
    assert!(!lipinski_passes(&mol(
        "CCC1NC(=O)C(C(=O)N(C)C(CC(C)C)C(=O)NC(CC(C)C)C(=O)N(C)C(CC(C)C)C(=O)NC(C(C)C)C(=O)N(C)C1CC(C)C)"
    )));
}

// ── HBA ───────────────────────────────────────────────────────────────────────

#[test]
fn hba_aspirin() {
    // 4 O total, but carboxyl OH excluded → 3
    assert_eq!(hba_count(&mol("CC(=O)Oc1ccccc1C(=O)O")), 3);
}

#[test]
fn hba_paracetamol() {
    // amide N excluded, amide C=O + phenol OH = 2
    assert_eq!(hba_count(&mol("CC(=O)Nc1ccc(O)cc1")), 2);
}

#[test]
fn hba_caffeine() {
    // 4 aromatic N (H0, all count) + 2 C=O = 6
    assert_eq!(hba_count(&mol("Cn1cnc2c1c(=O)n(c(=O)n2C)C")), 6);
}

#[test]
fn hba_indole() {
    // [nH] is NOT HBA (lone pair in aromaticity)
    assert_eq!(hba_count(&mol("c1ccc2[nH]ccc2c1")), 0);
}

#[test]
fn hba_pyridine() {
    // pyridine N (no H) IS HBA
    assert_eq!(hba_count(&mol("c1ccncc1")), 1);
}

#[test]
fn hba_urea() {
    // both amide N excluded, only C=O counts
    assert_eq!(hba_count(&mol("NC(N)=O")), 1);
}

#[test]
fn hba_acetic_acid() {
    // carboxyl OH excluded, C=O counts → 1
    assert_eq!(hba_count(&mol("CC(=O)O")), 1);
}

// ── LogP (Crippen) ────────────────────────────────────────────────────────────

#[test]
fn logp_benzene() {
    // RDKit: 1.6866 — confirms [cH]=0.1581, H_C=0.1230
    assert_approx("LogP benzene", logp_crippen(&mol("c1ccccc1")), 1.6866, 0.02);
}

#[test]
fn logp_pyridine() {
    // RDKit: 1.0816 — confirms [n]=−0.3239
    assert_approx("LogP pyridine", logp_crippen(&mol("c1ccncc1")), 1.0816, 0.02);
}

#[test]
fn logp_thiophene() {
    // RDKit: 1.7481 — confirms [s]=+0.6237
    assert_approx("LogP thiophene", logp_crippen(&mol("c1ccsc1")), 1.7481, 0.02);
}

#[test]
fn logp_methanol() {
    // RDKit: -0.3915 — confirms O_alc=−0.2893, H_Oalc=−0.2677
    assert_approx("LogP methanol", logp_crippen(&mol("CO")), -0.3915, 0.02);
}

#[test]
fn logp_ethanol() {
    // RDKit: -0.0014
    assert_approx("LogP ethanol", logp_crippen(&mol("CCO")), -0.0014, 0.02);
}

#[test]
fn logp_acetone() {
    // RDKit: 0.5953 — confirms C10=−0.3800, O8=−0.0509
    assert_approx("LogP acetone", logp_crippen(&mol("CC(C)=O")), 0.5953, 0.02);
}

#[test]
fn logp_acetic_acid() {
    // RDKit: 0.0909 — confirms carboxylic acid H=+0.2980
    assert_approx("LogP acetic acid", logp_crippen(&mol("CC(=O)O")), 0.0909, 0.05);
}

#[test]
fn logp_aspirin() {
    // RDKit: 1.3101; ester-type C=O gets slightly different weight in full Crippen (tol=0.35)
    assert_approx("LogP aspirin", logp_crippen(&mol("CC(=O)Oc1ccccc1C(=O)O")), 1.3101, 0.35);
}

#[test]
fn logp_caffeine() {
    // RDKit: -1.0293
    assert_approx("LogP caffeine", logp_crippen(&mol("Cn1cnc2c1c(=O)n(c(=O)n2C)C")), -1.0293, 0.20);
}

#[test]
fn logp_pyrimidine() {
    // RDKit: 0.4766 — confirms two [n] = 2×(−0.3239)
    assert_approx("LogP pyrimidine", logp_crippen(&mol("c1ccncn1")), 0.4766, 0.02);
}

#[test]
fn logp_tetrahydrofuran() {
    // RDKit: 0.7968 — confirms ether O=−0.0684
    assert_approx("LogP THF", logp_crippen(&mol("C1CCOC1")), 0.7968, 0.02);
}

#[test]
fn logp_dimethyl_sulfide() {
    // RDKit: 0.9792 — confirms thioether S=+0.6482
    assert_approx("LogP dimethyl sulfide", logp_crippen(&mol("CSC")), 0.9792, 0.02);
}

#[test]
fn logp_chlorobenzene() {
    // RDKit: 2.3400 — confirms Cl_ar=+0.7904
    assert_approx("LogP chlorobenzene", logp_crippen(&mol("Clc1ccccc1")), 2.3400, 0.02);
}

#[test]
fn logp_dichloromethane() {
    // RDKit: 1.4215 — confirms Cl_al=+0.6895
    assert_approx("LogP DCM", logp_crippen(&mol("ClCCl")), 1.4215, 0.02);
}

// ── v0.1.3 LogP regression tests (5 new atom-type fixes) ─────────────────────

#[test]
fn logp_phenol() {
    // Fix1: phenolic H = +0.1319 (was −0.2677 aliphatic alcohol)
    // RDKit: 1.3922 — exact match
    assert_approx("LogP phenol", logp_crippen(&mol("c1ccccc1O")), 1.3922, 0.005);
}

#[test]
fn logp_catechol() {
    // Fix1 × 2: two phenolic OH groups
    // RDKit: 1.0978 — exact match
    assert_approx("LogP catechol", logp_crippen(&mol("Oc1ccccc1O")), 1.0978, 0.005);
}

#[test]
fn logp_salicylic_acid() {
    // Fix1 (phenolic OH) + Fix2 (ArC=O); combined 0.6570 exact
    // RDKit: 1.0904 — exact match
    assert_approx("LogP salicylic acid", logp_crippen(&mol("OC(=O)c1ccccc1O")), 1.0904, 0.01);
}

#[test]
fn logp_toluene() {
    // Fix3: benzyl CH3-Ar = 0.0764 (was 0.1441 pure alkyl)
    // RDKit: 1.9950 — exact match
    assert_approx("LogP toluene", logp_crippen(&mol("Cc1ccccc1")), 1.9950, 0.01);
}

#[test]
fn logp_ethylbenzene() {
    // Fix3: benzyl CH2-Ar = −0.0597 (was 0.1441)
    // RDKit: 2.2490 — exact match
    assert_approx("LogP ethylbenzene", logp_crippen(&mol("CCc1ccccc1")), 2.2490, 0.01);
}

#[test]
fn logp_aniline() {
    // Fix4: primary aniline N (h=2, adj to Ar) = −0.7092 (was −1.0190 aliphatic)
    // RDKit: 1.2688 — exact match
    assert_approx("LogP aniline", logp_crippen(&mol("Nc1ccccc1")), 1.2688, 0.01);
}

#[test]
fn logp_thiophenol() {
    // Fix5: thiol S (h>0, no =O) = 0.3132 (was 0.6482 thioether)
    // RDKit: 1.9753 — exact match
    assert_approx("LogP thiophenol", logp_crippen(&mol("Sc1ccccc1")), 1.9753, 0.02);
}

// ── Sprint D: TPSA imine NH, phosphate P ────────────────────────────────────

#[test]
fn tpsa_metformin() {
    // CN(C)C(=N)NC(=N)N — RDKit: 88.99 Å²
    // Tests terminal imine C=N-H (h=1, sp2) → 23.79 Å² (not 12.03 like sp3 NH)
    assert_approx("TPSA metformin", tpsa(&mol("CN(C)C(=N)NC(=N)N")), 88.99, 0.5);
}

#[test]
fn tpsa_arginine() {
    // N[C@@H](CCCNC(=N)N)C(=O)O — RDKit: 125.22 Å²
    // Tests guanidinium =N-H in amino acid side chain
    assert_approx("TPSA arginine", tpsa(&mol("N[C@@H](CCCNC(=N)N)C(=O)O")), 125.22, 0.5);
}

#[test]
fn tpsa_trimethyl_phosphate() {
    // COP(=O)(OC)OC — RDKit: 54.57 Å²
    // Tests phosphate P=O → 26.88 Å² (not 34.14 for phosphine)
    assert_approx("TPSA trimethyl phosphate", tpsa(&mol("COP(=O)(OC)OC")), 54.57, 0.5);
}

#[test]
fn logp_trimethyl_phosphate() {
    // COP(=O)(OC)OC — RDKit: 1.0337
    // Tests phosphate ester P(=O) LogP contribution (+0.7933)
    assert_approx("LogP trimethyl phosphate", logp_crippen(&mol("COP(=O)(OC)OC")), 1.0337, 0.15);
}

// ── Sprint D: new ring descriptors ──────────────────────────────────────────

#[test]
fn ring_descs_pyridine() {
    let m = mol("c1ccncc1");
    assert_eq!(num_aromatic_heterocycles(&m), 1, "pyridine aromatic hetero rings");
    assert_eq!(num_aliphatic_heterocycles(&m), 0, "pyridine aliphatic hetero rings");
    assert_eq!(num_saturated_heterocycles(&m), 0, "pyridine saturated hetero rings");
    assert_eq!(num_spiro_atoms(&m), 0, "pyridine spiro");
    assert_eq!(num_bridgehead_atoms(&m), 0, "pyridine bridgehead");
}

#[test]
fn ring_descs_benzene() {
    let m = mol("c1ccccc1");
    assert_eq!(num_aromatic_heterocycles(&m), 0, "benzene has no hetero ring");
    assert_eq!(num_spiro_atoms(&m), 0);
    assert_eq!(num_bridgehead_atoms(&m), 0);
}

#[test]
fn ring_descs_piperidine() {
    let m = mol("C1CCNCC1");
    assert_eq!(num_aliphatic_heterocycles(&m), 1, "piperidine aliphatic");
    assert_eq!(num_saturated_heterocycles(&m), 1, "piperidine saturated");
    assert_eq!(num_aromatic_heterocycles(&m), 0, "piperidine not aromatic");
}

#[test]
fn ring_descs_morpholine() {
    let m = mol("C1COCCN1");
    assert_eq!(num_aliphatic_heterocycles(&m), 1, "morpholine aliphatic");
    assert_eq!(num_saturated_heterocycles(&m), 1, "morpholine saturated");
}

#[test]
fn ring_descs_spiro_decane() {
    // spiro[4.5]decane
    let m = mol("C1CCCCC11CCCC1");
    assert_eq!(num_spiro_atoms(&m), 1, "spiro[4.5]decane has 1 spiro atom");
    assert_eq!(num_bridgehead_atoms(&m), 0, "spiro is not bridgehead");
}

#[test]
fn ring_descs_norbornane() {
    // bicyclo[2.2.1]heptane
    let m = mol("C1CC2CCC1C2");
    assert_eq!(num_bridgehead_atoms(&m), 2, "norbornane has 2 bridgeheads");
    assert_eq!(num_spiro_atoms(&m), 0, "norbornane has no spiro atoms");
}

#[test]
fn ring_descs_naphthalene_no_spiro() {
    // Fused ring: two rings share 2 atoms (C4a, C8a) — not spiro, not bridgehead
    let m = mol("c1ccc2ccccc2c1");
    assert_eq!(num_spiro_atoms(&m), 0, "naphthalene has no spiro atoms");
    assert_eq!(num_bridgehead_atoms(&m), 0, "naphthalene bridgehead");
}
