//! GENERATED FILE -- DO NOT EDIT.
//!
//! Regenerate with `python3 scripts/gen_mmff94_numeric_type_registry.py`.
//! Source: RDKit `Code/ForceField/MMFF/Params.cpp` (`defaultMMFFDef` + `defaultMMFFProp`), tag `Release_2026_03_3`,
//! commit `e74e7b0a5a2fc4e7f77c04ec26a61d4b8edbf22f`. Full provenance: `scripts/mmff94_provenance/PROVENANCE.md`.
//!
//! Authoritative metadata for every MMFF94 numeric atom type chematic can
//! assign or look up. `element` is the semantic-compatibility gate's ground
//! truth: a parameter row matched under a type whose registered `element`
//! disagrees with the atom's real element is a collision, not a hit (issue
//! #227's `furan` finding).

use chematic_core::Element;

/// One MMFF94 numeric atom type's authoritative metadata.
#[derive(Debug, Clone, Copy)]
pub struct Mmff94NumericTypeInfo {
    /// MMFF94 numeric type ID (1-99).
    pub id: u8,
    /// RDKit/Halgren short symbol, e.g. "CB", "C5A", "NPYD".
    pub symbol: &'static str,
    /// The only element this numeric type may legitimately represent.
    pub element: Element,
    /// Atomic number (redundant with `element`, kept for direct
    /// comparison against RDKit's `aspec` column without a round-trip).
    pub atomic_number: u8,
    /// Coordination number (MMFFPROP `crd`).
    pub coordination: u8,
    /// Valence (MMFFPROP `val`).
    pub valence: u8,
    /// Has a lone pair capable of conjugation (MMFFPROP `pilp`).
    pub has_pi_lone_pair: bool,
    /// Number of attached multiple bonds (MMFFPROP `mltb`, 0-3).
    pub multiple_bond_count: u8,
    /// Aromatic atom type (MMFFPROP `arom`).
    pub aromatic: bool,
    /// Linear geometry, e.g. nitrile/acetylenic (MMFFPROP `lin`).
    pub linear: bool,
    /// Single bond adjacent to a multiple bond (MMFFPROP `sbmb`).
    pub single_bond_multiple_bond: bool,
    /// MMFF94 atom-type equivalence levels 2-5 (`MMFFDEF.PAR`), used
    /// for the equivalence-class parameter fallback (not yet wired
    /// into any chematic resolver -- see the Phase 1B-0 PR body's
    /// bond-fallback classification for why).
    pub equivalence_levels: [u8; 4],
    /// Human-readable Halgren description, e.g. "AROMATIC C".
    pub description: &'static str,
}

pub static MMFF94_NUMERIC_TYPE_REGISTRY: &[Mmff94NumericTypeInfo] = &[
    Mmff94NumericTypeInfo {
        id: 1,
        symbol: "CR",
        element: Element::C,
        atomic_number: 6,
        coordination: 4,
        valence: 4,
        has_pi_lone_pair: false,
        multiple_bond_count: 0,
        aromatic: false,
        linear: false,
        single_bond_multiple_bond: false,
        equivalence_levels: [1, 1, 1, 0],
        description: "ALKYL CARBON",
    },
    Mmff94NumericTypeInfo {
        id: 2,
        symbol: "C=C",
        element: Element::C,
        atomic_number: 6,
        coordination: 3,
        valence: 4,
        has_pi_lone_pair: false,
        multiple_bond_count: 2,
        aromatic: false,
        linear: false,
        single_bond_multiple_bond: true,
        equivalence_levels: [2, 2, 1, 0],
        description: "VINYLIC",
    },
    Mmff94NumericTypeInfo {
        id: 3,
        symbol: "C=O",
        element: Element::C,
        atomic_number: 6,
        coordination: 3,
        valence: 4,
        has_pi_lone_pair: false,
        multiple_bond_count: 2,
        aromatic: false,
        linear: false,
        single_bond_multiple_bond: true,
        equivalence_levels: [3, 3, 1, 0],
        description: "GENERAL CARBONYL C",
    },
    Mmff94NumericTypeInfo {
        id: 4,
        symbol: "CSP",
        element: Element::C,
        atomic_number: 6,
        coordination: 2,
        valence: 4,
        has_pi_lone_pair: false,
        multiple_bond_count: 3,
        aromatic: false,
        linear: true,
        single_bond_multiple_bond: true,
        equivalence_levels: [4, 4, 1, 0],
        description: "ACETYLENIC C",
    },
    Mmff94NumericTypeInfo {
        id: 5,
        symbol: "HC",
        element: Element::H,
        atomic_number: 1,
        coordination: 1,
        valence: 1,
        has_pi_lone_pair: false,
        multiple_bond_count: 0,
        aromatic: false,
        linear: false,
        single_bond_multiple_bond: false,
        equivalence_levels: [5, 5, 5, 0],
        description: "H-C",
    },
    Mmff94NumericTypeInfo {
        id: 6,
        symbol: "OR",
        element: Element::O,
        atomic_number: 8,
        coordination: 2,
        valence: 2,
        has_pi_lone_pair: true,
        multiple_bond_count: 0,
        aromatic: false,
        linear: false,
        single_bond_multiple_bond: false,
        equivalence_levels: [6, 6, 6, 0],
        description: "O-CSP3",
    },
    Mmff94NumericTypeInfo {
        id: 7,
        symbol: "O=C",
        element: Element::O,
        atomic_number: 8,
        coordination: 1,
        valence: 2,
        has_pi_lone_pair: false,
        multiple_bond_count: 2,
        aromatic: false,
        linear: false,
        single_bond_multiple_bond: false,
        equivalence_levels: [7, 7, 6, 0],
        description: "O=C, GENERIC",
    },
    Mmff94NumericTypeInfo {
        id: 8,
        symbol: "NR",
        element: Element::N,
        atomic_number: 7,
        coordination: 3,
        valence: 3,
        has_pi_lone_pair: true,
        multiple_bond_count: 0,
        aromatic: false,
        linear: false,
        single_bond_multiple_bond: false,
        equivalence_levels: [8, 8, 8, 0],
        description: "AMINE N",
    },
    Mmff94NumericTypeInfo {
        id: 9,
        symbol: "N=C",
        element: Element::N,
        atomic_number: 7,
        coordination: 2,
        valence: 3,
        has_pi_lone_pair: false,
        multiple_bond_count: 2,
        aromatic: false,
        linear: false,
        single_bond_multiple_bond: true,
        equivalence_levels: [9, 9, 8, 0],
        description: "N=C, IMINES",
    },
    Mmff94NumericTypeInfo {
        id: 10,
        symbol: "NC=O",
        element: Element::N,
        atomic_number: 7,
        coordination: 3,
        valence: 3,
        has_pi_lone_pair: true,
        multiple_bond_count: 1,
        aromatic: false,
        linear: false,
        single_bond_multiple_bond: false,
        equivalence_levels: [10, 10, 8, 0],
        description: "N-C=O, AMIDES",
    },
    Mmff94NumericTypeInfo {
        id: 11,
        symbol: "F",
        element: Element::F,
        atomic_number: 9,
        coordination: 1,
        valence: 1,
        has_pi_lone_pair: true,
        multiple_bond_count: 0,
        aromatic: false,
        linear: false,
        single_bond_multiple_bond: false,
        equivalence_levels: [11, 11, 11, 0],
        description: "FLUORINE",
    },
    Mmff94NumericTypeInfo {
        id: 12,
        symbol: "CL",
        element: Element::CL,
        atomic_number: 17,
        coordination: 1,
        valence: 1,
        has_pi_lone_pair: true,
        multiple_bond_count: 0,
        aromatic: false,
        linear: false,
        single_bond_multiple_bond: false,
        equivalence_levels: [12, 12, 12, 0],
        description: "CHLORINE",
    },
    Mmff94NumericTypeInfo {
        id: 13,
        symbol: "BR",
        element: Element::BR,
        atomic_number: 35,
        coordination: 1,
        valence: 1,
        has_pi_lone_pair: true,
        multiple_bond_count: 0,
        aromatic: false,
        linear: false,
        single_bond_multiple_bond: false,
        equivalence_levels: [13, 13, 13, 0],
        description: "BROMINE",
    },
    Mmff94NumericTypeInfo {
        id: 14,
        symbol: "I",
        element: Element::I,
        atomic_number: 53,
        coordination: 1,
        valence: 1,
        has_pi_lone_pair: true,
        multiple_bond_count: 0,
        aromatic: false,
        linear: false,
        single_bond_multiple_bond: false,
        equivalence_levels: [14, 14, 14, 0],
        description: "IODINE",
    },
    Mmff94NumericTypeInfo {
        id: 15,
        symbol: "S",
        element: Element::S,
        atomic_number: 16,
        coordination: 2,
        valence: 2,
        has_pi_lone_pair: true,
        multiple_bond_count: 0,
        aromatic: false,
        linear: false,
        single_bond_multiple_bond: false,
        equivalence_levels: [15, 15, 15, 0],
        description: "THIOL, SULFIDE",
    },
    Mmff94NumericTypeInfo {
        id: 16,
        symbol: "S=C",
        element: Element::S,
        atomic_number: 16,
        coordination: 1,
        valence: 2,
        has_pi_lone_pair: false,
        multiple_bond_count: 2,
        aromatic: false,
        linear: false,
        single_bond_multiple_bond: false,
        equivalence_levels: [16, 16, 15, 0],
        description: "S DOUBLY BONDED TO C",
    },
    Mmff94NumericTypeInfo {
        id: 17,
        symbol: "S=O",
        element: Element::S,
        atomic_number: 16,
        coordination: 3,
        valence: 4,
        has_pi_lone_pair: false,
        multiple_bond_count: 2,
        aromatic: false,
        linear: false,
        single_bond_multiple_bond: false,
        equivalence_levels: [17, 17, 15, 0],
        description: "SULFOXIDE S",
    },
    Mmff94NumericTypeInfo {
        id: 18,
        symbol: "SO2",
        element: Element::S,
        atomic_number: 16,
        coordination: 4,
        valence: 4,
        has_pi_lone_pair: false,
        multiple_bond_count: 0,
        aromatic: false,
        linear: false,
        single_bond_multiple_bond: false,
        equivalence_levels: [18, 18, 15, 0],
        description: "SULFONE S",
    },
    Mmff94NumericTypeInfo {
        id: 19,
        symbol: "SI",
        element: Element::SI,
        atomic_number: 14,
        coordination: 4,
        valence: 4,
        has_pi_lone_pair: false,
        multiple_bond_count: 0,
        aromatic: false,
        linear: false,
        single_bond_multiple_bond: false,
        equivalence_levels: [19, 19, 19, 0],
        description: "SILICON",
    },
    Mmff94NumericTypeInfo {
        id: 20,
        symbol: "CR4R",
        element: Element::C,
        atomic_number: 6,
        coordination: 4,
        valence: 4,
        has_pi_lone_pair: false,
        multiple_bond_count: 0,
        aromatic: false,
        linear: false,
        single_bond_multiple_bond: false,
        equivalence_levels: [20, 1, 1, 0],
        description: "C IN CYCLOBUTYL",
    },
    Mmff94NumericTypeInfo {
        id: 21,
        symbol: "HOR",
        element: Element::H,
        atomic_number: 1,
        coordination: 1,
        valence: 1,
        has_pi_lone_pair: false,
        multiple_bond_count: 0,
        aromatic: false,
        linear: false,
        single_bond_multiple_bond: false,
        equivalence_levels: [21, 21, 5, 0],
        description: "H-O, ALCOHOLS",
    },
    Mmff94NumericTypeInfo {
        id: 22,
        symbol: "CR3R",
        element: Element::C,
        atomic_number: 6,
        coordination: 4,
        valence: 4,
        has_pi_lone_pair: false,
        multiple_bond_count: 0,
        aromatic: false,
        linear: false,
        single_bond_multiple_bond: false,
        equivalence_levels: [22, 22, 1, 0],
        description: "C IN CYCLOPROPLY",
    },
    Mmff94NumericTypeInfo {
        id: 23,
        symbol: "HNR",
        element: Element::H,
        atomic_number: 1,
        coordination: 1,
        valence: 1,
        has_pi_lone_pair: false,
        multiple_bond_count: 0,
        aromatic: false,
        linear: false,
        single_bond_multiple_bond: false,
        equivalence_levels: [23, 23, 5, 0],
        description: "H-N, AMINES",
    },
    Mmff94NumericTypeInfo {
        id: 24,
        symbol: "HOCO",
        element: Element::H,
        atomic_number: 1,
        coordination: 1,
        valence: 1,
        has_pi_lone_pair: false,
        multiple_bond_count: 0,
        aromatic: false,
        linear: false,
        single_bond_multiple_bond: false,
        equivalence_levels: [24, 24, 5, 0],
        description: "H-O, ACIDS",
    },
    Mmff94NumericTypeInfo {
        id: 25,
        symbol: "PO4",
        element: Element::P,
        atomic_number: 15,
        coordination: 4,
        valence: 4,
        has_pi_lone_pair: false,
        multiple_bond_count: 0,
        aromatic: false,
        linear: false,
        single_bond_multiple_bond: false,
        equivalence_levels: [25, 25, 25, 0],
        description: "PHOSPHODIESTER",
    },
    Mmff94NumericTypeInfo {
        id: 26,
        symbol: "P",
        element: Element::P,
        atomic_number: 15,
        coordination: 3,
        valence: 3,
        has_pi_lone_pair: true,
        multiple_bond_count: 0,
        aromatic: false,
        linear: false,
        single_bond_multiple_bond: false,
        equivalence_levels: [26, 26, 25, 0],
        description: "TRICOORDINATE P",
    },
    Mmff94NumericTypeInfo {
        id: 27,
        symbol: "HN=C",
        element: Element::H,
        atomic_number: 1,
        coordination: 1,
        valence: 1,
        has_pi_lone_pair: false,
        multiple_bond_count: 0,
        aromatic: false,
        linear: false,
        single_bond_multiple_bond: false,
        equivalence_levels: [27, 28, 5, 0],
        description: "IMINE N-H",
    },
    Mmff94NumericTypeInfo {
        id: 28,
        symbol: "HNCO",
        element: Element::H,
        atomic_number: 1,
        coordination: 1,
        valence: 1,
        has_pi_lone_pair: false,
        multiple_bond_count: 0,
        aromatic: false,
        linear: false,
        single_bond_multiple_bond: false,
        equivalence_levels: [28, 28, 5, 0],
        description: "H-N, AMIDES",
    },
    Mmff94NumericTypeInfo {
        id: 29,
        symbol: "HOCC",
        element: Element::H,
        atomic_number: 1,
        coordination: 1,
        valence: 1,
        has_pi_lone_pair: false,
        multiple_bond_count: 0,
        aromatic: false,
        linear: false,
        single_bond_multiple_bond: false,
        equivalence_levels: [29, 29, 5, 0],
        description: "H-O, ENOLS, PHENOLS",
    },
    Mmff94NumericTypeInfo {
        id: 30,
        symbol: "CE4R",
        element: Element::C,
        atomic_number: 6,
        coordination: 3,
        valence: 4,
        has_pi_lone_pair: false,
        multiple_bond_count: 2,
        aromatic: false,
        linear: false,
        single_bond_multiple_bond: true,
        equivalence_levels: [30, 2, 1, 0],
        description: "C=C IN 4-RING",
    },
    Mmff94NumericTypeInfo {
        id: 31,
        symbol: "HOH",
        element: Element::H,
        atomic_number: 1,
        coordination: 1,
        valence: 1,
        has_pi_lone_pair: false,
        multiple_bond_count: 0,
        aromatic: false,
        linear: false,
        single_bond_multiple_bond: false,
        equivalence_levels: [31, 31, 31, 0],
        description: "H-OH",
    },
    Mmff94NumericTypeInfo {
        id: 32,
        symbol: "O2CM",
        element: Element::O,
        atomic_number: 8,
        coordination: 1,
        valence: 12,
        has_pi_lone_pair: true,
        multiple_bond_count: 1,
        aromatic: false,
        linear: false,
        single_bond_multiple_bond: false,
        equivalence_levels: [32, 7, 6, 0],
        description: "O, CARBOXYLATE ANION",
    },
    Mmff94NumericTypeInfo {
        id: 33,
        symbol: "HOS",
        element: Element::H,
        atomic_number: 1,
        coordination: 1,
        valence: 1,
        has_pi_lone_pair: false,
        multiple_bond_count: 0,
        aromatic: false,
        linear: false,
        single_bond_multiple_bond: false,
        equivalence_levels: [33, 21, 5, 0],
        description: "H-O-S, SULF ACIDS",
    },
    Mmff94NumericTypeInfo {
        id: 34,
        symbol: "NR+",
        element: Element::N,
        atomic_number: 7,
        coordination: 4,
        valence: 4,
        has_pi_lone_pair: false,
        multiple_bond_count: 0,
        aromatic: false,
        linear: false,
        single_bond_multiple_bond: false,
        equivalence_levels: [34, 8, 8, 0],
        description: "N+, QUATERNARY N",
    },
    Mmff94NumericTypeInfo {
        id: 35,
        symbol: "OM",
        element: Element::O,
        atomic_number: 8,
        coordination: 1,
        valence: 1,
        has_pi_lone_pair: true,
        multiple_bond_count: 1,
        aromatic: false,
        linear: false,
        single_bond_multiple_bond: false,
        equivalence_levels: [35, 6, 6, 0],
        description: "OXIDE OXYGEN ON SP3 C",
    },
    Mmff94NumericTypeInfo {
        id: 36,
        symbol: "HNR+",
        element: Element::H,
        atomic_number: 1,
        coordination: 1,
        valence: 1,
        has_pi_lone_pair: false,
        multiple_bond_count: 0,
        aromatic: false,
        linear: false,
        single_bond_multiple_bond: false,
        equivalence_levels: [36, 36, 5, 0],
        description: "H-N+",
    },
    Mmff94NumericTypeInfo {
        id: 37,
        symbol: "CB",
        element: Element::C,
        atomic_number: 6,
        coordination: 3,
        valence: 4,
        has_pi_lone_pair: false,
        multiple_bond_count: 2,
        aromatic: true,
        linear: false,
        single_bond_multiple_bond: true,
        equivalence_levels: [37, 2, 1, 0],
        description: "AROMATIC C",
    },
    Mmff94NumericTypeInfo {
        id: 38,
        symbol: "NPYD",
        element: Element::N,
        atomic_number: 7,
        coordination: 2,
        valence: 3,
        has_pi_lone_pair: false,
        multiple_bond_count: 2,
        aromatic: true,
        linear: false,
        single_bond_multiple_bond: false,
        equivalence_levels: [38, 9, 8, 0],
        description: "AROMATIC N, PYRIDINE",
    },
    Mmff94NumericTypeInfo {
        id: 39,
        symbol: "NPYL",
        element: Element::N,
        atomic_number: 7,
        coordination: 3,
        valence: 3,
        has_pi_lone_pair: true,
        multiple_bond_count: 1,
        aromatic: true,
        linear: false,
        single_bond_multiple_bond: true,
        equivalence_levels: [39, 10, 8, 0],
        description: "AROMATIC N, PYRROLE",
    },
    Mmff94NumericTypeInfo {
        id: 40,
        symbol: "NC=C",
        element: Element::N,
        atomic_number: 7,
        coordination: 3,
        valence: 3,
        has_pi_lone_pair: true,
        multiple_bond_count: 0,
        aromatic: false,
        linear: false,
        single_bond_multiple_bond: false,
        equivalence_levels: [40, 10, 8, 0],
        description: "N-C=C (DELOC LP)",
    },
    Mmff94NumericTypeInfo {
        id: 41,
        symbol: "CO2M",
        element: Element::C,
        atomic_number: 6,
        coordination: 3,
        valence: 4,
        has_pi_lone_pair: false,
        multiple_bond_count: 1,
        aromatic: false,
        linear: false,
        single_bond_multiple_bond: false,
        equivalence_levels: [41, 3, 1, 0],
        description: "C IN CO2- ANION",
    },
    Mmff94NumericTypeInfo {
        id: 42,
        symbol: "NSP",
        element: Element::N,
        atomic_number: 7,
        coordination: 1,
        valence: 3,
        has_pi_lone_pair: false,
        multiple_bond_count: 3,
        aromatic: false,
        linear: false,
        single_bond_multiple_bond: false,
        equivalence_levels: [42, 42, 8, 0],
        description: "N TRIPLE BONDED",
    },
    Mmff94NumericTypeInfo {
        id: 43,
        symbol: "NSO2",
        element: Element::N,
        atomic_number: 7,
        coordination: 3,
        valence: 3,
        has_pi_lone_pair: true,
        multiple_bond_count: 0,
        aromatic: false,
        linear: false,
        single_bond_multiple_bond: false,
        equivalence_levels: [43, 10, 8, 0],
        description: "N, SULFONAMIDES",
    },
    Mmff94NumericTypeInfo {
        id: 44,
        symbol: "STHI",
        element: Element::S,
        atomic_number: 16,
        coordination: 2,
        valence: 2,
        has_pi_lone_pair: true,
        multiple_bond_count: 1,
        aromatic: true,
        linear: false,
        single_bond_multiple_bond: false,
        equivalence_levels: [44, 16, 15, 0],
        description: "S IN THIOPHENE",
    },
    Mmff94NumericTypeInfo {
        id: 45,
        symbol: "NO2",
        element: Element::N,
        atomic_number: 7,
        coordination: 3,
        valence: 4,
        has_pi_lone_pair: false,
        multiple_bond_count: 2,
        aromatic: false,
        linear: false,
        single_bond_multiple_bond: false,
        equivalence_levels: [45, 10, 8, 0],
        description: "NITRO GROUP N",
    },
    Mmff94NumericTypeInfo {
        id: 46,
        symbol: "N=O",
        element: Element::N,
        atomic_number: 7,
        coordination: 2,
        valence: 3,
        has_pi_lone_pair: false,
        multiple_bond_count: 2,
        aromatic: false,
        linear: false,
        single_bond_multiple_bond: false,
        equivalence_levels: [46, 9, 8, 0],
        description: "NITROSO GROUP N",
    },
    Mmff94NumericTypeInfo {
        id: 47,
        symbol: "NAZT",
        element: Element::N,
        atomic_number: 7,
        coordination: 1,
        valence: 2,
        has_pi_lone_pair: false,
        multiple_bond_count: 2,
        aromatic: false,
        linear: false,
        single_bond_multiple_bond: false,
        equivalence_levels: [47, 42, 8, 0],
        description: "TERMINAL N, AZIDE",
    },
    Mmff94NumericTypeInfo {
        id: 48,
        symbol: "NSO",
        element: Element::N,
        atomic_number: 7,
        coordination: 2,
        valence: 2,
        has_pi_lone_pair: false,
        multiple_bond_count: 0,
        aromatic: false,
        linear: false,
        single_bond_multiple_bond: false,
        equivalence_levels: [48, 9, 8, 0],
        description: "DIVAL. N IN S(N)(O) GP",
    },
    Mmff94NumericTypeInfo {
        id: 49,
        symbol: "O+",
        element: Element::O,
        atomic_number: 8,
        coordination: 3,
        valence: 3,
        has_pi_lone_pair: false,
        multiple_bond_count: 0,
        aromatic: false,
        linear: false,
        single_bond_multiple_bond: false,
        equivalence_levels: [49, 6, 6, 0],
        description: "OXONIUM (TRICOORD) O",
    },
    Mmff94NumericTypeInfo {
        id: 50,
        symbol: "HO+",
        element: Element::H,
        atomic_number: 1,
        coordination: 1,
        valence: 1,
        has_pi_lone_pair: false,
        multiple_bond_count: 0,
        aromatic: false,
        linear: false,
        single_bond_multiple_bond: false,
        equivalence_levels: [50, 21, 5, 0],
        description: "H ON OXONIUM OXYGEN",
    },
    Mmff94NumericTypeInfo {
        id: 51,
        symbol: "O=+",
        element: Element::O,
        atomic_number: 8,
        coordination: 2,
        valence: 3,
        has_pi_lone_pair: false,
        multiple_bond_count: 2,
        aromatic: false,
        linear: false,
        single_bond_multiple_bond: false,
        equivalence_levels: [51, 7, 6, 0],
        description: "OXENIUM OXYGEN+",
    },
    Mmff94NumericTypeInfo {
        id: 52,
        symbol: "HO=+",
        element: Element::H,
        atomic_number: 1,
        coordination: 1,
        valence: 1,
        has_pi_lone_pair: false,
        multiple_bond_count: 0,
        aromatic: false,
        linear: false,
        single_bond_multiple_bond: false,
        equivalence_levels: [52, 21, 5, 0],
        description: "H ON OXENIUM O+",
    },
    Mmff94NumericTypeInfo {
        id: 53,
        symbol: "=N=",
        element: Element::N,
        atomic_number: 7,
        coordination: 2,
        valence: 4,
        has_pi_lone_pair: false,
        multiple_bond_count: 2,
        aromatic: false,
        linear: true,
        single_bond_multiple_bond: false,
        equivalence_levels: [53, 42, 8, 0],
        description: "N TWICE DOUBLE BONDED",
    },
    Mmff94NumericTypeInfo {
        id: 54,
        symbol: "N+=C",
        element: Element::N,
        atomic_number: 7,
        coordination: 3,
        valence: 4,
        has_pi_lone_pair: false,
        multiple_bond_count: 2,
        aromatic: false,
        linear: false,
        single_bond_multiple_bond: true,
        equivalence_levels: [54, 9, 8, 0],
        description: "IMINIUM NITROGEN",
    },
    Mmff94NumericTypeInfo {
        id: 55,
        symbol: "NCN+",
        element: Element::N,
        atomic_number: 7,
        coordination: 3,
        valence: 34,
        has_pi_lone_pair: false,
        multiple_bond_count: 1,
        aromatic: false,
        linear: false,
        single_bond_multiple_bond: false,
        equivalence_levels: [55, 10, 8, 0],
        description: "N IN +N=C-N: ; Q=1/2",
    },
    Mmff94NumericTypeInfo {
        id: 56,
        symbol: "NGD+",
        element: Element::N,
        atomic_number: 7,
        coordination: 3,
        valence: 34,
        has_pi_lone_pair: false,
        multiple_bond_count: 1,
        aromatic: false,
        linear: false,
        single_bond_multiple_bond: false,
        equivalence_levels: [56, 10, 8, 0],
        description: "GUANIDINIUM N; Q=1/3",
    },
    Mmff94NumericTypeInfo {
        id: 57,
        symbol: "CGD+",
        element: Element::C,
        atomic_number: 6,
        coordination: 3,
        valence: 4,
        has_pi_lone_pair: false,
        multiple_bond_count: 2,
        aromatic: false,
        linear: false,
        single_bond_multiple_bond: true,
        equivalence_levels: [57, 2, 1, 0],
        description: "GUANIDINIUM CARBON",
    },
    Mmff94NumericTypeInfo {
        id: 58,
        symbol: "NPD+",
        element: Element::N,
        atomic_number: 7,
        coordination: 3,
        valence: 4,
        has_pi_lone_pair: false,
        multiple_bond_count: 1,
        aromatic: true,
        linear: false,
        single_bond_multiple_bond: true,
        equivalence_levels: [58, 10, 8, 0],
        description: "N PYRIDINIUM ION",
    },
    Mmff94NumericTypeInfo {
        id: 59,
        symbol: "OFUR",
        element: Element::O,
        atomic_number: 8,
        coordination: 2,
        valence: 2,
        has_pi_lone_pair: true,
        multiple_bond_count: 1,
        aromatic: true,
        linear: false,
        single_bond_multiple_bond: false,
        equivalence_levels: [59, 6, 6, 0],
        description: "AROMATIC O, FURAN",
    },
    Mmff94NumericTypeInfo {
        id: 60,
        symbol: "C%",
        element: Element::C,
        atomic_number: 6,
        coordination: 1,
        valence: 3,
        has_pi_lone_pair: false,
        multiple_bond_count: 3,
        aromatic: false,
        linear: false,
        single_bond_multiple_bond: false,
        equivalence_levels: [60, 4, 1, 0],
        description: "ISONITRILE CARBON",
    },
    Mmff94NumericTypeInfo {
        id: 61,
        symbol: "NR%",
        element: Element::N,
        atomic_number: 7,
        coordination: 2,
        valence: 4,
        has_pi_lone_pair: false,
        multiple_bond_count: 3,
        aromatic: false,
        linear: true,
        single_bond_multiple_bond: false,
        equivalence_levels: [61, 42, 8, 0],
        description: "ISONITRILE N",
    },
    Mmff94NumericTypeInfo {
        id: 62,
        symbol: "NM",
        element: Element::N,
        atomic_number: 7,
        coordination: 2,
        valence: 2,
        has_pi_lone_pair: true,
        multiple_bond_count: 0,
        aromatic: false,
        linear: false,
        single_bond_multiple_bond: false,
        equivalence_levels: [62, 10, 8, 0],
        description: "SULFONAMIDE N-",
    },
    Mmff94NumericTypeInfo {
        id: 63,
        symbol: "C5A",
        element: Element::C,
        atomic_number: 6,
        coordination: 3,
        valence: 4,
        has_pi_lone_pair: false,
        multiple_bond_count: 2,
        aromatic: true,
        linear: false,
        single_bond_multiple_bond: true,
        equivalence_levels: [63, 2, 1, 0],
        description: "ALPHA AROM 5-RING C",
    },
    Mmff94NumericTypeInfo {
        id: 64,
        symbol: "C5B",
        element: Element::C,
        atomic_number: 6,
        coordination: 3,
        valence: 4,
        has_pi_lone_pair: false,
        multiple_bond_count: 2,
        aromatic: true,
        linear: false,
        single_bond_multiple_bond: true,
        equivalence_levels: [64, 2, 1, 0],
        description: "BETA AROM 5-RING C",
    },
    Mmff94NumericTypeInfo {
        id: 65,
        symbol: "N5A",
        element: Element::N,
        atomic_number: 7,
        coordination: 2,
        valence: 3,
        has_pi_lone_pair: false,
        multiple_bond_count: 2,
        aromatic: true,
        linear: false,
        single_bond_multiple_bond: false,
        equivalence_levels: [65, 9, 8, 0],
        description: "ALPHA AROM 5-RING N",
    },
    Mmff94NumericTypeInfo {
        id: 66,
        symbol: "N5B",
        element: Element::N,
        atomic_number: 7,
        coordination: 2,
        valence: 3,
        has_pi_lone_pair: false,
        multiple_bond_count: 2,
        aromatic: true,
        linear: false,
        single_bond_multiple_bond: false,
        equivalence_levels: [66, 9, 8, 0],
        description: "ALPHA AROM 5-RING N",
    },
    Mmff94NumericTypeInfo {
        id: 67,
        symbol: "N2OX",
        element: Element::N,
        atomic_number: 7,
        coordination: 3,
        valence: 4,
        has_pi_lone_pair: false,
        multiple_bond_count: 2,
        aromatic: false,
        linear: false,
        single_bond_multiple_bond: true,
        equivalence_levels: [67, 9, 8, 0],
        description: "NITROGEN IN N-OXIDE",
    },
    Mmff94NumericTypeInfo {
        id: 68,
        symbol: "N3OX",
        element: Element::N,
        atomic_number: 7,
        coordination: 4,
        valence: 4,
        has_pi_lone_pair: false,
        multiple_bond_count: 0,
        aromatic: false,
        linear: false,
        single_bond_multiple_bond: false,
        equivalence_levels: [68, 8, 8, 0],
        description: "NITROGEN IN N-OXIDE",
    },
    Mmff94NumericTypeInfo {
        id: 69,
        symbol: "NPOX",
        element: Element::N,
        atomic_number: 7,
        coordination: 3,
        valence: 4,
        has_pi_lone_pair: false,
        multiple_bond_count: 1,
        aromatic: true,
        linear: false,
        single_bond_multiple_bond: false,
        equivalence_levels: [69, 9, 8, 0],
        description: "NITROGEN IN N-OXIDE",
    },
    Mmff94NumericTypeInfo {
        id: 70,
        symbol: "OH2",
        element: Element::O,
        atomic_number: 8,
        coordination: 2,
        valence: 2,
        has_pi_lone_pair: true,
        multiple_bond_count: 0,
        aromatic: false,
        linear: false,
        single_bond_multiple_bond: false,
        equivalence_levels: [70, 70, 70, 70],
        description: "OXYGEN IN WATER",
    },
    Mmff94NumericTypeInfo {
        id: 71,
        symbol: "HS",
        element: Element::H,
        atomic_number: 1,
        coordination: 1,
        valence: 1,
        has_pi_lone_pair: false,
        multiple_bond_count: 0,
        aromatic: false,
        linear: false,
        single_bond_multiple_bond: false,
        equivalence_levels: [71, 5, 5, 0],
        description: "H-S",
    },
    Mmff94NumericTypeInfo {
        id: 72,
        symbol: "S2CM",
        element: Element::S,
        atomic_number: 16,
        coordination: 1,
        valence: 1,
        has_pi_lone_pair: true,
        multiple_bond_count: 1,
        aromatic: false,
        linear: false,
        single_bond_multiple_bond: false,
        equivalence_levels: [72, 16, 15, 0],
        description: "THIOCARBOXYLATE S",
    },
    Mmff94NumericTypeInfo {
        id: 73,
        symbol: "SO2M",
        element: Element::S,
        atomic_number: 16,
        coordination: 3,
        valence: 3,
        has_pi_lone_pair: false,
        multiple_bond_count: 0,
        aromatic: false,
        linear: false,
        single_bond_multiple_bond: false,
        equivalence_levels: [73, 18, 15, 0],
        description: "SULFUR IN SULFINATE",
    },
    Mmff94NumericTypeInfo {
        id: 74,
        symbol: "=S=O",
        element: Element::S,
        atomic_number: 16,
        coordination: 2,
        valence: 4,
        has_pi_lone_pair: false,
        multiple_bond_count: 2,
        aromatic: false,
        linear: false,
        single_bond_multiple_bond: false,
        equivalence_levels: [74, 17, 15, 0],
        description: "SULFINYL SULFUR, C=S=O",
    },
    Mmff94NumericTypeInfo {
        id: 75,
        symbol: "-P=C",
        element: Element::P,
        atomic_number: 15,
        coordination: 2,
        valence: 3,
        has_pi_lone_pair: false,
        multiple_bond_count: 2,
        aromatic: false,
        linear: false,
        single_bond_multiple_bond: true,
        equivalence_levels: [75, 26, 25, 0],
        description: "P DOUBLY BONDED TO C",
    },
    Mmff94NumericTypeInfo {
        id: 76,
        symbol: "N5M",
        element: Element::N,
        atomic_number: 7,
        coordination: 2,
        valence: 2,
        has_pi_lone_pair: true,
        multiple_bond_count: 0,
        aromatic: false,
        linear: false,
        single_bond_multiple_bond: false,
        equivalence_levels: [76, 9, 8, 0],
        description: "NEG N IN TETRAZOLE AN",
    },
    Mmff94NumericTypeInfo {
        id: 77,
        symbol: "CLO4",
        element: Element::CL,
        atomic_number: 17,
        coordination: 4,
        valence: 4,
        has_pi_lone_pair: false,
        multiple_bond_count: 0,
        aromatic: false,
        linear: false,
        single_bond_multiple_bond: false,
        equivalence_levels: [77, 12, 12, 0],
        description: "CHLORINE IN CLO4(-)",
    },
    Mmff94NumericTypeInfo {
        id: 78,
        symbol: "C5",
        element: Element::C,
        atomic_number: 6,
        coordination: 3,
        valence: 4,
        has_pi_lone_pair: false,
        multiple_bond_count: 2,
        aromatic: true,
        linear: false,
        single_bond_multiple_bond: true,
        equivalence_levels: [78, 2, 1, 0],
        description: "GENERAL AROM 5-RING C",
    },
    Mmff94NumericTypeInfo {
        id: 79,
        symbol: "N5",
        element: Element::N,
        atomic_number: 7,
        coordination: 2,
        valence: 3,
        has_pi_lone_pair: false,
        multiple_bond_count: 2,
        aromatic: true,
        linear: false,
        single_bond_multiple_bond: false,
        equivalence_levels: [79, 9, 8, 0],
        description: "GENERAL AROM 5-RING N",
    },
    Mmff94NumericTypeInfo {
        id: 80,
        symbol: "CIM+",
        element: Element::C,
        atomic_number: 6,
        coordination: 3,
        valence: 4,
        has_pi_lone_pair: false,
        multiple_bond_count: 2,
        aromatic: false,
        linear: false,
        single_bond_multiple_bond: true,
        equivalence_levels: [80, 2, 1, 0],
        description: "C IN N-C-N, IM+ ION",
    },
    Mmff94NumericTypeInfo {
        id: 81,
        symbol: "NIM+",
        element: Element::N,
        atomic_number: 7,
        coordination: 3,
        valence: 4,
        has_pi_lone_pair: false,
        multiple_bond_count: 1,
        aromatic: true,
        linear: false,
        single_bond_multiple_bond: true,
        equivalence_levels: [81, 10, 8, 0],
        description: "N IN N-C-N, IM+ ION",
    },
    Mmff94NumericTypeInfo {
        id: 82,
        symbol: "N5AX",
        element: Element::N,
        atomic_number: 7,
        coordination: 3,
        valence: 4,
        has_pi_lone_pair: false,
        multiple_bond_count: 1,
        aromatic: true,
        linear: false,
        single_bond_multiple_bond: false,
        equivalence_levels: [82, 9, 8, 0],
        description: "5R NITROGEN IN N-OXIDE",
    },
    Mmff94NumericTypeInfo {
        id: 87,
        symbol: "FE+2",
        element: Element::FE,
        atomic_number: 26,
        coordination: 0,
        valence: 0,
        has_pi_lone_pair: false,
        multiple_bond_count: 0,
        aromatic: false,
        linear: false,
        single_bond_multiple_bond: false,
        equivalence_levels: [87, 87, 87, 87],
        description: "IRON +2 CATION",
    },
    Mmff94NumericTypeInfo {
        id: 88,
        symbol: "FE+3",
        element: Element::FE,
        atomic_number: 26,
        coordination: 0,
        valence: 0,
        has_pi_lone_pair: false,
        multiple_bond_count: 0,
        aromatic: false,
        linear: false,
        single_bond_multiple_bond: false,
        equivalence_levels: [88, 88, 88, 88],
        description: "IRON +3 CATION",
    },
    Mmff94NumericTypeInfo {
        id: 89,
        symbol: "F-",
        element: Element::F,
        atomic_number: 9,
        coordination: 0,
        valence: 0,
        has_pi_lone_pair: false,
        multiple_bond_count: 0,
        aromatic: false,
        linear: false,
        single_bond_multiple_bond: false,
        equivalence_levels: [89, 89, 89, 89],
        description: "FLUORIDE ANION",
    },
    Mmff94NumericTypeInfo {
        id: 90,
        symbol: "CL-",
        element: Element::CL,
        atomic_number: 17,
        coordination: 0,
        valence: 0,
        has_pi_lone_pair: false,
        multiple_bond_count: 0,
        aromatic: false,
        linear: false,
        single_bond_multiple_bond: false,
        equivalence_levels: [90, 90, 90, 90],
        description: "CHLORIDE ANION",
    },
    Mmff94NumericTypeInfo {
        id: 91,
        symbol: "BR-",
        element: Element::BR,
        atomic_number: 35,
        coordination: 0,
        valence: 0,
        has_pi_lone_pair: false,
        multiple_bond_count: 0,
        aromatic: false,
        linear: false,
        single_bond_multiple_bond: false,
        equivalence_levels: [91, 91, 91, 91],
        description: "BROMIDE ANION",
    },
    Mmff94NumericTypeInfo {
        id: 92,
        symbol: "LI+",
        element: Element::LI,
        atomic_number: 3,
        coordination: 0,
        valence: 0,
        has_pi_lone_pair: false,
        multiple_bond_count: 0,
        aromatic: false,
        linear: false,
        single_bond_multiple_bond: false,
        equivalence_levels: [92, 92, 92, 92],
        description: "LITHIUM CATION",
    },
    Mmff94NumericTypeInfo {
        id: 93,
        symbol: "NA+",
        element: Element::NA,
        atomic_number: 11,
        coordination: 0,
        valence: 0,
        has_pi_lone_pair: false,
        multiple_bond_count: 0,
        aromatic: false,
        linear: false,
        single_bond_multiple_bond: false,
        equivalence_levels: [93, 93, 93, 93],
        description: "SODIUM CATION",
    },
    Mmff94NumericTypeInfo {
        id: 94,
        symbol: "K+",
        element: Element::K,
        atomic_number: 19,
        coordination: 0,
        valence: 0,
        has_pi_lone_pair: false,
        multiple_bond_count: 0,
        aromatic: false,
        linear: false,
        single_bond_multiple_bond: false,
        equivalence_levels: [94, 94, 94, 94],
        description: "POTASSIUM CATION",
    },
    Mmff94NumericTypeInfo {
        id: 95,
        symbol: "ZN+2",
        element: Element::ZN,
        atomic_number: 30,
        coordination: 0,
        valence: 0,
        has_pi_lone_pair: false,
        multiple_bond_count: 0,
        aromatic: false,
        linear: false,
        single_bond_multiple_bond: false,
        equivalence_levels: [95, 95, 95, 95],
        description: "DIPOSITIVE ZINC CATION",
    },
    Mmff94NumericTypeInfo {
        id: 96,
        symbol: "CA+2",
        element: Element::CA,
        atomic_number: 20,
        coordination: 0,
        valence: 0,
        has_pi_lone_pair: false,
        multiple_bond_count: 0,
        aromatic: false,
        linear: false,
        single_bond_multiple_bond: false,
        equivalence_levels: [96, 96, 96, 96],
        description: "DIPOSITIVE CALCIUM CATION",
    },
    Mmff94NumericTypeInfo {
        id: 97,
        symbol: "CU+1",
        element: Element::CU,
        atomic_number: 29,
        coordination: 0,
        valence: 0,
        has_pi_lone_pair: false,
        multiple_bond_count: 0,
        aromatic: false,
        linear: false,
        single_bond_multiple_bond: false,
        equivalence_levels: [97, 97, 97, 97],
        description: "MONOPOSITIVE COPPER CATION",
    },
    Mmff94NumericTypeInfo {
        id: 98,
        symbol: "CU+2",
        element: Element::CU,
        atomic_number: 29,
        coordination: 0,
        valence: 0,
        has_pi_lone_pair: false,
        multiple_bond_count: 0,
        aromatic: false,
        linear: false,
        single_bond_multiple_bond: false,
        equivalence_levels: [98, 98, 98, 98],
        description: "DIPOSITIVE COPPER CATION",
    },
    Mmff94NumericTypeInfo {
        id: 99,
        symbol: "MG+2",
        element: Element::MG,
        atomic_number: 12,
        coordination: 0,
        valence: 0,
        has_pi_lone_pair: false,
        multiple_bond_count: 0,
        aromatic: false,
        linear: false,
        single_bond_multiple_bond: false,
        equivalence_levels: [99, 99, 99, 99],
        description: "DIPOSITIVE MAGNESIUM CATION",
    },
];

/// Look up a numeric MMFF94 type's authoritative metadata.
///
/// `MMFF94_NUMERIC_TYPE_REGISTRY` is sorted by ascending `id` (types
/// are emitted in the source table's natural order, which is already
/// ascending), so this binary-searches rather than scanning linearly.
pub fn mmff94_numeric_type_info(id: u8) -> Option<&'static Mmff94NumericTypeInfo> {
    MMFF94_NUMERIC_TYPE_REGISTRY
        .binary_search_by_key(&id, |info| info.id)
        .ok()
        .map(|idx| &MMFF94_NUMERIC_TYPE_REGISTRY[idx])
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn registry_is_sorted_by_id() {
        let ids: Vec<u8> = MMFF94_NUMERIC_TYPE_REGISTRY.iter().map(|i| i.id).collect();
        let mut sorted = ids.clone();
        sorted.sort_unstable();
        assert_eq!(ids, sorted, "generator must emit ascending id order");
    }

    #[test]
    fn benzene_type_37_is_aromatic_carbon() {
        let info = mmff94_numeric_type_info(37).expect("type 37");
        assert_eq!(info.symbol, "CB");
        assert_eq!(info.element, Element::C);
        assert!(info.aromatic);
    }

    #[test]
    fn furan_alpha_carbon_type_63_is_carbon_not_the_old_wrong_symbol() {
        let info = mmff94_numeric_type_info(63).expect("type 63");
        assert_eq!(info.symbol, "C5A");
        assert_eq!(info.element, Element::C);
    }

    #[test]
    fn pyridine_n_type_38_is_nitrogen() {
        let info = mmff94_numeric_type_info(38).expect("type 38");
        assert_eq!(info.symbol, "NPYD");
        assert_eq!(info.element, Element::N);
    }
}
